In [1]:
using Plots
gr()

Plots.GRBackend()

Considere o seguinte problema de ajustar um conjunto de pontos por uma reta

In [47]:
m = 10
x = linspace(-3, 7, m)
y = 1.9 + 0.6*x + randn(m)*0.2 # Gerando pontos aleatórios

scatter(x, y, leg=false)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -2 
 
 
 0 
 
 
 2 
 
 
 4 
 
 
 6 
 
 
 0.0 
 
 
 2.5 
 
 
 5.0

Não existe uma reta que passa por todos esses pontos. Inclusive, alguns deles podem ter o mesmo $x$,
de modo que não existe nenhum função que passa por eles.
Sendo assim, precisamos encontrar uma reta que aproxima estes pontos.

Essa reta é definida por $L(x) = \alpha + \beta x$, e precisamos encontrar esses valores para $\alpha$ e $\beta$.
Como?

Uma estratégia é considerar o erro de aproximação e tentar minimizá-lo.
Vamos separar o erro termo a termo, obtendo assim um Erro$_i$, que depende
dos valores de $\alpha$ e $\beta$.

Nosso problema pode ser escrito como
$$ \min E(\alpha,\beta) = \sum_{i=1}^m \mbox{Erro}_i(\alpha,\beta). $$

Já sabemos que para minimizar uma função, devemos buscar seus pontos críticos.
Isto é,
$$ \frac{\partial E}{\partial \alpha} = 0, $$
e
$$ \frac{\partial E}{\partial \beta} = 0. $$

Para calcular essa derivada, devemos calcular a derivada de Erro$_i$.
Então, a escolha dessa função de erro deve ser bem pensada, para que seja
significativa e fácil de derivar.

A escolha mais comum é Erro$_i = \frac{1}{2}[\alpha + \beta x_i - y_i]^2 = \frac{1}{2}[L(x_i) - y_i]^2$.

Essa escolha é boa pois a derivada dessa função é fácil de calcular, e é fácil de visualizar que é a distância vertical da reta ao ponto $(x_i,y_i)$.

In [48]:
E(α,β) = sum( 0.5*(α + β*x - y).^2)

E (generic function with 1 method)

In [49]:
E(0,0)

70.91533193598852

In [50]:
E(2,0)

26.961731344500812

In [51]:
E(2,0.5)

1.1890120804851914

In [52]:
using Interact

scaleE = max(E(1.0, 0.3), E(3.0, 0.7))

@manipulate for α = linspace(1.0, 3.0, 100), β = linspace(0.3, 0.7, 100)
    scatter(x, y, leg=false)
    plot!(x->α + β*x, x[1], x[m], c=:red, lw=2)
    scatter!([2.5], [1.0], ms=E(α,β)*30/scaleE*5)
    ylims!(extrema(y)...)
end

Interact.Slider{Float64}(Signal{Float64}(1.9898989898989898, nactions=0),"α",1.9898989898989898,linspace(1.0,3.0,100),true)

Interact.Slider{Float64}(Signal{Float64}(0.49797979797979797, nactions=0),"β",0.49797979797979797,linspace(0.3,0.7,100),true)

É fácil ver que

$$ E_{\alpha}(\alpha,\beta) = \sum_{i=1}^m (\alpha + \beta x_i - y_i), $$
e
$$ E_{\beta}(\alpha,\beta) = \sum_{i=1}^m x_i (\alpha + \beta x_i - y_i). $$

Se nosso objetivo é encontrar $\alpha$ e $\beta$ tal que isso seja zero, é fácil ver que

\begin{align*}
\alpha \bigg(\sum_{i=1}^m 1\bigg) + \beta\bigg(\sum_{i=1}^m x_i\bigg) & = \sum_{i=1}^m y_i \\
\alpha \bigg(\sum_{i=1}^m x_i\bigg) + \beta\bigg(\sum_{i=1}^m x_i^2\bigg) & = \sum_{i=1}^m x_i y_i
\end{align*}

Esse sistema é bastante fácil de resolver.

In [53]:
dot(x, y)

127.00840149099422

In [54]:
x'*y

1-element Array{Float64,1}:
 127.008

In [55]:
M = [m  sum(x); sum(x)   dot(x,x)]

2x2 Array{Float64,2}:
 10.0   20.0  
 20.0  141.852

In [56]:
b = [sum(y); dot(x,y)]

2-element Array{Float64,1}:
  31.9768
 127.008 

In [57]:
α, β = M\b

2-element Array{Float64,1}:
 1.95951 
 0.619083

In [58]:
E(α,β)

0.2714506701374105

In [59]:
scatter(x, y, leg=false)
plot!(x->α + β*x, x[1], x[m], c=:red, lw=2)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -2 
 
 
 0 
 
 
 2 
 
 
 4 
 
 
 6 
 
 
 0.0 
 
 
 2.5 
 
 
 5.0 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:1.6; stroke-opacity:1; fill:none" points="
 51.3,351.482 56.6423,348.078 61.9847,344.674 67.3271,341.27 72.6695,337.866 78.0119,334.462 83.3543,331.058 88.6967,327.654 94.039,324.251 99.3814,320.847 
 104.724,317.443 110.066,314.039 115.409,310.635 120.751,307.231 126.093,303.827 131.436,300.423 136.778,297.02 142.121,293.616 147.463,290.212 152.805,286.808 
 158.148,283.404 163.49,280 168.832,276.596 174.175,273.192 179.517,269.788 184.86,266.385 190.202,262.981 195.544,259.577 200.887,256.173 206.229,252.769 
 211.572,249.365 216.914,245.961 222.256,242.557 227.599,239.154 232.941,235.75 238.283,232.346 243.626,228.942 248.968,225.538 254.311,222.134 259.653,218.73 
 264.995,215.326 270.338,211.923 275.68,208.519 281.023,205.115 286.365,201.711 291.707,198.307 297.05,194.903 302.392,191.499 307.734,188.095 313.077,184.692 
 318.419,181.288 323.762,177.884 329.104,174.48 334.446,171.076 339.789,167.672 345.131,164.268 350.474,160.864 355.816,157.46 361.158,154.057 366.501,150.653 
 371.843,147.249 377.185,143.845 382.528,140.441 387.87,137.037 393.213,133.633 398.555,130.229 403.897,126.826 409.24,123.422 414.582,120.018 419.925,116.614 
 425.267,113.21 430.609,109.806 435.952,106.402 441.294,102.998 446.636,99.5946 451.979,96.1907 457.321,92.7868 462.664,89.3829 468.006,85.979 473.348,82.5752 
 478.691,79.1713 484.033,75.7674 489.376,72.3635 494.718,68.9597 500.06,65.5558 505.403,62.1519 510.745,58.748 516.087,55.3441 521.43,51.9403 526.772,48.5364 
 532.115,45.1325 537.457,41.7286 542.799,38.3247 548.142,34.9209 553.484,31.517 558.827,28.1131 564.169,24.7092 569.511,21.3054 574.854,17.9015 580.196,14.4976 
 
 "/>

In [62]:
m = 52
t = linspace(0, 1, m)

phi1(t) = sin(2pi*t)
phi2(t) = cos(2pi*t)
phi3(t) = 1

C = 4*phi1(t) + 3*phi2(t) + 22*phi3(t) + rand(m)*1.2

scatter(t, C, leg=false)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 20

In [74]:
# Montar M

F = [phi1, phi2, phi3]
M = zeros(3,3)
c = zeros(3)
for k = 1:3
    for j = 1:3
        for i = 1:m
            M[k,j] += F[k](t[i]) * F[j](t[i])
        end
    end
    for i = 1:m
        c[k] += F[k](t[i]) * C[i]
    end
end

In [75]:
α = M\c

3-element Array{Float64,1}:
  3.90236
  2.99954
 22.5404 

In [76]:
scatter(t, C, leg=false)
plot!(t->α[1]*phi1(t) + α[2]*phi2(t) + α[3]*phi3(t), 0, 1, c=:red, lw=2)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 20 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:1.6; stroke-opacity:1; fill:none" points="
 51.3,90.1357 56.6423,82.0172 61.9847,74.3375 67.3271,67.1275 72.6695,60.4162 78.0119,54.2307 83.3543,48.5959 88.6967,43.5344 94.039,39.0666 99.3814,35.2106 
 104.724,31.9818 110.066,29.3933 115.409,27.4555 120.751,26.1761 126.093,25.5604 131.436,25.6108 136.778,26.3271 142.121,27.7064 147.463,29.7432 152.805,32.4292 
 158.148,35.7537 163.49,39.7033 168.832,44.262 174.175,49.4116 179.517,55.1312 184.86,61.3978 190.202,68.1863 195.544,75.4692 200.887,83.2173 206.229,91.3994 
 211.572,99.9824 216.914,108.932 222.256,118.212 227.599,127.785 232.941,137.612 238.283,147.654 243.626,157.871 248.968,168.221 254.311,178.663 259.653,189.155 
 264.995,199.653 270.338,210.117 275.68,220.504 281.023,230.772 286.365,240.88 291.707,250.787 297.05,260.453 302.392,269.839 307.734,278.908 313.077,287.623 
 318.419,295.949 323.762,303.852 329.104,311.301 334.446,318.265 339.789,324.716 345.131,330.629 350.474,335.98 355.816,340.747 361.158,344.911 366.501,348.456 
 371.843,351.366 377.185,353.63 382.528,355.239 387.87,356.187 393.213,356.47 398.555,356.087 403.897,355.038 409.24,353.329 414.582,350.967 419.925,347.96 
 425.267,344.321 430.609,340.065 435.952,335.208 441.294,329.771 446.636,323.775 451.979,317.244 457.321,310.205 462.664,302.685 468.006,294.716 473.348,286.33 
 478.691,277.559 484.033,268.44 489.376,259.009 494.718,249.304 500.06,239.364 505.403,229.229 510.745,218.94 516.087,208.539 521.43,198.067 526.772,187.567 
 532.115,177.08 537.457,166.65 542.799,156.317 548.142,146.124 553.484,136.111 558.827,126.32 564.169,116.789 569.511,107.557 574.854,98.6603 580.196,90.1357 
 
 "/>

In [83]:
x = linspace(-1, 1, 100)
y = x.^2 - 0.2x + 0.4 + rand(100)*0.3

scatter(x, y)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 0.5 
 
 
 1.0 
 
 
 1.5 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1

Achar $\alpha_1$, $\alpha_2$ e $\alpha_3$ tais que 
$f(x) = \alpha_1 + \alpha_2x + \alpha_3x^2$ seja o modelo ótimo.

Plotar os dados com scatter.
Plotar a curva ótima por cima.