# Interpolação

Dado um conjunto de pontos $(x_i,y_i), i = 1,\dots,m$, nos interessa agora encontrar uma função $f$ tal que $f(x_i) = y_i$.

É importante notar a diferença desse tipo de problema com o problema de quadrados mínimos.
No segundo, dado um modelo de funções, qual delas melhor representa esse conjunto de dados. Na outra, buscamos alguma função que passa exatamente em todos esses pontos.

Embora bastante parecidos, em quadrados mínimos é esperado que os dados tenham algum erro de medida, ou que sejam em enorme quantidade, invalidando a busca por pontos que passam exatamente por cima do conjunto. Em interpolação, os pontos são todos considerados importantes, e por isso queremos passar em todos.

Um exemplo muito comum é o de aproximações de uma função num intervalo $[a,b]$ dado.
Por exemplo, uma função muito complicada pode ser simplificada nesse intervalo usando funções mais simples. Os motivos para querer isso poder ser variados, e como escolher os pontos nesse intervalo também, mas a questão é que isso leva a um conjunto de dados para interpolação.

A primeira coisa que percebemos é que para passar em todos os pontos, devemos ter $x_i \neq x_j$ para todo $i \neq j$. Então a partir de agora, esta será uma hipótese.

A segunda coisa que percebemos é que, se usarmos uma função do tipo
$f(x) = \alpha_1\phi_1(x) + \dots + \alpha_n\phi_n(x)$ para passar em todos os pontos, precisaremos de $m$ funções, num caso geral. Isso quer dizer que o problema pode complicar bastante para uma quantidade muito grande de pontos. Dependendo dos pontos $x_i$ isso pode não ser um problema. Alternativamente, podemos usar outros métodos de interpolação para gerar uma função passando nos pontos dados mas que não seja um modelo como o dado acima.

## Interpolação polinomial

O primeiro modelo de interpolação é o de interpolação polinomial.
Dado um conjunto de dados $(x_i,y_i), i = 1,\dots,m$, valor interpolar estes pontos usando
um polinômio $f(x) = a_0 + a_1x + a_2x^2 + \dots + a_{m-1}x^{m-1}$.

A maneira mais simples de tentar resolver este problema é através do sistema linear gerado pelas igualdades $f(x_i) = y_i, i = 1,\dots,m$.

In [1]:
x = collect(0:5)/5
y = exp(x)
m = length(x)
A = Float64[x[i].^j for i = 1:m, j = 0:m-1]

6x6 Array{Float64,2}:
 1.0  0.0  0.0   0.0    0.0     0.0    
 1.0  0.2  0.04  0.008  0.0016  0.00032
 1.0  0.4  0.16  0.064  0.0256  0.01024
 1.0  0.6  0.36  0.216  0.1296  0.07776
 1.0  0.8  0.64  0.512  0.4096  0.32768
 1.0  1.0  1.0   1.0    1.0     1.0    

In [2]:
a = A\y

6-element Array{Float64,1}:
 1.0      
 1.00008  
 0.499069 
 0.17041  
 0.0348664
 0.0138543

In [3]:
using Plots
gr()

Plots.GRBackend()

In [4]:
scatter(x, y, ms=3)

[Plots.jl] Initializing backend: gr


<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 1 
 
 
 2 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1

In [5]:
plot!(x->a[1]+a[2]*x+a[3]*x^2+a[4]*x^3+a[5]*x^4+a[6]*x^5, x[1], x[end], c=:red)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 1 
 
 
 2 
 
 
 
 
 
 
 
 
 
 
 
 
 
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 51.3,366.517 56.6423,364.437 61.9847,362.336 67.3271,360.214 72.6695,358.07 78.0119,355.904 83.3543,353.717 88.6967,351.507 94.039,349.275 99.3814,347.02 
 104.724,344.742 110.066,342.441 115.409,340.117 120.751,337.769 126.093,335.397 131.436,333.002 136.778,330.582 142.121,328.137 147.463,325.667 152.805,323.173 
 158.148,320.653 163.49,318.108 168.832,315.536 174.175,312.939 179.517,310.315 184.86,307.665 190.202,304.987 195.544,302.283 200.887,299.551 206.229,296.791 
 211.572,294.004 216.914,291.187 222.256,288.343 227.599,285.469 232.941,282.567 238.283,279.635 243.626,276.673 248.968,273.681 254.311,270.658 259.653,267.605 
 264.995,264.521 270.338,261.406 275.68,258.259 281.023,255.08 286.365,251.869 291.707,248.625 297.05,245.348 302.392,242.038 307.734,238.695 313.077,235.317 
 318.419,231.905 323.762,228.459 329.104,224.977 334.446,221.461 339.789,217.908 345.131,214.319 350.474,210.694 355.816,207.033 361.158,203.334 366.501,199.597 
 371.843,195.823 377.185,192.01 382.528,188.159 387.87,184.268 393.213,180.338 398.555,176.368 403.897,172.358 409.24,168.307 414.582,164.215 419.925,160.081 
 425.267,155.905 430.609,151.687 435.952,147.426 441.294,143.122 446.636,138.775 451.979,134.383 457.321,129.946 462.664,125.464 468.006,120.937 473.348,116.364 
 478.691,111.745 484.033,107.078 489.376,102.365 494.718,97.6029 500.06,92.793 505.403,87.9342 510.745,83.026 516.087,78.0681 521.43,73.0598 526.772,68.0007 
 532.115,62.8902 537.457,57.7278 542.799,52.5131 548.142,47.2454 553.484,41.9242 558.827,36.5491 564.169,31.1194 569.511,25.6347 574.854,20.0942 580.196,14.4976 
 
 "/>
 
 
 
 
 
 
 
 y1 
 
 
 
 y2

Escrever tudo isso não dá, então vamos criar uma função pra fazer isso

In [6]:
"""
    p = poli_eval(x, a)

Dados os coeficientes `a`, calcula o valor de
`a[1] + a[2]*x + … + a[m]*x^(m-1)`.
"""
function poli_eval(x, a)
    p = a[1]
    m = length(a)
    xx = 1.0
    for i = 2:m
        xx *= x
        p += a[i]*xx
    end
    return p
end

poli_eval (generic function with 1 method)

In [7]:
?poli_eval

search: poli_eval



```
p = poli_eval(x, a)
```

Dados os coeficientes `a`, calcula o valor de `a[1] + a[2]*x + … + a[m]*x^(m-1)`.


In [8]:
scatter(x, y)
plot!(x->poli_eval(x, a), x[1], x[end])

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 1 
 
 
 2 
 
 
 
 
 
 
 
 
 
 
 
 
 
<polyline clip-path="url(#clip02)" style="stroke:#e9746a; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 51.3,366.517 56.6423,364.437 61.9847,362.336 67.3271,360.214 72.6695,358.07 78.0119,355.904 83.3543,353.717 88.6967,351.507 94.039,349.275 99.3814,347.02 
 104.724,344.742 110.066,342.441 115.409,340.117 120.751,337.769 126.093,335.397 131.436,333.002 136.778,330.582 142.121,328.137 147.463,325.667 152.805,323.173 
 158.148,320.653 163.49,318.108 168.832,315.536 174.175,312.939 179.517,310.315 184.86,307.665 190.202,304.987 195.544,302.283 200.887,299.551 206.229,296.791 
 211.572,294.004 216.914,291.187 222.256,288.343 227.599,285.469 232.941,282.567 238.283,279.635 243.626,276.673 248.968,273.681 254.311,270.658 259.653,267.605 
 264.995,264.521 270.338,261.406 275.68,258.259 281.023,255.08 286.365,251.869 291.707,248.625 297.05,245.348 302.392,242.038 307.734,238.695 313.077,235.317 
 318.419,231.905 323.762,228.459 329.104,224.977 334.446,221.461 339.789,217.908 345.131,214.319 350.474,210.694 355.816,207.033 361.158,203.334 366.501,199.597 
 371.843,195.823 377.185,192.01 382.528,188.159 387.87,184.268 393.213,180.338 398.555,176.368 403.897,172.358 409.24,168.307 414.582,164.215 419.925,160.081 
 425.267,155.905 430.609,151.687 435.952,147.426 441.294,143.122 446.636,138.775 451.979,134.383 457.321,129.946 462.664,125.464 468.006,120.937 473.348,116.364 
 478.691,111.745 484.033,107.078 489.376,102.365 494.718,97.6029 500.06,92.793 505.403,87.9342 510.745,83.026 516.087,78.0681 521.43,73.0598 526.772,68.0007 
 532.115,62.8902 537.457,57.7278 542.799,52.5131 548.142,47.2454 553.484,41.9242 558.827,36.5491 564.169,31.1194 569.511,25.6347 574.854,20.0942 580.196,14.4976 
 
 "/>
 
 
 
 
 
 
 
 y1 
 
 
 
 y2

Em outras linguagens a criação da matriz não é tão simples.
Vamos fazer uma função para ela, e dar seu nome oficial: Matriz de Vandermonde

In [9]:
function vandermonde(x)
    m = length(x)
    A = zeros(m, m)
    for i = 1:m
        xx = 1.0
        for j = 1:m
            A[i,j] = xx
            xx *= x[i]
        end
    end
    return A
end

vandermonde (generic function with 1 method)

In [10]:
vandermonde(x)

6x6 Array{Float64,2}:
 1.0  0.0  0.0   0.0    0.0     0.0    
 1.0  0.2  0.04  0.008  0.0016  0.00032
 1.0  0.4  0.16  0.064  0.0256  0.01024
 1.0  0.6  0.36  0.216  0.1296  0.07776
 1.0  0.8  0.64  0.512  0.4096  0.32768
 1.0  1.0  1.0   1.0    1.0     1.0    

A matriz de Vandermonde tem o sério problema de ser mal-condicionada.

In [11]:
A = vandermonde(linspace(1,10,10))

10x10 Array{Float64,2}:
 1.0   1.0    1.0     1.0      1.0  …       1.0             1.0      
 1.0   2.0    4.0     8.0     16.0        256.0           512.0      
 1.0   3.0    9.0    27.0     81.0       6561.0         19683.0      
 1.0   4.0   16.0    64.0    256.0      65536.0        262144.0      
 1.0   5.0   25.0   125.0    625.0     390625.0             1.95313e6
 1.0   6.0   36.0   216.0   1296.0  …       1.67962e6       1.00777e7
 1.0   7.0   49.0   343.0   2401.0          5.7648e6        4.03536e7
 1.0   8.0   64.0   512.0   4096.0          1.67772e7       1.34218e8
 1.0   9.0   81.0   729.0   6561.0          4.30467e7       3.8742e8 
 1.0  10.0  100.0  1000.0  10000.0          1.0e8           1.0e9    

In [12]:
cond(A)

2.106257837668719e12

In [13]:
b = A*ones(10)
A\b

10-element Array{Float64,1}:
 1.00001 
 0.999977
 1.00002 
 0.999988
 1.0     
 0.999999
 1.0     
 1.0     
 1.0     
 1.0     

Então, a resolução direta desse sistema é impraticável para qualquer coisa maior que uns 5 elementos. Vamos ver outras duas maneiras de fazer a interpolação polinomial.

## Polinômio de Lagrange

O polinômio de Lagrange que interpola os pontos $(x_i,y_i), i =1,\dots,m$ é uma soma de polinômios, cada um construído de uma maneira inteligente para passar nos pontos acima.

A forma de Lagrange é
$$ L(x) = \sum_{i=1}^m y_i \ell_i(x), $$
onde
$$ \ell_i(x) = \prod_{j=1, j\neq i}^m \frac{x-x_j}{x_i-x_j}. $$

Dessa maneira, $ \ell_i(x_j) = 0 $ para todo $j \neq i$, mas $\ell_i(x_i) = 1$,
e daí, $L(x_i) = y_i$.

In [14]:
function lag(x, i, xv)
    l = 1.0
    m = length(xv)
    for j = 1:m
        if i == j
            continue
        end
        if x == xv[j]
            return 0.0
        end
        l *= (x - xv[j])/(xv[i] - xv[j])
    end
    return l
end

lag (generic function with 1 method)

In [15]:
scatter(x, y)
for i = 1:m
    plot!(t->y[i]*lag(t, i, x), x[1], x[end])
end
plot!()

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 
 
 
 
 
 
 
 
 
 
 
<polyline clip-path="url(#clip02)" style="stroke:#e9746a; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 51.3,159.386 56.6423,168.306 61.9847,176.499 67.3271,184.006 72.6695,190.866 78.0119,197.119 83.3543,202.803 88.6967,207.953 94.039,212.603 99.3814,216.786 
 104.724,220.536 110.066,223.881 115.409,226.85 120.751,229.473 126.093,231.774 131.436,233.781 136.778,235.516 142.121,237.002 147.463,238.262 152.805,239.316 
 158.148,240.183 163.49,240.883 168.832,241.432 174.175,241.848 179.517,242.144 184.86,242.337 190.202,242.439 195.544,242.463 200.887,242.421 206.229,242.324 
 211.572,242.182 216.914,242.004 222.256,241.798 227.599,241.573 232.941,241.334 238.283,241.09 243.626,240.844 248.968,240.603 254.311,240.37 259.653,240.149 
 264.995,239.944 270.338,239.757 275.68,239.59 281.023,239.445 286.365,239.323 291.707,239.225 297.05,239.151 302.392,239.101 307.734,239.075 313.077,239.072 
 318.419,239.091 323.762,239.131 329.104,239.19 334.446,239.266 339.789,239.358 345.131,239.463 350.474,239.579 355.816,239.704 361.158,239.835 366.501,239.97 
 371.843,240.105 377.185,240.239 382.528,240.369 387.87,240.493 393.213,240.607 398.555,240.709 403.897,240.798 409.24,240.871 414.582,240.926 419.925,240.962 
 425.267,240.977 430.609,240.969 435.952,240.939 441.294,240.884 446.636,240.805 451.979,240.702 457.321,240.576 462.664,240.426 468.006,240.255 473.348,240.064 
 478.691,239.856 484.033,239.632 489.376,239.397 494.718,239.155 500.06,238.909 505.403,238.665 510.745,238.429 516.087,238.207 521.43,238.006 526.772,237.834 
 532.115,237.7 537.457,237.613 542.799,237.584 548.142,237.623 553.484,237.742 558.827,237.954 564.169,238.273 569.511,238.714 574.854,239.292 580.196,240.024 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#3cb370; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 51.3,240.024 56.6423,216.727 61.9847,196.434 67.3271,178.934 72.6695,164.022 78.0119,151.504 83.3543,141.194 88.6967,132.913 94.039,126.49 99.3814,121.764 
 104.724,118.579 110.066,116.789 115.409,116.252 120.751,116.838 126.093,118.418 131.436,120.876 136.778,124.098 142.121,127.979 147.463,132.42 152.805,137.328 
 158.148,142.616 163.49,148.202 168.832,154.012 174.175,159.976 179.517,166.029 184.86,172.112 190.202,178.172 195.544,184.158 200.887,190.028 206.229,195.74 
 211.572,201.261 216.914,206.558 222.256,211.606 227.599,216.38 232.941,220.863 238.283,225.038 243.626,228.894 248.968,232.421 254.311,235.614 259.653,238.471 
 264.995,240.992 270.338,243.18 275.68,245.039 281.023,246.579 286.365,247.808 291.707,248.739 297.05,249.385 302.392,249.762 307.734,249.887 313.077,249.778 
 318.419,249.455 323.762,248.939 329.104,248.25 334.446,247.411 339.789,246.445 345.131,245.375 350.474,244.225 355.816,243.017 361.158,241.775 366.501,240.523 
 371.843,239.282 377.185,238.076 382.528,236.925 387.87,235.85 393.213,234.87 398.555,234.004 403.897,233.269 409.24,232.679 414.582,232.248 419.925,231.988 
 425.267,231.908 430.609,232.017 435.952,232.318 441.294,232.816 446.636,233.508 451.979,234.394 457.321,235.466 462.664,236.716 468.006,238.131 473.348,239.695 
 478.691,241.389 484.033,243.189 489.376,245.068 494.718,246.994 500.06,248.932 505.403,250.842 510.745,252.678 516.087,254.39 521.43,255.925 526.772,257.223 
 532.115,258.218 537.457,258.84 542.799,259.013 548.142,258.656 553.484,257.68 558.827,255.992 564.169,253.493 569.511,250.074 574.854,245.625 580.196,240.024 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#d96fd5; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 51.3,240.024 56.6423,267.742 61.9847,290.432 67.3271,308.524 72.6695,322.423 78.0119,332.518 83.3543,339.18 88.6967,342.758 94.039,343.588 99.3814,341.984 
 104.724,338.244 110.066,332.651 115.409,325.471 120.751,316.951 126.093,307.3

In [16]:
function Lag(x, xv, y)
    s = 0.0
    m = length(xv)
    for i = 1:m
        s += lag(x, i, xv)*y[i]
    end
    return s
end

Lag (generic function with 1 method)

In [17]:
plot!(t->Lag(t, x, y), x[1], x[end], c=:black, lw=2)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 
 
 
 
 
 
 
 
 
 
 
<polyline clip-path="url(#clip02)" style="stroke:#e9746a; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 51.3,159.386 56.6423,168.306 61.9847,176.499 67.3271,184.006 72.6695,190.866 78.0119,197.119 83.3543,202.803 88.6967,207.953 94.039,212.603 99.3814,216.786 
 104.724,220.536 110.066,223.881 115.409,226.85 120.751,229.473 126.093,231.774 131.436,233.781 136.778,235.516 142.121,237.002 147.463,238.262 152.805,239.316 
 158.148,240.183 163.49,240.883 168.832,241.432 174.175,241.848 179.517,242.144 184.86,242.337 190.202,242.439 195.544,242.463 200.887,242.421 206.229,242.324 
 211.572,242.182 216.914,242.004 222.256,241.798 227.599,241.573 232.941,241.334 238.283,241.09 243.626,240.844 248.968,240.603 254.311,240.37 259.653,240.149 
 264.995,239.944 270.338,239.757 275.68,239.59 281.023,239.445 286.365,239.323 291.707,239.225 297.05,239.151 302.392,239.101 307.734,239.075 313.077,239.072 
 318.419,239.091 323.762,239.131 329.104,239.19 334.446,239.266 339.789,239.358 345.131,239.463 350.474,239.579 355.816,239.704 361.158,239.835 366.501,239.97 
 371.843,240.105 377.185,240.239 382.528,240.369 387.87,240.493 393.213,240.607 398.555,240.709 403.897,240.798 409.24,240.871 414.582,240.926 419.925,240.962 
 425.267,240.977 430.609,240.969 435.952,240.939 441.294,240.884 446.636,240.805 451.979,240.702 457.321,240.576 462.664,240.426 468.006,240.255 473.348,240.064 
 478.691,239.856 484.033,239.632 489.376,239.397 494.718,239.155 500.06,238.909 505.403,238.665 510.745,238.429 516.087,238.207 521.43,238.006 526.772,237.834 
 532.115,237.7 537.457,237.613 542.799,237.584 548.142,237.623 553.484,237.742 558.827,237.954 564.169,238.273 569.511,238.714 574.854,239.292 580.196,240.024 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#3cb370; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 51.3,240.024 56.6423,216.727 61.9847,196.434 67.3271,178.934 72.6695,164.022 78.0119,151.504 83.3543,141.194 88.6967,132.913 94.039,126.49 99.3814,121.764 
 104.724,118.579 110.066,116.789 115.409,116.252 120.751,116.838 126.093,118.418 131.436,120.876 136.778,124.098 142.121,127.979 147.463,132.42 152.805,137.328 
 158.148,142.616 163.49,148.202 168.832,154.012 174.175,159.976 179.517,166.029 184.86,172.112 190.202,178.172 195.544,184.158 200.887,190.028 206.229,195.74 
 211.572,201.261 216.914,206.558 222.256,211.606 227.599,216.38 232.941,220.863 238.283,225.038 243.626,228.894 248.968,232.421 254.311,235.614 259.653,238.471 
 264.995,240.992 270.338,243.18 275.68,245.039 281.023,246.579 286.365,247.808 291.707,248.739 297.05,249.385 302.392,249.762 307.734,249.887 313.077,249.778 
 318.419,249.455 323.762,248.939 329.104,248.25 334.446,247.411 339.789,246.445 345.131,245.375 350.474,244.225 355.816,243.017 361.158,241.775 366.501,240.523 
 371.843,239.282 377.185,238.076 382.528,236.925 387.87,235.85 393.213,234.87 398.555,234.004 403.897,233.269 409.24,232.679 414.582,232.248 419.925,231.988 
 425.267,231.908 430.609,232.017 435.952,232.318 441.294,232.816 446.636,233.508 451.979,234.394 457.321,235.466 462.664,236.716 468.006,238.131 473.348,239.695 
 478.691,241.389 484.033,243.189 489.376,245.068 494.718,246.994 500.06,248.932 505.403,250.842 510.745,252.678 516.087,254.39 521.43,255.925 526.772,257.223 
 532.115,258.218 537.457,258.84 542.799,259.013 548.142,258.656 553.484,257.68 558.827,255.992 564.169,253.493 569.511,250.074 574.854,245.625 580.196,240.024 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#d96fd5; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 51.3,240.024 56.6423,267.742 61.9847,290.432 67.3271,308.524 72.6695,322.423 78.0119,332.518 83.3543,339.18 88.6967,342.758 94.039,343.588 99.3814,341.984 
 104.724,338.244 110.066,332.651 115.409,325.471 120.751,316.951 126.093,307.3

In [30]:
using Interact

@manipulate for m = 3:10
    x = collect(linspace(-2, 2, m))
    f(x) = sin(pi*x)
    y = f(x)
    scatter(x, y)
    plot!(f, x[1], x[end], c=:blue)
    plot!(t->Lag(t, x, y), x[1], x[end], c=:red)
end

Interact.Slider{Int64}(Signal{Int64}(6, nactions=0),"m",6,3:10,true)

Um fator importante da teoria, todos os polinômios obtidos do mesmo grau passando no mesmo ponto são iguais.
Isso quer dizer que não importa o método de obtenção, desde que ele interpole aqueles pontos e tenha o mesmo grau.

O polinômio de Lagrange é bastante útil na teoria, pois dá uma maneira simples e bonita de usar os polinômios.
Uma maneira de pensar nessa interpolação é que a base de interpolação é $\{\ell_1, \dots, \ell_m\}$, e nessa
base montamos a matriz do sistema linear.

## Polinômio de Newton - Diferenças Divididas

Apesar de ser útil na teoria, o polinômio de Lagrange não é muito fácil de calcular ou eficiente em memória.
Para isso, existe outra maneira de expressar os polinômios: a forma de Newton.

Dado os pontos $(x_i,y_i), i = 1,\dots,m$, existem $a_1,\dots,a_m$ tais que
$$P(x) = a_1 + a_2(x-x_1) + a_3(x-x_1)(x - x_2) + \dots + a_m(x-x_1)(x-x_2)\dots(x-x_{m-1})$$
interpola esses pontos, i.e., $P(x_i) = y_i$.

Uma característica interessante dessa forma é que, ao escrever as condições $P(x_i) = y_i$, o sistema linear para encontrar $a_i$ se mostra trivial, pois todos os termos $a_j$ com $j < i$ podem ser determinados antes dessa equação, e todos os termos $a_j$ com $j > i$ não irão aparecer no sistema.

$$y_1 = P(x_1) = a_1 \qquad \Rightarrow \qquad
a_1 = y_1. $$
$$y_2 = P(x_2) = a_1 + a_2(x_2-x_1) = y_1 + a_2(x_2-x_1) \qquad
\Rightarrow \qquad
a_2 = \frac{y_2 - y_1}{x_2 - x_1}. $$
$$y_3 = P(x_3) = a_1 + a_2(x_3-x_1) + a_3(x_3-x_1)(x_3-x_2) = \\
y_1 + \frac{y_2-y_1}{x_2-x_1}(x_3-x_1) + a_3(x_3-x_1)(x_3-x_2).
$$

E essa seria uma maneira de resolver o sistema.
Na prática, no entanto, existe uma maneira ainda mais fácil.

**Def.:** A diferença dividida de ordem 0 em $x_i$ é dada por
$$ f[x_i] = y_i. $$

**Def.:** A diferença dividida de ordem $k$ em $x_i, x_{i+1}, \dots, x_{i+k}$ é dada por
$$ f[x_i,x_{i+1},\dots,x_{i+k}] = \frac{ f[x_{i+1},\dots,x_{i+k}] - f[x_i,\dots,x_{i+k-1}]}{x_{i+k} - x_i}. $$

É trivial ver que a diferença de ordem 1 é a inclinação da reta que passa em $(x_i,y_i)$ e $(x_{i+1},y_{i+1})$. Veja que
$$ a_1 = f[x_1], $$
e
$$ a_2 = f[x_1,x_2]. $$
Com um certo trabalho algébrico, é possível mostrar que
$$ a_k = f[x_1,x_2,\dots,x_k]. $$

Note que precisamos calcular uma "árvore" de diferenças divididas.
Uma maneira de fazer isso é usar um tipo de tabela.

x_k | Ordem 0 | Ordem 1    | Ordem 2
----|---------|------------|
x_1 |   y_1   |
    |         | f[x_1,x_2]
x_2 |   y_2   |            | f[x_1,x_2,x_3]
    |         | f[x_2,x_3]
x_3 |   y_3   |

Obs.: Fazer no quadro, porque aqui fica difícil.

Para armazenar esses valores, vamos usar uma matriz (metade de uma matriz na verdade).

$$ D = \left[\begin{array}{cccc}
y_1 & f[x_1,x_2] & f[x_1,x_2,x_3] & f[x_1,x_2,x_3,x_4] \\
y_2 & f[x_2,x_3] & f[x_2,x_3,x_4] \\
y_3 & f[x_3,x_4] \\
y_4
\end{array}\right]
$$

Fica fácil ver que
$$ D_{i,j} = \frac{D_{i+1,j-1} - D_{i,j-1}}{x_{i+j-1} - x_i} $$

In [49]:
function DifDiv(x, y)
end

DifDiv (generic function with 1 method)

In [50]:
x = collect(linspace(0, 2, 3))
y = exp(x)
a = DifDiv(x, y)
P(t) = a[1] + a[2]*(t-x[1]) + a[3]*(t-x[1])*(t-x[2])
scatter(x, y)
plot!(P, x[1], x[end], c=:red)

LoadError: LoadError: MethodError: `getindex` has no method matching getindex(::Void, ::Int64)
while loading In[50], in expression starting on line 6