# Introdução à Linguagem Julia

Julia é uma linguagem dinâmica de alto nível e alto desempenho.
Ela se assemelha ao MatLab e ao Python na facilidade de escrita
de código, mas sua velocidade pode ser comparável ao C e Fortran.

# Jupyter

O Jupyter é uma interface web para Julia, Python, e muitas outras.
Ela **não** é o Julia, isto é, o Julia não depende do Jupyter para
funcionar. No entanto, usando o Jupyter, aulas e apresentações
ficam mais práticas.

Cada *célula* do Jupyter pode ser executada com um `ctrl+enter`, ou
um `ctrl+shift`, sendo que o último move a seleção para a célula de
baixo.
Você pode adicionar novas células usando o `+` no topo da página.

# O REPL - Terminal Interativo

Ao abrir o Julia no Windows, ou digitar `julia` no terminal do Mac
ou Linux, se abrirá um prompt tipo

````julia
julia>
````

O Jupyter também serve como esse prompt e todo comando digitado aqui
pode ser digitado lá.

# Básico

In [3]:
2 + 300

302

In [5]:
3 * 5

15

In [6]:
7 ^ 3

343

In [8]:
exp(1)

2.718281828459045

In [9]:
sin(3.14159/4)

0.7071063120935576

In [11]:
pi

π = 3.1415926535897...

In [12]:
( sin(pi/4)*2 )^2

1.9999999999999996

In [14]:
round(pi, 2)

3.14

In [15]:
sqrt(2)

1.4142135623730951

In [16]:
abs(-3)

3

In [23]:
x = 3

3

In [24]:
x

3

In [25]:
x ^ 2

9

In [26]:
y = 2x

6

In [27]:
y - x

3

In [28]:
(x,y)

(3,6)

In [32]:
1.23e-1 # 10⁻²

0.123

In [33]:
1e3 # 10³

1000.0

In [34]:
0.1 + 0.2 - 0.3

5.551115123125783e-17

In [18]:
5/2

2.5

## Exercício

- Calcule $\varphi = \dfrac{\sqrt{5} + 1}{2}$.

In [35]:
(sqrt(5)+1)/2

1.618033988749895

In [36]:
z = sqrt(5) + 1
z/2

1.618033988749895

# Álgebra Linear Numérica

In [39]:
rand(3)

3-element Array{Float64,1}:
 0.813871
 0.236933
 0.606327

In [40]:
ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [41]:
zeros(3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [44]:
rand(2,4)

2×4 Array{Float64,2}:
 0.43464   0.343554  0.931485  0.250893
 0.901974  0.934661  0.362614  0.395355

In [45]:
v = rand(3)

3-element Array{Float64,1}:
 0.609575
 0.844965
 0.670946

In [46]:
w = rand(3)

3-element Array{Float64,1}:
 0.646051
 0.559173
 0.53122 

In [48]:
u = [2.0; 3.0; -1.0]

3-element Array{Float64,1}:
  2.0
  3.0
 -1.0

In [57]:
A = [1.0  2.0  3.0;  -1.0  -1.0  -2.0]

2×3 Array{Float64,2}:
  1.0   2.0   3.0
 -1.0  -1.0  -2.0

In [59]:
A*u

2-element Array{Float64,1}:
  5.0
 -3.0

In [49]:
v + w

3-element Array{Float64,1}:
 1.25563
 1.40414
 1.20217

In [50]:
3*v

3-element Array{Float64,1}:
 1.82872
 2.53489
 2.01284

In [51]:
2*v + 3*w

3-element Array{Float64,1}:
 3.1573 
 3.36745
 2.93555

In [52]:
A = rand(2, 3)

2×3 Array{Float64,2}:
 0.814949  0.173387  0.207212
 0.917818  0.893238  0.286909

In [53]:
A * v

2-element Array{Float64,1}:
 0.782306
 1.50673 

In [55]:
w = rand(2)

2-element Array{Float64,1}:
 0.325318
 0.888372

In [54]:
A'

3×2 Array{Float64,2}:
 0.814949  0.917818
 0.173387  0.893238
 0.207212  0.286909

In [56]:
A' * w

3-element Array{Float64,1}:
 1.08048 
 0.849934
 0.322292

In [60]:
B = rand(2, 3)

2×3 Array{Float64,2}:
 0.281167  0.283782  0.695558
 0.433422  0.442924  0.284436

In [61]:
A + B

2×3 Array{Float64,2}:
  1.28117    2.28378    3.69556
 -0.566578  -0.557076  -1.71556

In [62]:
A * B'

2×2 Array{Float64,2}:
  2.93541   2.17258
 -1.95607  -1.44522

In [63]:
A' * B

3×3 Array{Float64,2}:
 -0.152255   -0.159142   0.411122
  0.128912    0.124639   1.10668 
 -0.0233429  -0.0345029  1.5178  

$$ Ax = b $$

In [64]:
A = rand(3, 3)
b = rand(3)
x = A\b # Resolve o SL

3-element Array{Float64,1}:
 -2.09919
  2.33951
  0.73271

In [65]:
A * x - b # É pra ser zero (ou quase)

3-element Array{Float64,1}:
  0.0        
  2.498e-16  
 -1.11022e-16

In [66]:
norm(A*x-b) # norm = ‖ ⋅ ‖

2.7336071744532853e-16

In [67]:
v = [1.0; 2.0; 3.0]
w = [2.0; -2.0; 2.0]
dot(v, w) # v,w

4.0

In [72]:
A = [1.0/(i+j-1) for i = 1:3, j = 1:3]

3×3 Array{Float64,2}:
 1.0       0.5       0.333333
 0.5       0.333333  0.25    
 0.333333  0.25      0.2     

In [73]:
det(A)

0.00046296296296296135

In [74]:
A^2 # A * A

3×3 Array{Float64,2}:
 1.36111  0.75      0.525   
 0.75     0.423611  0.3     
 0.525    0.3       0.213611

In [75]:
A .^ 2 # Cada elemento de A ao quadrado

3×3 Array{Float64,2}:
 1.0       0.25      0.111111
 0.25      0.111111  0.0625  
 0.111111  0.0625    0.04    

In [76]:
B = rand(3, 3)

3×3 Array{Float64,2}:
 0.843456  0.972252  0.790712
 0.980318  0.73671   0.615172
 0.669554  0.743285  0.15289 

In [77]:
A .* B

3×3 Array{Float64,2}:
 0.843456  0.486126  0.263571 
 0.490159  0.24557   0.153793 
 0.223185  0.185821  0.0305779

In [78]:
A = [2  3  4; 4.1  5.2  6.0]

2×3 Array{Float64,2}:
 2.0  3.0  4.0
 4.1  5.2  6.0

In [79]:
A = [2 3 4;1 0 1]

2×3 Array{Int64,2}:
 2  3  4
 1  0  1

## Funções que "distribuem"

In [80]:
exp( [0.0; 1.0] )

2-element Array{Float64,1}:
 1.0    
 2.71828

In [82]:
v = linspace(0, 1, 11)

11-element LinSpace{Float64}:
 0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0

In [83]:
w = shuffle(v)

11-element Array{Float64,1}:
 0.3
 0.8
 0.4
 0.5
 0.1
 1.0
 0.9
 0.0
 0.2
 0.6
 0.7

In [84]:
sqrt(w)

11-element Array{Float64,1}:
 0.547723
 0.894427
 0.632456
 0.707107
 0.316228
 1.0     
 0.948683
 0.0     
 0.447214
 0.774597
 0.83666 

In [49]:
sqrt(shuffle(linspace(0, 1, 10)))

10-element Array{Float64,1}:
 0.471405
 1.0     
 0.816497
 0.333333
 0.942809
 0.745356
 0.57735 
 0.881917
 0.666667
 0.0     

## Exercício

- Crie um vetor com os ângulos importantes: 0, pi/6, pi/4, pi/3 e pi/2.
- Crie um vetor com o seno de cada ângulo e outro com o cosseno, usando o vetor acima.
- Calcule a tangente de cada angulo usando os dois vetores acima (tan = sen/cos), mas **sem usar a função tan**.

In [85]:
x = [0.0; pi/6; pi/4; pi/3; pi/2]

5-element Array{Float64,1}:
 0.0     
 0.523599
 0.785398
 1.0472  
 1.5708  

In [87]:
S = sin(x)

5-element Array{Float64,1}:
 0.0     
 0.5     
 0.707107
 0.866025
 1.0     

In [88]:
C = cos(x)

5-element Array{Float64,1}:
 1.0        
 0.866025   
 0.707107   
 0.5        
 6.12323e-17

In [90]:
S ./ C

5-element Array{Float64,1}:
 0.0       
 0.57735   
 1.0       
 1.73205   
 1.63312e16

## Acesso aos elementos

In [91]:
v = rand(5)

5-element Array{Float64,1}:
 0.96983  
 0.0987713
 0.421499 
 0.578561 
 0.925988 

In [92]:
v[1]

0.9698300719774426

In [93]:
v[2]

0.09877126437237238

In [94]:
v[end]

0.925988342498639

In [95]:
A

2×3 Array{Int64,2}:
 2  3  4
 1  0  1

In [96]:
A[1,1]

2

In [97]:
A[2,3]

1

In [98]:
v[2:4]

3-element Array{Float64,1}:
 0.0987713
 0.421499 
 0.578561 

In [100]:
collect(2.0 : 0.1: 3.0)

11-element Array{Float64,1}:
 2.0
 2.1
 2.2
 2.3
 2.4
 2.5
 2.6
 2.7
 2.8
 2.9
 3.0

In [102]:
0 : pi/4 : 2pi

0.0:0.7853981633974483:6.283185307179586

In [103]:
A

2×3 Array{Int64,2}:
 2  3  4
 1  0  1

In [104]:
A[:,2]

2-element Array{Int64,1}:
 3
 0

In [105]:
A[1,:]

3-element Array{Int64,1}:
 2
 3
 4

In [108]:
A = rand(2,3)

2×3 Array{Float64,2}:
 0.0356084  0.527433  0.7438  
 0.498461   0.865589  0.884801

In [109]:
A[2,3] = 0.0

0.0

In [110]:
A

2×3 Array{Float64,2}:
 0.0356084  0.527433  0.7438
 0.498461   0.865589  0.0   

In [114]:
eye(4)

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [115]:
size(A)

(2,3)

In [117]:
m, n = size(A)

(2,3)

In [118]:
(m, n) = size(A)

(2,3)

In [119]:
m

2

In [120]:
length(v)

5

## Exercício

- Crie um vetor aleatório e mude o primeiro elemento para o seu oposto (i.e. mude o sinal)

In [121]:
v = rand(3)

3-element Array{Float64,1}:
 0.795822
 0.499114
 0.421126

In [122]:
v[1] = -v[1]

-0.7958224920315167

In [123]:
v

3-element Array{Float64,1}:
 -0.795822
  0.499114
  0.421126

## Matriz por blocos - concatenação

In [124]:
[rand(3,3) zeros(3,2); ones(2,3) eye(2,2)]

5×5 Array{Float64,2}:
 0.896208  0.780958    0.348082  0.0  0.0
 0.151002  0.00465716  0.065718  0.0  0.0
 0.331548  0.580115    0.328334  0.0  0.0
 1.0       1.0         1.0       1.0  0.0
 1.0       1.0         1.0       0.0  1.0

# Funções

3 tipos
- curta
- anônima
- longa

In [134]:
min(2, 3, 5)

2

In [125]:
exp(1) - sin(1) + abs(5)

6.876810843651149

In [137]:
gcd(12, 8) # MDC

4

In [131]:
f(x) = sqrt(x^2 + 1e-2)
f(2)

2.0024984394500787

In [127]:
f(-3)

9

In [128]:
f(sqrt(2))

2.0000000000000004

In [138]:
g(a,b) = exp(a + b)

g (generic function with 1 method)

In [139]:
g(2,3)

148.4131591025766

In [141]:
g(3,-3)

1.0

In [142]:
h = x -> sin(x)

(::#3) (generic function with 1 method)

In [143]:
bar(foo, a) = foo(a) * 2 + 1    ## bar(f,a) = 2f(a) + 1

bar (generic function with 1 method)

In [146]:
bar(f, 2) # f definida lá em cima

5.004996878900157

In [150]:
bar(x->sin(pi * x), 5)

1.0000000000000013

In [149]:
bar(h, 5)

-0.9178485493262769

In [151]:
function soma_dois_numeros(a, b)
    return a + b
end

soma_dois_numeros (generic function with 1 method)

In [153]:
soma_dois_numeros(3, -1)

2

In [154]:
function aproxima_integral(f, a, b)
    h = (b-a)/2
    S = f(a) + f( (a+b)/2 )
    return h * S
end

aproxima_integral (generic function with 1 method)

In [156]:
aproxima_integral(x->x^3, 0, 1)

0.0625

# Exercícios

- Crie uma função que recebe $a$ e calcula $2\bigg(a + \dfrac{1}{a}\bigg)$.
- Crie uma função que recebe dois catetos e calcula a hipotenusa.
- Crie uma função que recebe uma matriz A e um vetor v e retorna
$\dfrac{\langle v, Av\rangle}{\langle v, v\rangle}$

In [157]:
f(a) = 2*(a + 1/a)

f (generic function with 1 method)

In [158]:
f(2)

5.0

In [159]:
function hipotenusa(cat1, cat2)
    return sqrt(cat1^2 + cat2^2)
end

hipotenusa (generic function with 1 method)

In [160]:
hipotenusa(3, 4)

5.0

In [161]:
function rayleigh(A, v)
    return dot(A*v, v)/dot(v, v)
end

rayleigh (generic function with 1 method)

In [162]:
A = [1.0   0.0;   0.0   4.0]

2×2 Array{Float64,2}:
 1.0  0.0
 0.0  4.0

In [197]:
rayleigh(A, rand(2))

2.8161296517684398

# Loops e condicionais

In [3]:
for i = linspace(0, 1, 11)
    println(i^2)
end

0.0
0.010000000000000002
0.04000000000000001
0.09
0.16000000000000003
0.25
0.36
0.48999999999999994
0.6400000000000001
0.81
1.0


In [4]:
for i = 1:10
    
    ## Vê se ele é primo (como ??)
    
    println("$i é primo")
end

1 é primo
2 é primo
3 é primo
4 é primo
5 é primo
6 é primo
7 é primo
8 é primo
9 é primo
10 é primo


In [5]:
A = zeros(10, 10)

for i = 1:10 # linhas
    for j = 1:10 # colunas
        A[i,j] = 1.0/(i + j - 1)
    end
end

A

10×10 Array{Float64,2}:
 1.0       0.5        0.333333   …  0.125      0.111111   0.1      
 0.5       0.333333   0.25          0.111111   0.1        0.0909091
 0.333333  0.25       0.2           0.1        0.0909091  0.0833333
 0.25      0.2        0.166667      0.0909091  0.0833333  0.0769231
 0.2       0.166667   0.142857      0.0833333  0.0769231  0.0714286
 0.166667  0.142857   0.125      …  0.0769231  0.0714286  0.0666667
 0.142857  0.125      0.111111      0.0714286  0.0666667  0.0625   
 0.125     0.111111   0.1           0.0666667  0.0625     0.0588235
 0.111111  0.1        0.0909091     0.0625     0.0588235  0.0555556
 0.1       0.0909091  0.0833333     0.0588235  0.0555556  0.0526316

In [88]:
for i = 1 : 0.5 : 5
    println("i = $i")
end

i = 1.0
i = 1.5
i = 2.0
i = 2.5
i = 3.0
i = 3.5
i = 4.0
i = 4.5
i = 5.0


In [208]:
x = rand(10)
y = zeros(10)
for i = 1:10
    y[i] = x[i] * i
end

In [209]:
x

10-element Array{Float64,1}:
 0.537613 
 0.978892 
 0.119257 
 0.984027 
 0.943599 
 0.578526 
 0.0138703
 0.30376  
 0.771505 
 0.119265 

In [210]:
y

10-element Array{Float64,1}:
 0.537613 
 1.95778  
 0.357772 
 3.93611  
 4.718    
 3.47116  
 0.0970923
 2.43008  
 6.94354  
 1.19265  

In [6]:
for x in [0; pi/6; pi/4; pi/3; pi/2]
    println("sin($x) = $(sin(x))")
end

sin(0.0) = 0.0
sin(0.5235987755982988) = 0.49999999999999994
sin(0.7853981633974483) = 0.7071067811865475
sin(1.0471975511965976) = 0.8660254037844386
sin(1.5707963267948966) = 1.0


In [8]:
for i in 1:10
    println("$i^2 = $(i^2)")
end

1^2 = 1
2^2 = 4
3^2 = 9
4^2 = 16
5^2 = 25
6^2 = 36
7^2 = 49
8^2 = 64
9^2 = 81
10^2 = 100


In [218]:
for i = 3:3:20
    print("$i ")
end

3 6 9 12 15 18 

In [10]:
n = 6
v = ones(n)
v[2] = 5
v

6-element Array{Float64,1}:
 1.0
 5.0
 1.0
 1.0
 1.0
 1.0

In [11]:
n/2

3.0

In [14]:
typeof(3.0)

Float64

In [15]:
typeof(3)

Int64

In [12]:
v[n/2] = 2
v

LoadError: LoadError: ArgumentError: invalid index: 3.0
while loading In[12], in expression starting on line 1

In [95]:
n/2

3.0

In [16]:
div(7,2) # 7/2 = 3 com resto 1

3

In [17]:
div(12, 5)

2

In [20]:
round(Int, 3.9)

4

In [219]:
10 % 4 # resto da divisão de 10 por 4

2

In [21]:
12 % 5

2

# Fatorial
$$ n! = n(n-1)\dots2. 1 $$

In [22]:
function fatorial(n)
    resultado = 1
    for i = 1:n
        resultado = resultado * i
    end
    return resultado
end

fatorial (generic function with 1 method)

In [23]:
fatorial(4)

24

In [24]:
fatorial(10)

3628800

In [25]:
fatorial(0)

1

In [27]:
fatorial(-pi)

1

In [30]:
for n = 1:12
    println("$n ! = $(fatorial(n))")
end

1 ! = 1
2 ! = 2
3 ! = 6
4 ! = 24
5 ! = 120
6 ! = 720
7 ! = 5040
8 ! = 40320
9 ! = 362880
10 ! = 3628800
11 ! = 39916800
12 ! = 479001600


## Exercícios

- Faça uma função `soma1(n)` que calcula a soma $1 + 2 + 3 + \dots + n$, usando `for`. (O valor exato é `n(n+1)/2`).
- Faça uma função `soma2(n)` que calcula a soma $1^2 + 2^2 + \dots + n^2$, usando `for`. (O valor exato é `n(n+1)(2n+1)/6`).

In [31]:
function soma1(n)
    S = 0
    for i = 1:n
        S = S + i
    end
    return S
end

soma1 (generic function with 1 method)

In [33]:
soma1(100)

5050

In [36]:
function soma2(n)
    S = 0
    for i = 1:n
        S = S + i^2
    end
    return S
end

soma2 (generic function with 1 method)

In [37]:
m = 3
soma2(m)

14

### Condicional

In [38]:
function sinal(x)
    if x > 0
        return 1
    elseif x < 0
        return -1
    else
        return 0
    end
end

sinal (generic function with 1 method)

In [40]:
sinal(3.2)

1

In [41]:
sinal(-1.2)

-1

In [42]:
sinal(0.0)

0

In [43]:
sinal(π)

1

In [53]:
π

π = 3.1415926535897...

In [44]:
function bhaskara(a, b, c) # ax² + bx + c = 0, Δ = b² - 4ac
    Δ = b^2 - 4a*c
    if Δ < 0
        error("Nos reais não tem solução")
    end
    return (-b + sqrt(Δ))/2a, (-b - sqrt(Δ))/2a
end

bhaskara (generic function with 1 method)

In [48]:
bhaskara(1, 3, 2) #x^2 + 5x + 6 = 0

(-1.0,-2.0)

In [49]:
bhaskara(1, 0, 1) # x² + 1 = 0

LoadError: LoadError: Nos reais não tem solução
while loading In[49], in expression starting on line 1

In [50]:
bhaskara(1, 0, -1) # x² - 1 = 0

(1.0,-1.0)

## Exercícios

- Faça uma função `primo(n)` que retorna se o número `n` é primo ou não. Lembrando que `n % p` é o resto da divisão de `n` por `p`. Teste com a função abaixo.

In [55]:
println(2)
println(3)
println(5)
println(1)
println(10)

2
3
5
1
10


In [56]:
10 % 3

1

In [57]:
10 % 4

2

In [58]:
10 % 5

0

In [59]:
13 % 2

1

In [60]:
13 % 3

1

In [61]:
13 % 4

1

In [62]:
13 % 5

3

In [63]:
13 % 6

1

In [64]:
x = 2

2

In [65]:
2 == 2

true

In [67]:
x == 2

true

In [68]:
x == 3

false

In [69]:
x = 3

3

In [70]:
2 == 3

false

In [71]:
2 = 3

LoadError: LoadError: syntax: invalid assignment location "2"
while loading In[71], in expression starting on line 1

In [72]:
function primo(n)
    for i = 2:n-1
        if n % i == 0
            return false
        end
    end
    return true
end

primo (generic function with 1 method)

In [80]:
primo(269)

true

In [78]:
for i = 2:15
    if primo(i)
        println("$i é primo")
    else
        println("$i não é primo")
    end
end

2 é primo
3 é primo
4 não é primo
5 é primo
6 não é primo
7 é primo
8 não é primo
9 não é primo
10 não é primo
11 é primo
12 não é primo
13 é primo
14 não é primo
15 não é primo


### Loop while

In [83]:
i = 5
n = 10
while i <= n
    println("i = $i")
    i += 1 # += quer dizer = . + => i += 1 quer dizer i = i + 1
end

i = 5
i = 6
i = 7
i = 8
i = 9
i = 10


In [84]:
function zero_de_funcao(f, a, b)
    if f(a) * f(b) > 0
        error("f pode não ter raíz em [$a,$b]")
    end
    x = (a+b)/2
    while abs(f(x)) > 1e-8
        if f(x) * f(a) < 0
            b = x
        else
            a = x
        end
        x = (a+b)/2
    end
    return x, f(x)
end

zero_de_funcao (generic function with 1 method)

In [86]:
x, fx = zero_de_funcao(x->cos(x), 0, 3)

(1.570796325802803,9.920935796805404e-10)

In [88]:
g(x) = exp(-x) - x
x, fx = zero_de_funcao(g, 0, 1)

(0.5671432912349701,-1.2931850035258208e-9)

In [87]:
pi/2

1.5707963267948966

In [116]:
x, fx = zero_de_funcao(x->6x^2 - x - 1/3, -1, 0)

(-0.1666666641831398,-7.450580541412677e-9)

In [117]:
x, fx = zero_de_funcao(x->6x^2 - x - 1/3, -1, 1)

LoadError: LoadError: f pode não ter raíz em [-1,1]
while loading In[117], in expression starting on line 1

## Exercícios

- Faça uma função `collatz(n)` que calcula uma sequência
$$ a_{n+1} = \left\{\begin{array}{ll}
a_n/2, & \mbox{se $a_n$ é par} \\
3a_n + 1, & \mbox{se $a_n$ é ímpar}.
\end{array}\right.$$
começando de $a_0 = n$, e parando quando $a_n = 1$.
Imprima cada elemento da sequência.

In [111]:
function collatz(n)
    # n == 1 => PARE
    println("n = $n")
    contador = 0
    while n > 1
        if n % 2 == 0
            n = div(n, 2)
        else
            n = 3n + 1
        end
        contador += 1
        println("n = $n")
    end
    println("$contador numeros na sequencia")
end

collatz (generic function with 1 method)

In [112]:
collatz(BigInt(2)^6-1)

n = 63
n = 190
n = 95
n = 286
n = 143
n = 430
n = 215
n = 646
n = 323
n = 970
n = 485
n = 1456
n = 728
n = 364
n = 182
n = 91
n = 274
n = 137
n = 412
n = 206
n = 103
n = 310
n = 155
n = 466
n = 233
n = 700
n = 350
n = 175
n = 526
n = 263
n = 790
n = 395
n = 1186
n = 593
n = 1780
n = 890
n = 445
n = 1336
n = 668
n = 334
n = 167
n = 502
n = 251
n = 754
n = 377
n = 1132
n = 566
n = 283
n = 850
n = 425
n = 1276
n = 638
n = 319
n = 958
n = 479
n = 1438
n = 719
n = 2158
n = 1079
n = 3238
n = 1619
n = 4858
n = 2429
n = 7288
n = 3644
n = 1822
n = 911
n = 2734
n = 1367
n = 4102
n = 2051
n = 6154
n = 3077
n = 9232
n = 4616
n = 2308
n = 1154
n = 577
n = 1732
n = 866
n = 433
n = 1300
n = 650
n = 325
n = 976
n = 488
n = 244
n = 122
n = 61
n = 184
n = 92
n = 46
n = 23
n = 70
n = 35
n = 106
n = 53
n = 160
n = 80
n = 40
n = 20
n = 10
n = 5
n = 16
n = 8
n = 4
n = 2
n = 1
107 numeros na sequencia


In [91]:
m = 2^63-1

9223372036854775807

In [97]:
fatorial(23)

8128291617894825984

In [103]:
primo(BigInt(2)^130 - 1)

false

## Operadores lógicos

In [113]:
true

true

In [114]:
true || false # || -> ou

true

In [115]:
true && false # && -> e

false

In [117]:
false || false

false

In [122]:
if 1 > 0 && "a" in ["a", "b"]
    println("Ok")
end

Ok


In [124]:
!true # ! -> não

false

In [125]:
!false

true

In [126]:
function fib(n)
    if (n == 1 || n == 2)
        return 1
    else
        return fib(n-1) + fib(n-2)
    end
end

fib (generic function with 1 method)

In [127]:
fib(1)

1

In [128]:
fib(2)

1

In [129]:
fib(3)

2

In [130]:
fib(5)

5

In [134]:
fib(10)

55

In [130]:
!true

false

## !(a && b) = !a || !b

In [136]:
x = 0
n = 0

while !(x > 5 || n == 10)
    x = x + rand()
    n = n + 1
end
println("Fim, x = $x, n = $n")

Fim, x = 5.018892008698307, n = 9


In [137]:
n = 0
x = 0

while x <= 5 && n < 10
    x = x + rand()
    n = n + 1
end
println("Fim, x = $x, n = $n")

Fim, x = 5.787914730692325, n = 10


## Plots

In [2]:
using Plots
gr()

Plots.GRBackend()

In [146]:
plot([1; 2; 3; 1], [3; 1; 2; 3])

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 1.0 
 
 
 1.5 
 
 
 2.0 
 
 
 2.5 
 
 
 3.0 
 
 
 1.0 
 
 
 1.5 
 
 
 2.0 
 
 
 2.5 
 
 
 3.0 
 
 
 
 
 
 
 y1

In [145]:
x = linspace(-1, 2, 100) # 100 pontos igual. esp. em [-1,2]
y = x.^3 - x.^2
plot(x, y)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -1.0 
 
 
 -0.5 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 1.5 
 
 
 2.0 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 3 
 
 
 4 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,384.952 27.5163,375.562 33.3178,366.628 39.1193,358.139 44.9208,350.084 50.7223,342.454 56.5238,335.238 62.3253,328.424 68.1268,322.002 73.9283,315.963 
 79.7298,310.294 85.5313,304.986 91.3328,300.027 97.1342,295.408 102.936,291.118 108.737,287.146 114.539,283.481 120.34,280.113 126.142,277.031 131.943,274.225 
 137.745,271.684 143.546,269.397 149.348,267.355 155.149,265.545 160.951,263.958 166.752,262.584 172.554,261.41 178.355,260.428 184.157,259.626 189.958,258.993 
 195.76,258.519 201.561,258.194 207.363,258.007 213.164,257.947 218.966,258.003 224.767,258.166 230.569,258.424 236.37,258.767 242.172,259.184 247.973,259.664 
 253.775,260.198 259.576,260.774 265.378,261.382 271.179,262.011 276.981,262.651 282.782,263.29 288.584,263.92 294.385,264.527 300.187,265.103 305.988,265.637 
 311.79,266.118 317.591,266.535 323.393,266.878 329.194,267.136 334.996,267.298 340.797,267.355 346.599,267.295 352.4,267.107 358.202,266.782 364.003,266.309 
 369.805,265.676 375.606,264.874 381.408,263.891 387.209,262.718 393.011,261.343 398.812,259.756 404.614,257.947 410.415,255.904 416.217,253.618 422.018,251.077 
 427.82,248.271 433.621,245.189 439.423,241.821 445.224,238.156 451.026,234.184 456.827,229.893 462.629,225.274 468.43,220.316 474.232,215.008 480.033,209.339 
 485.835,203.299 491.636,196.878 497.438,190.064 503.239,182.847 509.041,175.217 514.842,167.163 520.644,158.674 526.445,149.74 532.247,140.35 538.048,130.493 
 543.85,120.159 549.651,109.338 555.453,98.0183 561.254,86.1897 567.056,73.8415 572.857,60.9632 578.659,47.5443 584.46,33.574 590.261,19.0418 596.063,3.93701 
 
 "/>
 
 
 
 
 y1

In [151]:
plot(x, y, m=3)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 0.0 
 
 
 2.5 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 46.6072,374.168 51.9956,365.31 57.3841,356.881 62.7725,348.873 68.1609,341.275 73.5493,334.076 78.9377,327.268 84.3261,320.84 89.7145,314.782 95.1029,309.084 
 100.491,303.736 105.88,298.729 111.268,294.051 116.657,289.693 122.045,285.646 127.433,281.898 132.822,278.441 138.21,275.264 143.599,272.356 148.987,269.709 
 154.375,267.312 159.764,265.155 165.152,263.228 170.541,261.521 175.929,260.024 181.317,258.727 186.706,257.62 192.094,256.693 197.483,255.936 202.871,255.339 
 208.259,254.893 213.648,254.586 219.036,254.409 224.425,254.352 229.813,254.406 235.201,254.559 240.59,254.803 245.978,255.126 251.367,255.519 256.755,255.973 
 262.143,256.476 267.532,257.02 272.92,257.593 278.309,258.187 283.697,258.79 289.086,259.394 294.474,259.987 299.862,260.56 305.251,261.104 310.639,261.607 
 316.028,262.061 321.416,262.454 326.804,262.778 332.193,263.021 337.581,263.174 342.97,263.228 348.358,263.171 353.746,262.994 359.135,262.688 364.523,262.241 
 369.912,261.644 375.3,260.887 380.688,259.96 386.077,258.853 391.465,257.556 396.854,256.059 402.242,254.352 407.63,252.425 413.019,250.268 418.407,247.871 
 423.796,245.224 429.184,242.316 434.572,239.139 439.961,235.682 445.349,231.934 450.738,227.887 456.126,223.529 461.514,218.851 466.903,213.844 472.291,208.496 
 477.68,202.798 483.068,196.74 488.457,190.312 493.845,183.504 499.233,176.306 504.622,168.707 510.01,160.699 515.399,152.27 520.787,143.412 526.175,134.113 
 531.564,124.364 536.952,114.155 542.341,103.476 547.729,92.3173 553.117,80.6681 558.506,68.5188 563.894,55.8594 569.283,42.6798 574.671,28.9702 580.059,14.7204 
 
 "/>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1

In [152]:
scatter(x, y, color=:red)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 0.0 
 
 
 2.5 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1

In [153]:
scatter(x, rand(100))

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1

In [154]:
#f(x) = sin(x) + cos(x)
plot(x->sin(4x) + cos(x)*x, 0, 4pi) # plot(fun, a, b)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 5 
 
 
 10 
 
 
 -5 
 
 
 0 
 
 
 5 
 
 
 10 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,218.558 27.5163,208.104 33.3178,199.849 39.1193,195.46 44.9208,195.677 50.7223,200.144 56.5238,207.52 62.3253,215.836 68.1268,223.005 73.9283,227.358 
 79.7298,228.075 85.5313,225.395 91.3328,220.552 97.1342,215.462 102.936,212.228 108.737,212.596 114.539,217.499 120.34,226.8 126.142,239.3 131.943,253.018 
 137.745,265.658 143.546,275.162 149.348,280.195 155.149,280.45 160.951,276.699 166.752,270.566 172.554,264.089 178.355,259.184 184.157,257.141 189.958,258.279 
 195.76,261.854 201.561,266.242 207.363,269.343 213.164,269.119 218.966,264.111 224.767,253.831 230.569,238.898 236.37,220.914 242.172,202.086 247.973,184.713 
 253.775,170.636 259.576,160.828 265.378,155.185 271.179,152.609 276.981,151.328 282.782,149.397 288.584,145.232 294.385,138.063 300.187,128.166 305.988,116.835 
 311.79,106.092 317.591,98.2077 323.393,95.1474 329.194,98.0964 334.996,107.168 340.797,121.378 346.599,138.884 352.4,157.438 358.202,174.928 364.003,189.884 
 369.805,201.804 375.606,211.241 381.408,219.607 387.209,228.761 393.011,240.475 398.812,255.922 404.614,275.307 410.415,297.749 416.217,321.425 422.018,343.965 
 427.82,362.978 433.621,376.59 439.423,383.859 445.224,384.952 451.026,381.063 456.827,374.065 462.629,366.013 468.43,358.599 474.232,352.716 480.033,348.235 
 485.835,344.047 491.636,338.362 497.438,329.198 503.239,314.922 509.041,294.715 514.842,268.844 520.644,238.662 526.445,206.351 532.247,174.452 538.048,145.315 
 543.85,120.601 549.651,100.957 555.453,85.9494 561.254,74.2667 567.056,64.1435 572.857,53.8918 578.659,42.4082 584.46,29.5251 590.261,16.1179 596.063,3.93701 
 
 "/>
 
 
 
 
 y1

In [155]:
plot(x->exp(x), -1, 1)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -1.0 
 
 
 -0.5 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 1 
 
 
 2 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 12.8259,384.952 18.7172,383.735 24.6085,382.493 30.4997,381.226 36.391,379.933 42.2823,378.613 48.1736,377.267 54.0649,375.893 59.9562,374.491 65.8475,373.061 
 71.7387,371.601 77.63,370.112 83.5213,368.592 89.4126,367.041 95.3039,365.458 101.195,363.844 107.086,362.196 112.978,360.514 118.869,358.799 124.76,357.048 
 130.652,355.261 136.543,353.439 142.434,351.578 148.325,349.68 154.217,347.744 160.108,345.767 165.999,343.751 171.891,341.693 177.782,339.593 183.673,337.45 
 189.564,335.264 195.456,333.033 201.347,330.756 207.238,328.433 213.13,326.063 219.021,323.644 224.912,321.176 230.803,318.657 236.695,316.087 242.586,313.465 
 248.477,310.789 254.369,308.059 260.26,305.273 266.151,302.429 272.042,299.528 277.934,296.568 283.825,293.547 289.716,290.465 295.608,287.32 301.499,284.11 
 307.39,280.835 313.281,277.494 319.173,274.084 325.064,270.604 330.955,267.054 336.847,263.431 342.738,259.734 348.629,255.961 354.52,252.112 360.412,248.184 
 366.303,244.176 372.194,240.086 378.085,235.913 383.977,231.654 389.868,227.309 395.759,222.875 401.651,218.35 407.542,213.733 413.433,209.022 419.324,204.215 
 425.216,199.309 431.107,194.304 436.998,189.196 442.89,183.984 448.781,178.666 454.672,173.239 460.563,167.702 466.455,162.051 472.346,156.285 478.237,150.402 
 484.129,144.398 490.02,138.272 495.911,132.021 501.802,125.642 507.694,119.133 513.585,112.492 519.476,105.714 525.368,98.7988 531.259,91.7422 537.15,84.5415 
 543.041,77.1939 548.933,69.6963 554.824,62.0457 560.715,54.239 566.607,46.273 572.498,38.1444 578.389,29.8499 584.28,21.3862 590.172,12.7497 596.063,3.93701 
 
 "/>
 
 
 
 
 y1

In [156]:
plot!(x->exp(-x)*3, -1, 1)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -1.0 
 
 
 -0.5 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 2.5 
 
 
 5.0 
 
 
 7.5 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 30.6037,384.952 36.3154,384.585 42.0271,384.21 47.7388,383.827 53.4505,383.437 59.1622,383.039 64.8739,382.632 70.5856,382.218 76.2974,381.794 82.0091,381.363 
 87.7208,380.922 93.4325,380.473 99.1442,380.014 104.856,379.546 110.568,379.068 116.279,378.581 121.991,378.083 127.703,377.576 133.414,377.058 139.126,376.529 
 144.838,375.99 150.55,375.44 156.261,374.879 161.973,374.306 167.685,373.721 173.396,373.124 179.108,372.516 184.82,371.895 190.532,371.261 196.243,370.614 
 201.955,369.954 207.667,369.281 213.378,368.594 219.09,367.892 224.802,367.177 230.514,366.447 236.225,365.702 241.937,364.942 247.649,364.166 253.36,363.374 
 259.072,362.567 264.784,361.743 270.496,360.902 276.207,360.043 281.919,359.168 287.631,358.274 293.342,357.363 299.054,356.432 304.766,355.483 310.477,354.514 
 316.189,353.526 321.901,352.517 327.613,351.488 333.324,350.437 339.036,349.366 344.748,348.272 350.459,347.156 356.171,346.018 361.883,344.856 367.595,343.67 
 373.306,342.46 379.018,341.226 384.73,339.966 390.441,338.681 396.153,337.369 401.865,336.031 407.577,334.665 413.288,333.272 419,331.85 424.712,330.398 
 430.423,328.918 436.135,327.407 441.847,325.865 447.559,324.292 453.27,322.687 458.982,321.049 464.694,319.377 470.405,317.672 476.117,315.932 481.829,314.156 
 487.54,312.344 493.252,310.495 498.964,308.608 504.676,306.682 510.387,304.718 516.099,302.713 521.811,300.667 527.522,298.58 533.234,296.45 538.946,294.277 
 544.658,292.059 550.369,289.796 556.081,287.487 561.793,285.13 567.504,282.726 573.216,280.272 578.928,277.769 584.64,275.214 590.351,272.607 596.063,269.947 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#e9746a; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 30.6037,3.93701 36.3154,11.917 42.0271,19.7375 47.7388,27.4015 53.4505,34.9123 59.1622,42.2728 64.8739,49.4862 70.5856,56.5553 76.2974,63.483 82.0091,70.2721 
 87.7208,76.9255 93.4325,83.4458 99.1442,89.8357 104.856,96.0978 110.568,102.235 116.279,108.249 121.991,114.143 127.703,119.919 133.414,125.579 139.126,131.126 
 144.838,136.563 150.55,141.89 156.261,147.111 161.973,152.228 167.685,157.242 173.396,162.156 179.108,166.972 184.82,171.692 190.532,176.317 196.243,180.849 
 201.955,185.291 207.667,189.644 213.378,193.91 219.09,198.091 224.802,202.188 230.514,206.203 236.225,210.138 241.937,213.994 247.649,217.773 253.36,221.477 
 259.072,225.106 264.784,228.663 270.496,232.149 276.207,235.564 281.919,238.912 287.631,242.193 293.342,245.408 299.054,248.559 304.766,251.646 310.477,254.672 
 316.189,257.638 321.901,260.544 327.613,263.392 333.324,266.183 339.036,268.919 344.748,271.599 350.459,274.226 356.171,276.801 361.883,279.324 367.595,281.796 
 373.306,284.219 379.018,286.594 384.73,288.921 390.441,291.201 396.153,293.436 401.865,295.626 407.577,297.773 413.288,299.876 419,301.938 424.712,303.958 
 430.423,305.938 436.135,307.878 441.847,309.78 447.559,311.643 453.27,313.469 458.982,315.259 464.694,317.012 470.405,318.731 476.117,320.416 481.829,322.066 
 487.54,323.684 493.252,325.269 498.964,326.823 504.676,328.345 510.387,329.837 516.099,331.3 521.811,332.733 527.522,334.137 533.234,335.513 538.946,336.862 
 544.658,338.184 550.369,339.479 556.081,340.749 561.793,341.993 567.504,343.212 573.216,344.406 578.928,345.577 584.64,346.725 590.351,347.849 596.063,348.951 
 
 "/>
 
 
 
 
 y1 
 
 
 
 y2

In [159]:
plot(x->exp(x), -1, 1)
for i = 1:10
    plot!(x->exp(-x/i), -1, 1)
end
plot!()

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -1.0 
 
 
 -0.5 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 1 
 
 
 2 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 12.8259,384.952 18.7172,383.735 24.6085,382.493 30.4997,381.226 36.391,379.933 42.2823,378.613 48.1736,377.267 54.0649,375.893 59.9562,374.491 65.8475,373.061 
 71.7387,371.601 77.63,370.112 83.5213,368.592 89.4126,367.041 95.3039,365.458 101.195,363.844 107.086,362.196 112.978,360.514 118.869,358.799 124.76,357.048 
 130.652,355.261 136.543,353.439 142.434,351.578 148.325,349.68 154.217,347.744 160.108,345.767 165.999,343.751 171.891,341.693 177.782,339.593 183.673,337.45 
 189.564,335.264 195.456,333.033 201.347,330.756 207.238,328.433 213.13,326.063 219.021,323.644 224.912,321.176 230.803,318.657 236.695,316.087 242.586,313.465 
 248.477,310.789 254.369,308.059 260.26,305.273 266.151,302.429 272.042,299.528 277.934,296.568 283.825,293.547 289.716,290.465 295.608,287.32 301.499,284.11 
 307.39,280.835 313.281,277.494 319.173,274.084 325.064,270.604 330.955,267.054 336.847,263.431 342.738,259.734 348.629,255.961 354.52,252.112 360.412,248.184 
 366.303,244.176 372.194,240.086 378.085,235.913 383.977,231.654 389.868,227.309 395.759,222.875 401.651,218.35 407.542,213.733 413.433,209.022 419.324,204.215 
 425.216,199.309 431.107,194.304 436.998,189.196 442.89,183.984 448.781,178.666 454.672,173.239 460.563,167.702 466.455,162.051 472.346,156.285 478.237,150.402 
 484.129,144.398 490.02,138.272 495.911,132.021 501.802,125.642 507.694,119.133 513.585,112.492 519.476,105.714 525.368,98.7988 531.259,91.7422 537.15,84.5415 
 543.041,77.1939 548.933,69.6963 554.824,62.0457 560.715,54.239 566.607,46.273 572.498,38.1444 578.389,29.8499 584.28,21.3862 590.172,12.7497 596.063,3.93701 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#e9746a; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 12.8259,3.93701 18.7172,12.7497 24.6085,21.3862 30.4997,29.8499 36.391,38.1444 42.2823,46.273 48.1736,54.239 54.0649,62.0457 59.9562,69.6963 65.8475,77.1939 
 71.7387,84.5415 77.63,91.7422 83.5213,98.7988 89.4126,105.714 95.3039,112.492 101.195,119.133 107.086,125.642 112.978,132.021 118.869,138.272 124.76,144.398 
 130.652,150.402 136.543,156.285 142.434,162.051 148.325,167.702 154.217,173.239 160.108,178.666 165.999,183.984 171.891,189.196 177.782,194.304 183.673,199.309 
 189.564,204.215 195.456,209.022 201.347,213.733 207.238,218.35 213.13,222.875 219.021,227.309 224.912,231.654 230.803,235.913 236.695,240.086 242.586,244.176 
 248.477,248.184 254.369,252.112 260.26,255.961 266.151,259.734 272.042,263.431 277.934,267.054 283.825,270.604 289.716,274.084 295.608,277.494 301.499,280.835 
 307.39,284.11 313.281,287.32 319.173,290.465 325.064,293.547 330.955,296.568 336.847,299.528 342.738,302.429 348.629,305.273 354.52,308.059 360.412,310.789 
 366.303,313.465 372.194,316.087 378.085,318.657 383.977,321.176 389.868,323.644 395.759,326.063 401.651,328.433 407.542,330.756 413.433,333.033 419.324,335.264 
 425.216,337.45 431.107,339.593 436.998,341.693 442.89,343.751 448.781,345.767 454.672,347.744 460.563,349.68 466.455,351.578 472.346,353.439 478.237,355.261 
 484.129,357.048 490.02,358.799 495.911,360.514 501.802,362.196 507.694,363.844 513.585,365.458 519.476,367.041 525.368,368.592 531.259,370.112 537.15,371.601 
 543.041,373.061 548.933,374.491 554.824,375.893 560.715,377.267 566.607,378.613 572.498,379.933 578.389,381.226 584.28,382.493 590.172,383.735 596.063,384.952 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#3cb370; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 12.8259,177.319 18.7172,180.006 24.6085,182.665 30.4997,185.297 36.391,187.903 42.2823,190.483 48.1736,193.036 54.0649,195.565 59.9562,198.067 65.8475,200.545 
 71.7387,202.998 77.63,205.426 83.5213,207.829 89.4126,210.209 95.3039,212.564 101.195,214.896 107.086,217

In [160]:
xlims!(-0.5, 0.5)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -0.50 
 
 
 -0.25 
 
 
 0.00 
 
 
 0.25 
 
 
 0.50 
 
 
 1 
 
 
 2 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 -278.793,384.952 -267.01,383.735 -255.228,382.493 -243.445,381.226 -231.662,379.933 -219.88,378.613 -208.097,377.267 -196.315,375.893 -184.532,374.491 -172.75,373.061 
 -160.967,371.601 -149.184,370.112 -137.402,368.592 -125.619,367.041 -113.837,365.458 -102.054,363.844 -90.2716,362.196 -78.489,360.514 -66.7064,358.799 -54.9239,357.048 
 -43.1413,355.261 -31.3587,353.439 -19.5762,351.578 -7.7936,349.68 3.98897,347.744 15.7715,345.767 27.5541,343.751 39.3367,341.693 51.1192,339.593 62.9018,337.45 
 74.6844,335.264 86.4669,333.033 98.2495,330.756 110.032,328.433 121.815,326.063 133.597,323.644 145.38,321.176 157.162,318.657 168.945,316.087 180.727,313.465 
 192.51,310.789 204.293,308.059 216.075,305.273 227.858,302.429 239.64,299.528 251.423,296.568 263.205,293.547 274.988,290.465 286.771,287.32 298.553,284.11 
 310.336,280.835 322.118,277.494 333.901,274.084 345.683,270.604 357.466,267.054 369.249,263.431 381.031,259.734 392.814,255.961 404.596,252.112 416.379,248.184 
 428.161,244.176 439.944,240.086 451.727,235.913 463.509,231.654 475.292,227.309 487.074,222.875 498.857,218.35 510.639,213.733 522.422,209.022 534.205,204.215 
 545.987,199.309 557.77,194.304 569.552,189.196 581.335,183.984 593.117,178.666 604.9,173.239 616.682,167.702 628.465,162.051 640.248,156.285 652.03,150.402 
 663.813,144.398 675.595,138.272 687.378,132.021 699.16,125.642 710.943,119.133 722.726,112.492 734.508,105.714 746.291,98.7988 758.073,91.7422 769.856,84.5415 
 781.638,77.1939 793.421,69.6963 805.204,62.0457 816.986,54.239 828.769,46.273 840.551,38.1444 852.334,29.8499 864.116,21.3862 875.899,12.7497 887.682,3.93701 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#e9746a; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 -278.793,3.93701 -267.01,12.7497 -255.228,21.3862 -243.445,29.8499 -231.662,38.1444 -219.88,46.273 -208.097,54.239 -196.315,62.0457 -184.532,69.6963 -172.75,77.1939 
 -160.967,84.5415 -149.184,91.7422 -137.402,98.7988 -125.619,105.714 -113.837,112.492 -102.054,119.133 -90.2716,125.642 -78.489,132.021 -66.7064,138.272 -54.9239,144.398 
 -43.1413,150.402 -31.3587,156.285 -19.5762,162.051 -7.7936,167.702 3.98897,173.239 15.7715,178.666 27.5541,183.984 39.3367,189.196 51.1192,194.304 62.9018,199.309 
 74.6844,204.215 86.4669,209.022 98.2495,213.733 110.032,218.35 121.815,222.875 133.597,227.309 145.38,231.654 157.162,235.913 168.945,240.086 180.727,244.176 
 192.51,248.184 204.293,252.112 216.075,255.961 227.858,259.734 239.64,263.431 251.423,267.054 263.205,270.604 274.988,274.084 286.771,277.494 298.553,280.835 
 310.336,284.11 322.118,287.32 333.901,290.465 345.683,293.547 357.466,296.568 369.249,299.528 381.031,302.429 392.814,305.273 404.596,308.059 416.379,310.789 
 428.161,313.465 439.944,316.087 451.727,318.657 463.509,321.176 475.292,323.644 487.074,326.063 498.857,328.433 510.639,330.756 522.422,333.033 534.205,335.264 
 545.987,337.45 557.77,339.593 569.552,341.693 581.335,343.751 593.117,345.767 604.9,347.744 616.682,349.68 628.465,351.578 640.248,353.439 652.03,355.261 
 663.813,357.048 675.595,358.799 687.378,360.514 699.16,362.196 710.943,363.844 722.726,365.458 734.508,367.041 746.291,368.592 758.073,370.112 769.856,371.601 
 781.638,373.061 793.421,374.491 805.204,375.893 816.986,377.267 828.769,378.613 840.551,379.933 852.334,381.226 864.116,382.493 875.899,383.735 887.682,384.952 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#3cb370; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 -278.793,177.319 -267.01,180.006 -255.228,182.665 -243.445,185.297 -231.662,187.903 -219.88,190.483 -208.097,193.036 -196.315,195.565 -184.532,198.067 -172.75,200.545 
 -160.967,202.998 -149.184,205.426 -137.402,207

In [161]:
ylims!(0.5, 1.5)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -0.50 
 
 
 -0.25 
 
 
 0.00 
 
 
 0.25 
 
 
 0.50 
 
 
 0.50 
 
 
 0.75 
 
 
 1.00 
 
 
 1.25 
 
 
 1.50 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 -238.793,435.292 -227.549,432.431 -216.305,429.512 -205.061,426.534 -193.817,423.495 -182.573,420.394 -171.33,417.229 -160.086,414 -148.842,410.705 -137.598,407.343 
 -126.354,403.912 -115.11,400.411 -103.866,396.839 -92.6226,393.194 -81.3788,389.474 -70.1349,385.679 -58.8911,381.806 -47.6473,377.854 -36.4034,373.821 -25.1596,369.706 
 -13.9157,365.507 -2.67186,361.223 8.57198,356.851 19.8158,352.389 31.0597,347.837 42.3035,343.192 53.5474,338.452 64.7912,333.615 76.0351,328.68 87.2789,323.644 
 98.5228,318.505 109.767,313.261 121.01,307.91 132.254,302.45 143.498,296.879 154.742,291.194 165.986,285.393 177.23,279.473 188.474,273.433 199.717,267.269 
 210.961,260.98 222.205,254.562 233.449,248.013 244.693,241.331 255.937,234.512 267.18,227.554 278.424,220.455 289.668,213.21 300.912,205.817 312.156,198.274 
 323.4,190.576 334.644,182.722 345.887,174.707 357.131,166.529 368.375,158.183 379.619,149.668 390.863,140.979 402.107,132.112 413.35,123.064 424.594,113.832 
 435.838,104.411 447.082,94.7986 458.326,84.9895 469.57,74.9803 480.814,64.7668 492.057,54.3449 503.301,43.7102 514.545,32.8586 525.789,21.7855 537.033,10.4864 
 548.277,-1.04327 559.52,-12.8082 570.764,-24.8133 582.008,-37.0633 593.252,-49.5633 604.496,-62.3185 615.74,-75.3339 626.984,-88.6149 638.227,-102.167 649.471,-115.996 
 660.715,-130.106 671.959,-144.505 683.203,-159.198 694.447,-174.19 705.691,-189.489 716.934,-205.1 728.178,-221.029 739.422,-237.283 750.666,-253.869 761.91,-270.794 
 773.154,-288.063 784.397,-305.686 795.641,-323.668 806.885,-342.017 818.129,-360.74 829.373,-379.845 840.617,-399.341 851.861,-419.234 863.104,-439.533 874.348,-460.246 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#e9746a; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 -238.793,-460.246 -227.549,-439.533 -216.305,-419.234 -205.061,-399.341 -193.817,-379.845 -182.573,-360.74 -171.33,-342.017 -160.086,-323.668 -148.842,-305.686 -137.598,-288.063 
 -126.354,-270.794 -115.11,-253.869 -103.866,-237.283 -92.6226,-221.029 -81.3788,-205.1 -70.1349,-189.489 -58.8911,-174.19 -47.6473,-159.198 -36.4034,-144.505 -25.1596,-130.106 
 -13.9157,-115.996 -2.67186,-102.167 8.57198,-88.6149 19.8158,-75.3339 31.0597,-62.3185 42.3035,-49.5633 53.5474,-37.0633 64.7912,-24.8133 76.0351,-12.8082 87.2789,-1.04327 
 98.5228,10.4864 109.767,21.7855 121.01,32.8586 132.254,43.7102 143.498,54.3449 154.742,64.7668 165.986,74.9803 177.23,84.9895 188.474,94.7986 199.717,104.411 
 210.961,113.832 222.205,123.064 233.449,132.112 244.693,140.979 255.937,149.668 267.18,158.183 278.424,166.529 289.668,174.707 300.912,182.722 312.156,190.576 
 323.4,198.274 334.644,205.817 345.887,213.21 357.131,220.455 368.375,227.554 379.619,234.512 390.863,241.331 402.107,248.013 413.35,254.562 424.594,260.98 
 435.838,267.269 447.082,273.433 458.326,279.473 469.57,285.393 480.814,291.194 492.057,296.879 503.301,302.45 514.545,307.91 525.789,313.261 537.033,318.505 
 548.277,323.644 559.52,328.68 570.764,333.615 582.008,338.452 593.252,343.192 604.496,347.837 615.74,352.389 626.984,356.851 638.227,361.223 649.471,365.507 
 660.715,369.706 671.959,373.821 683.203,377.854 694.447,381.806 705.691,385.679 716.934,389.474 728.178,393.194 739.422,396.839 750.666,400.411 761.91,403.912 
 773.154,407.343 784.397,410.705 795.641,414 806.885,417.229 818.129,420.394 829.373,423.495 840.617,426.534 851.861,429.512 863.104,432.431 874.348,435.292 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#3cb370; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 -238.793,-52.728 -227.549,-46.4146 -216.305,-40.1647 -205.061,-33.9776 -193.817,-27.8526 -182.573,-21.7892 -171.33,-15

In [162]:
t = linspace(-2, 3, 200)
x = cos(t*pi*2) .* exp(t) # x(t) = cos(2πt)×e^t
y = sin(t*pi*2) .* exp(t)
plot(x, y)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -10 
 
 
 0 
 
 
 10 
 
 
 20 
 
 
 -10 
 
 
 0 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 248.11,147.763 248.14,147.436 248.109,147.101 248.014,146.766 247.856,146.44 247.634,146.132 247.352,145.85 247.013,145.604 246.624,145.402 246.191,145.251 
 245.725,145.158 245.236,145.128 244.734,145.166 244.234,145.273 243.747,145.451 243.288,145.699 242.869,146.013 242.504,146.39 242.205,146.822 241.983,147.3 
 241.848,147.816 241.809,148.356 241.87,148.909 242.036,149.461 242.308,149.996 242.684,150.501 243.159,150.96 243.726,151.359 244.376,151.685 245.095,151.924 
 245.868,152.068 246.678,152.106 247.505,152.033 248.329,151.844 249.128,151.538 249.88,151.119 250.563,150.59 251.155,149.959 251.636,149.239 251.988,148.443 
 252.195,147.588 252.244,146.694 252.125,145.781 251.834,144.874 251.369,143.995 250.733,143.169 249.933,142.421 248.983,141.774 247.9,141.251 246.704,140.871 
 245.422,140.651 244.082,140.606 242.717,140.746 241.361,141.076 240.05,141.599 238.82,142.309 237.708,143.199 236.749,144.254 235.976,145.455 235.418,146.779 
 235.103,148.196 235.049,149.675 235.272,151.18 235.781,152.674 236.576,154.116 237.653,155.466 238.997,156.684 240.586,157.732 242.393,158.573 244.38,159.175 
 246.506,159.509 248.721,159.554 250.973,159.292 253.204,158.715 255.356,157.822 257.367,156.62 259.177,155.125 260.73,153.36 261.971,151.357 262.852,149.158 
 263.331,146.808 263.375,144.363 262.961,141.88 262.074,139.423 260.715,137.058 258.895,134.851 256.637,132.867 253.979,131.171 250.967,129.822 247.665,128.872 
 244.141,128.367 240.479,128.343 236.765,128.826 233.095,129.829 229.567,131.353 226.28,133.385 223.333,135.897 220.82,138.848 218.83,142.186 217.441,145.841 
 216.721,149.734 216.723,153.777 217.483,157.871 219.023,161.911 221.34,165.79 224.416,169.397 228.207,172.624 232.653,175.367 237.671,177.53 243.158,179.026 
 248.996,179.782 255.049,179.739 261.172,178.857 267.207,177.117 272.991,174.52 278.362,171.089 283.156,166.872 287.219,161.937 290.407,156.377 292.591,150.306 
 293.663,143.855 293.538,137.174 292.156,130.425 289.489,123.782 285.541,117.424 280.349,111.532 273.984,106.283 266.554,101.849 258.196,98.3865 249.082,96.0371 
 239.411,94.9194 229.407,95.1259 219.315,96.7197 209.395,99.7304 199.914,104.152 191.143,109.943 183.348,117.02 176.783,125.267 171.683,134.527 168.258,144.61 
 166.682,155.295 167.093,166.334 169.582,177.456 174.191,188.375 180.909,198.794 189.669,208.416 200.347,216.948 212.762,224.11 226.68,229.644 241.814,233.323 
 257.831,234.953 274.357,234.388 290.987,231.528 307.29,226.33 322.825,218.81 337.145,209.044 349.812,197.172 360.411,183.396 368.558,167.979 373.913,151.238 
 376.192,133.544 375.177,115.309 370.726,96.9841 362.777,79.0423 351.357,61.9729 336.588,46.2674 318.682,32.4067 297.946,20.8484 274.776,12.0134 249.653,6.27306 
 223.133,3.93701 195.838,5.24177 168.441,10.3409 141.655,19.2965 116.21,32.0731 92.8409,48.5337 72.2666,68.4375 55.1688,91.4414 42.1738,117.104 33.8327,144.89 
 30.6037,174.184 32.8345,204.297 40.7483,234.483 54.4309,263.956 73.8218,291.91 98.7081,317.535 128.722,340.041 163.344,358.679 201.904,372.761 243.598,381.685 
 287.498,384.952 332.568,382.184 377.69,373.143 421.687,357.743 463.351,336.057 501.471,308.33 534.868,274.975 562.426,236.574 583.123,193.872 596.063,147.763 
 
 "/>
 
 
 
 
 y1

In [163]:
plot(sin, 0, 2pi, label="sin")
plot!(cos, 0, 2pi, label="cos", c=:green)
plot!(x->1, 0, 2pi, c=:red, l=:dash, label="")
plot!(x->-1, 0, 2pi, c=:red, l=:dash, label="")
ylims!(-1.2, 1.2)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 2 
 
 
 4 
 
 
 6 
 
 
 -1 
 
 
 0 
 
 
 1 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,194.444 27.5163,184.376 33.3178,174.347 39.1193,164.4 44.9208,154.573 50.7223,144.907 56.5238,135.441 62.3253,126.212 68.1268,117.258 73.9283,108.614 
 79.7298,100.317 85.5313,92.3979 91.3328,84.8901 97.1342,77.8235 102.936,71.2264 108.737,65.1255 114.539,59.5453 120.34,54.5083 126.142,50.0347 131.943,46.1427 
 137.745,42.8478 143.546,40.1633 149.348,38.1001 155.149,36.6664 160.951,35.8681 166.752,35.7082 172.554,36.1876 178.355,37.3042 184.157,39.0535 189.958,41.4285 
 195.76,44.4197 201.561,48.015 207.363,52.1999 213.164,56.9575 218.966,62.2688 224.767,68.1123 230.569,74.4645 236.37,81.2998 242.172,88.5907 247.973,96.3079 
 253.775,104.42 259.576,112.895 265.378,121.698 271.179,130.794 276.981,140.147 282.782,149.718 288.584,159.469 294.385,169.361 300.187,179.354 305.988,189.407 
 311.79,199.481 317.591,209.535 323.393,219.528 329.194,229.42 334.996,239.171 340.797,248.742 346.599,258.095 352.4,267.191 358.202,275.994 364.003,284.469 
 369.805,292.581 375.606,300.298 381.408,307.589 387.209,314.424 393.011,320.777 398.812,326.62 404.614,331.931 410.415,336.689 416.217,340.874 422.018,344.469 
 427.82,347.46 433.621,349.835 439.423,351.585 445.224,352.701 451.026,353.181 456.827,353.021 462.629,352.222 468.43,350.789 474.232,348.726 480.033,346.041 
 485.835,342.746 491.636,338.854 497.438,334.381 503.239,329.344 509.041,323.763 514.842,317.663 520.644,311.065 526.445,303.999 532.247,296.491 538.048,288.572 
 543.85,280.275 549.651,271.631 555.453,262.677 561.254,253.448 567.056,243.982 572.857,234.316 578.659,224.489 584.46,214.542 590.261,204.513 596.063,194.444 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#008100; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,35.6882 27.5163,36.0079 33.3178,36.9655 39.1193,38.5572 44.9208,40.7766 50.7223,43.6148 56.5238,47.0603 62.3253,51.0993 68.1268,55.7154 73.9283,60.8902 
 79.7298,66.6028 85.5313,72.8301 91.3328,79.5472 97.1342,86.7269 102.936,94.3403 108.737,102.357 114.539,110.744 120.34,119.468 126.142,128.495 131.943,137.787 
 137.745,147.306 143.546,157.016 149.348,166.877 155.149,176.848 160.951,186.891 166.752,196.963 172.554,207.026 178.355,217.038 184.157,226.959 189.958,236.749 
 195.76,246.369 201.561,255.779 207.363,264.943 213.164,273.823 218.966,282.383 224.767,290.589 230.569,298.408 236.37,305.808 242.172,312.76 247.973,319.235 
 253.775,325.208 259.576,330.655 265.378,335.553 271.179,339.882 276.981,343.626 282.782,346.77 288.584,349.3 294.385,351.206 300.187,352.482 305.988,353.121 
 311.79,353.121 317.591,352.482 323.393,351.206 329.194,349.3 334.996,346.77 340.797,343.626 346.599,339.882 352.4,335.553 358.202,330.655 364.003,325.208 
 369.805,319.235 375.606,312.76 381.408,305.808 387.209,298.408 393.011,290.589 398.812,282.383 404.614,273.823 410.415,264.943 416.217,255.779 422.018,246.369 
 427.82,236.749 433.621,226.959 439.423,217.038 445.224,207.026 451.026,196.963 456.827,186.891 462.629,176.848 468.43,166.877 474.232,157.016 480.033,147.306 
 485.835,137.787 491.636,128.495 497.438,119.468 503.239,110.744 509.041,102.357 514.842,94.3403 520.644,86.7269 526.445,79.5472 532.247,72.8301 538.048,66.6028 
 543.85,60.8902 549.651,55.7154 555.453,51.0993 561.254,47.0603 567.056,43.6148 572.857,40.7766 578.659,38.5572 584.46,36.9655 590.261,36.0079 596.063,35.6882 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:0.8; stroke-opacity:1; fill:none" stroke-dasharray="8, 5" points="
 21.7148,35.6882 27.5163,35.6882 33.3178,35.6882 39.1193,35.6882 44.9208,35.6882 50.7223,35.6882 56.5238,35.6882 62.3253,35.6882 68.1268,35.6882 73.9283,35.6882 
 79.7298,35.6882 85.5313,35.6882 91.3328,35.6882 97.1342,35.6882 102.936,35.6882 108.737,

In [164]:
xticks!(0 : pi/2 : 2pi)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0000000 
 
 
 1.5707963 
 
 
 3.1415927 
 
 
 4.7123890 
 
 
 6.2831853 
 
 
 -1 
 
 
 0 
 
 
 1 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,194.444 27.5163,184.376 33.3178,174.347 39.1193,164.4 44.9208,154.573 50.7223,144.907 56.5238,135.441 62.3253,126.212 68.1268,117.258 73.9283,108.614 
 79.7298,100.317 85.5313,92.3979 91.3328,84.8901 97.1342,77.8235 102.936,71.2264 108.737,65.1255 114.539,59.5453 120.34,54.5083 126.142,50.0347 131.943,46.1427 
 137.745,42.8478 143.546,40.1633 149.348,38.1001 155.149,36.6664 160.951,35.8681 166.752,35.7082 172.554,36.1876 178.355,37.3042 184.157,39.0535 189.958,41.4285 
 195.76,44.4197 201.561,48.015 207.363,52.1999 213.164,56.9575 218.966,62.2688 224.767,68.1123 230.569,74.4645 236.37,81.2998 242.172,88.5907 247.973,96.3079 
 253.775,104.42 259.576,112.895 265.378,121.698 271.179,130.794 276.981,140.147 282.782,149.718 288.584,159.469 294.385,169.361 300.187,179.354 305.988,189.407 
 311.79,199.481 317.591,209.535 323.393,219.528 329.194,229.42 334.996,239.171 340.797,248.742 346.599,258.095 352.4,267.191 358.202,275.994 364.003,284.469 
 369.805,292.581 375.606,300.298 381.408,307.589 387.209,314.424 393.011,320.777 398.812,326.62 404.614,331.931 410.415,336.689 416.217,340.874 422.018,344.469 
 427.82,347.46 433.621,349.835 439.423,351.585 445.224,352.701 451.026,353.181 456.827,353.021 462.629,352.222 468.43,350.789 474.232,348.726 480.033,346.041 
 485.835,342.746 491.636,338.854 497.438,334.381 503.239,329.344 509.041,323.763 514.842,317.663 520.644,311.065 526.445,303.999 532.247,296.491 538.048,288.572 
 543.85,280.275 549.651,271.631 555.453,262.677 561.254,253.448 567.056,243.982 572.857,234.316 578.659,224.489 584.46,214.542 590.261,204.513 596.063,194.444 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#008100; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,35.6882 27.5163,36.0079 33.3178,36.9655 39.1193,38.5572 44.9208,40.7766 50.7223,43.6148 56.5238,47.0603 62.3253,51.0993 68.1268,55.7154 73.9283,60.8902 
 79.7298,66.6028 85.5313,72.8301 91.3328,79.5472 97.1342,86.7269 102.936,94.3403 108.737,102.357 114.539,110.744 120.34,119.468 126.142,128.495 131.943,137.787 
 137.745,147.306 143.546,157.016 149.348,166.877 155.149,176.848 160.951,186.891 166.752,196.963 172.554,207.026 178.355,217.038 184.157,226.959 189.958,236.749 
 195.76,246.369 201.561,255.779 207.363,264.943 213.164,273.823 218.966,282.383 224.767,290.589 230.569,298.408 236.37,305.808 242.172,312.76 247.973,319.235 
 253.775,325.208 259.576,330.655 265.378,335.553 271.179,339.882 276.981,343.626 282.782,346.77 288.584,349.3 294.385,351.206 300.187,352.482 305.988,353.121 
 311.79,353.121 317.591,352.482 323.393,351.206 329.194,349.3 334.996,346.77 340.797,343.626 346.599,339.882 352.4,335.553 358.202,330.655 364.003,325.208 
 369.805,319.235 375.606,312.76 381.408,305.808 387.209,298.408 393.011,290.589 398.812,282.383 404.614,273.823 410.415,264.943 416.217,255.779 422.018,246.369 
 427.82,236.749 433.621,226.959 439.423,217.038 445.224,207.026 451.026,196.963 456.827,186.891 462.629,176.848 468.43,166.877 474.232,157.016 480.033,147.306 
 485.835,137.787 491.636,128.495 497.438,119.468 503.239,110.744 509.041,102.357 514.842,94.3403 520.644,86.7269 526.445,79.5472 532.247,72.8301 538.048,66.6028 
 543.85,60.8902 549.651,55.7154 555.453,51.0993 561.254,47.0603 567.056,43.6148 572.857,40.7766 578.659,38.5572 584.46,36.9655 590.261,36.0079 596.063,35.6882 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:0.8; stroke-opacity:1; fill:none" stroke-dasharray="8, 5" points="
 21.7148,35.6882 27.5163,35.6882 33.3178,35.6882 39.1193,35.6882 44.9208,35.6882 50.7223,35.6882 56.5238,35.6882 62.3253,35.6882 68.1268,35.6882 73.9283,35.6882 
 79.7298,35.6882 85.5313,35.6882 91.3

In [165]:
xticks!(0:pi/2:2pi, ["0", "\\pi /2", "\\pi", "3\\pi/2", "2\\pi"])

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 π 
 
 
 /2 
 
 
 π 
 
 
 3 
 
 
 π 
 
 
 2 
 
 
 
 2 
 
 
 π 
 
 
 -1 
 
 
 0 
 
 
 1 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,194.444 27.5163,184.376 33.3178,174.347 39.1193,164.4 44.9208,154.573 50.7223,144.907 56.5238,135.441 62.3253,126.212 68.1268,117.258 73.9283,108.614 
 79.7298,100.317 85.5313,92.3979 91.3328,84.8901 97.1342,77.8235 102.936,71.2264 108.737,65.1255 114.539,59.5453 120.34,54.5083 126.142,50.0347 131.943,46.1427 
 137.745,42.8478 143.546,40.1633 149.348,38.1001 155.149,36.6664 160.951,35.8681 166.752,35.7082 172.554,36.1876 178.355,37.3042 184.157,39.0535 189.958,41.4285 
 195.76,44.4197 201.561,48.015 207.363,52.1999 213.164,56.9575 218.966,62.2688 224.767,68.1123 230.569,74.4645 236.37,81.2998 242.172,88.5907 247.973,96.3079 
 253.775,104.42 259.576,112.895 265.378,121.698 271.179,130.794 276.981,140.147 282.782,149.718 288.584,159.469 294.385,169.361 300.187,179.354 305.988,189.407 
 311.79,199.481 317.591,209.535 323.393,219.528 329.194,229.42 334.996,239.171 340.797,248.742 346.599,258.095 352.4,267.191 358.202,275.994 364.003,284.469 
 369.805,292.581 375.606,300.298 381.408,307.589 387.209,314.424 393.011,320.777 398.812,326.62 404.614,331.931 410.415,336.689 416.217,340.874 422.018,344.469 
 427.82,347.46 433.621,349.835 439.423,351.585 445.224,352.701 451.026,353.181 456.827,353.021 462.629,352.222 468.43,350.789 474.232,348.726 480.033,346.041 
 485.835,342.746 491.636,338.854 497.438,334.381 503.239,329.344 509.041,323.763 514.842,317.663 520.644,311.065 526.445,303.999 532.247,296.491 538.048,288.572 
 543.85,280.275 549.651,271.631 555.453,262.677 561.254,253.448 567.056,243.982 572.857,234.316 578.659,224.489 584.46,214.542 590.261,204.513 596.063,194.444 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#008100; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,35.6882 27.5163,36.0079 33.3178,36.9655 39.1193,38.5572 44.9208,40.7766 50.7223,43.6148 56.5238,47.0603 62.3253,51.0993 68.1268,55.7154 73.9283,60.8902 
 79.7298,66.6028 85.5313,72.8301 91.3328,79.5472 97.1342,86.7269 102.936,94.3403 108.737,102.357 114.539,110.744 120.34,119.468 126.142,128.495 131.943,137.787 
 137.745,147.306 143.546,157.016 149.348,166.877 155.149,176.848 160.951,186.891 166.752,196.963 172.554,207.026 178.355,217.038 184.157,226.959 189.958,236.749 
 195.76,246.369 201.561,255.779 207.363,264.943 213.164,273.823 218.966,282.383 224.767,290.589 230.569,298.408 236.37,305.808 242.172,312.76 247.973,319.235 
 253.775,325.208 259.576,330.655 265.378,335.553 271.179,339.882 276.981,343.626 282.782,346.77 288.584,349.3 294.385,351.206 300.187,352.482 305.988,353.121 
 311.79,353.121 317.591,352.482 323.393,351.206 329.194,349.3 334.996,346.77 340.797,343.626 346.599,339.882 352.4,335.553 358.202,330.655 364.003,325.208 
 369.805,319.235 375.606,312.76 381.408,305.808 387.209,298.408 393.011,290.589 398.812,282.383 404.614,273.823 410.415,264.943 416.217,255.779 422.018,246.369 
 427.82,236.749 433.621,226.959 439.423,217.038 445.224,207.026 451.026,196.963 456.827,186.891 462.629,176.848 468.43,166.877 474.232,157.016 480.033,147.306 
 485.835,137.787 491.636,128.495 497.438,119.468 503.239,110.744 509.041,102.357 514.842,94.3403 520.644,86.7269 526.445,79.5472 532.247,72.8301 538.048,66.6028 
 543.85,60.8902 549.651,55.7154 555.453,51.0993 561.254,47.0603 567.056,43.6148 572.857,40.7766 578.659,38.5572 584.46,36.9655 590.261,36.0079 596.063,35.6882 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:0.8; stroke-opacity:1; fill:none" stroke-dasharray="8, 5" points="
 21.7148,35.6882 27.5163,35.6882 33.3178,35.6882 39.1193,35.6882 44.9208,35.6882 50.7223,35.6882 56.5238,35.6882 62.3253,35.6882 68.1268,35.6882 73.9283,35.6882 
 79.7298,35.6882 85.5313,35.6882 91.3328,3

In [166]:
x = linspace(0, 2*pi, 100)
anim = @animate for i = 1:5:100
    plot(x[1:i], sin(x[1:i]))
end
gif(anim, "exemplo1.gif", fps=10)

INFO: Saved animation to /home/abel/Downloads/exemplo1.gif


Plots.AnimatedGif("/home/abel/Downloads/exemplo1.gif")

In [167]:
x = linspace(0, 2*pi, 100)
anim = @animate for i = 1:3:100
    plot(x[1:i], sin(x[1:i]))
    xlims!(x[1], x[end])
    ylims!(-1, 1)
end
gif(anim, "exemplo2.gif", fps=12)

INFO: Saved animation to /home/abel/Downloads/exemplo2.gif


Plots.AnimatedGif("/home/abel/Downloads/exemplo2.gif")

In [3]:
x = linspace(0, 2*pi, 100)
anim = @animate for i = 1:3:100
    plot(x, sin(x), leg=false)
    a = x[i]
    scatter!([a], [sin(a)], c=:red)
    plot!(x, sin(a) + cos(a)*(x-a), c=:red, l=:dash)
    xlims!(x[1], x[end])
    ylims!(-2, 2)
end
gif(anim, "exemplo3.gif", fps=12)

INFO: Saved animation to /home/abel/Downloads/exemplo3.gif


Plots.AnimatedGif("/home/abel/Downloads/exemplo3.gif")

In [170]:
x = linspace(0, 2*pi, 100)
anim = @animate for i = 1:3:100
    plot(x, sin(x), leg=false)
    a = x[i]
    scatter!([a], [sin(a)], c=:red)
    plot!(x, sin(a) + cos(a)*(x-a), c=:red, l=:dash)
    plot!(x, sin(a) + cos(a)*(x-a) - sin(a)*(x-a).^2/2, c=:green, l=:dot)
    xlims!(x[1], x[end])
    ylims!(-2, 2)
end
gif(anim, "exemplo3.gif", fps=12)

INFO: Saved animation to /home/abel/Downloads/exemplo3.gif


Plots.AnimatedGif("/home/abel/Downloads/exemplo3.gif")

In [16]:
x = linspace(-pi, 3*pi, 300)
anim = @animate for i = 1:2:length(x)
    plot(x, sin(x), leg=false)
    a = x[i]
    scatter!([a], [sin(a)], c=:red)
    y = sin(a)
    p = 1
    for i = 1:3
        p = (x-a) .* p / i
        s = (-1)^(div(i,2))
        if i % 2 == 1
            t = cos(a)
        else
            t = sin(a)
        end
        y += t * p * s
        plot!(x, y, c=:red, l=:dash)
    end
    xlims!(0, 2pi)
    ylims!(-2, 2)
end
gif(anim, "exemplo3.gif", fps=12)

INFO: Saved animation to /home/abel/Downloads/exemplo3.gif


Plots.AnimatedGif("/home/abel/Downloads/exemplo3.gif")

In [172]:
t = linspace(0, 10, 100)
x = cos(pi*t) .* t
y = sin(pi*t) .* t
z = t.^2
plot(x, y, z, m=(3,:red), c=:blue)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
<polyline clip-path="url(#clip00)" style="stroke:#000000; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 30.6037,279.187 30.6037,279.187 22.946,283.646 30.6037,279.187 30.6037,263.558 26.7748,265.787 30.6037,263.558 30.6037,247.928 22.946,252.387 30.6037,247.928 
 30.6037,232.299 26.7748,234.528 30.6037,232.299 30.6037,216.67 22.946,221.128 30.6037,216.67 30.6037,201.04 26.7748,203.27 30.6037,201.04 30.6037,185.411 
 22.946,189.87 30.6037,185.411 30.6037,169.782 26.7748,172.011 30.6037,169.782 30.6037,154.152 22.946,158.611 30.6037,154.152 
 "/>
 
 
 
 
 
 
<polyline clip-path="url(#clip00)" style="stroke:#000000; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 30.6037,279.187 61.9993,289.987 58.1704,292.216 61.9993,289.987 100.195,303.126 92.537,307.584 100.195,303.126 138.39,316.264 134.561,318.494 138.39,316.264 
 176.586,329.403 168.928,333.862 176.586,329.403 214.781,342.542 210.952,344.771 214.781,342.542 252.976,355.681 245.319,360.14 252.976,355.681 291.172,368.82 
 287.343,371.049 291.172,368.82 329.367,381.959 321.709,386.417 329.367,381.959 338.069,384.952 
 "/>
 
 
 
 
 
 
 
<polyline clip-path="url(#clip00)" style="stroke:#000000; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 338.069,384.952 338.514,384.693 344.663,386.808 338.514,384.693 372.376,364.977 375.451,366.034 372.376,364.977 406.239,345.261 412.388,347.376 406.239,345.261 
 440.101,325.544 443.176,326.602 440.101,325.544 473.964,305.828 480.113,307.943 473.964,305.828 507.826,286.112 510.901,287.169 507.826,286.112 541.689,266.395 
 547.838,268.511 541.689,266.395 575.552,246.679 578.626,247.737 575.552,246.679 596.063,234.737 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#0000ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 312.48,219.021 314.374,219.27 316.588,218.906 318.509,217.94 319.539,216.506 319.198,214.837 317.21,213.232 313.559,212.02 308.518,211.501 302.623,211.9 
 296.622,213.33 291.381,215.759 287.774,219.004 286.559,222.742 288.261,226.539 293.082,229.9 300.843,232.326 310.971,233.379 322.535,232.745 334.334,230.282 
 345.019,226.055 353.246,220.34 357.837,213.615 357.934,206.515 353.123,199.77 343.52,194.129 329.789,190.272 313.112,188.729 295.085,189.809 277.567,193.55 
 262.491,199.698 251.648,207.716 246.484,216.826 247.916,226.081 256.202,234.461 270.876,240.976 290.756,244.78 314.036,245.267 338.448,242.156 361.481,235.528 
 380.642,225.845 393.721,213.913 399.045,200.817 395.678,187.813 383.557,176.209 363.539,167.221 337.347,161.846 307.43,160.744 276.732,164.154 248.404,171.853 
 225.478,183.158 210.55,196.982 205.483,211.931 211.187,226.438 227.491,238.92 253.113,247.944 285.759,252.379 322.327,251.53 359.194,245.222 392.581,233.835 
 418.938,218.288 435.321,199.957 439.715,180.551 431.275,161.945 410.452,145.99 378.983,134.321 339.756,128.184 296.543,128.292 253.644,134.737 215.452,146.963 
 186.007,163.803 168.571,183.581 165.268,204.271 176.833,223.694 202.503,239.742 240.047,250.589 285.961,254.893 335.792,251.943 384.568,241.748 427.296,225.056 
 459.473,203.299 477.555,178.459 479.351,152.879 464.275,129.038 433.446,109.295 389.616,95.6465 336.928,89.5168 280.524,91.5948 226.044,101.749 179.064,119.023 
 144.523,141.71 126.205,167.516 126.332,193.774 145.296,217.715 181.586,236.739 231.896,248.693 291.426,252.091 354.338,246.285 414.33,231.547 465.262,209.059 
 
 "/>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1

In [180]:
x = linspace(-2, 2, 100)
y = copy(x)
bat(x,y) = x^2 - y^2
contour(x, y, bat)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
<polyline clip-path="url(#clip02)" style="stroke:#ba3655; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,384.952 26.9102,381.103 32.1057,377.255 37.3011,373.406 42.4965,369.557 47.692,365.709 
 52.8874,361.86 58.0828,358.011 63.2783,354.163 68.4737,350.314 73.6691,346.466 
 78.8646,342.617 84.06,338.768 89.2555,334.92 94.4509,331.071 99.6463,327.222 
 104.842,323.374 110.037,319.525 115.233,315.676 120.428,311.828 125.624,307.979 
 130.819,304.131 136.014,300.282 141.21,296.433 146.405,292.585 151.601,288.736 
 156.796,284.887 161.992,281.039 167.187,277.19 172.382,273.341 177.578,269.493 
 182.773,265.644 187.969,261.796 193.164,257.947 198.36,254.098 203.555,250.25 
 208.75,246.401 213.946,242.552 219.141,238.704 224.337,234.855 229.532,231.006 
 234.728,227.158 239.923,223.309 245.119,219.461 250.314,215.612 255.509,211.763 
 260.705,207.915 265.9,204.066 271.096,200.217 276.291,196.369 281.487,196.369 286.682,200.217 
 291.877,204.066 297.073,207.915 302.268,211.763 307.464,215.612 312.659,219.461 
 317.855,223.309 323.05,227.158 328.246,231.006 333.441,234.855 338.636,238.704 
 343.832,242.552 349.027,246.401 354.223,250.25 359.418,254.098 364.614,257.947 
 369.809,261.796 375.004,265.644 380.2,269.493 385.395,273.341 390.591,277.19 
 395.786,281.039 400.982,284.887 406.177,288.736 411.373,292.585 416.568,296.433 
 421.763,300.282 426.959,304.131 432.154,307.979 437.35,311.828 442.545,315.676 
 447.741,319.525 452.936,323.374 458.131,327.222 463.327,331.071 468.522,334.92 
 473.718,338.768 478.913,342.617 484.109,346.466 489.304,350.314 494.5,354.163 
 499.695,358.011 504.89,361.86 510.086,365.709 515.281,369.557 520.477,373.406 
 525.672,377.255 530.868,381.103 536.063,384.952 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#d24742; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 536.063,370.812 534.473,369.557 530.868,366.649 529.677,365.709 525.672,362.472 524.898,361.86 520.477,358.28 520.138,358.011 515.394,354.163 515.281,354.069 
 510.663,350.314 510.086,349.833 505.953,346.466 504.89,345.577 501.266,342.617 499.695,341.3 496.602,338.768 494.5,337 491.965,334.92 489.304,332.675 
 487.356,331.071 484.109,328.322 482.776,327.222 478.913,323.94 478.23,323.374 473.718,319.525 469.224,315.676 468.522,315.056 464.77,311.828 
 463.327,310.545 460.358,307.979 458.131,305.989 455.992,304.131 452.936,301.382 451.677,300.282 447.741,296.718 447.416,296.433 443.195,292.585 442.545,291.969 
 439.026,288.736 437.35,287.132 434.925,284.887 432.154,282.21 430.9,281.039 426.959,277.19 423.062,273.341 421.763,271.994 419.262,269.493 
 416.568,266.657 415.569,265.644 411.972,261.796 411.373,261.116 408.463,257.947 406.177,255.301 405.095,254.098 401.848,250.25 400.982,249.15 398.723,246.401 
 395.786,242.552 392.952,238.704 390.591,235.205 390.343,234.855 387.869,231.006 385.643,227.158 385.395,226.677 383.577,223.309 381.759,219.461 
 380.2,215.612 378.833,211.763 377.739,207.915 376.919,204.066 376.372,200.217 376.098,196.369 376.098,192.52 376.372,188.671 376.919,184.823 
 377.739,180.974 378.833,177.126 380.2,173.277 381.759,169.428 383.577,165.58 385.395,162.212 385.643,161.731 387.869,157.882 390.343,154.034 
 390.591,153.684 392.952,150.185 395.786,146.337 398.723,142.488 400.982,139.739 401.848,138.639 405.095,134.791 406.177,133.588 408.463,130.942 
 411.373,127.773 411.972,127.093 415.569,123.245 416.568,122.232 419.262,119.396 421.763,116.894 423.062,115.547 426.959,111.699 430.9,107.85 
 432.154,106.679 434.925,104.002 437.35,101.756 439.026,100.153 442.545,96.92 443.195,96.3042 447.416,92.4556 447.741,92.1705 451.677,88.607 452.936,87.5074 
 455.992,84.7583 458.131,82.9004 460.358,80.9097 463.327,78.344 464.77,77.0611 468.522,73.8332 469.224,73.2124 473.718,69.3638 478.23,65.5152 
 478.91

In [181]:
contour(x, y, bat, fill=true)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
<image width="514" height="381" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAAgIAAAF9CAYAAAB22QBFAAAgAElEQVR4nOy9W4IjO8sEiNL1rWk2
Mrudpf1dqXlQIiEIJPJS7upjxUPbltDFLreFIID0//0//28mgZwTERHtmeh734iI6DtvR1s6Xqfa
l6m0/dkT7Sx3zPV9yOec6nM5By/8Z0+d/E6Jvo+2KpMT5eNFnX9P9TX3/cn9uD2LeY/GTER/djJy
ZQ+9XGnLoK2Na/vKx/ttz7+PTt7znony0beLcbVNP+ZBH2XKx8y1Le2017b92PPxOmW3r7R9q75v
I8/tuo3b61q5zZ+zlmvz17Wz3U/OVk73yTlt27dp03vo5/y2/fzH7YDGonXia2PBmFx4vjcj0RYU
DMq5c9q2BOfctBCcN6XXdG05f6IXXHMmr/uk/FbbXmLcZuQ3MJbHbYM2fuT5pezG74c2I78dv6W4
b6ONWn/pS/Wx9R1tadBHibZESr68fqX2buu41D8vclTH8V/6lZJt23iuJi/Hlj0QvVLu2jaxznb8
/tq1c51XjufnLP91vH6lTJt4btdWfSnX51LmlXYjV97rTl9HX2vLFP8fuLCwsLCwsPCfwxdrDox8
qCgpJ6o3muMhsfqyb0TbcVvLrPps9Gc/NI2qax1ziucJtbM6souXR5u8kPFO6/xbrnttYnxbZg2z
taUqker8fCuX++K32dZOYmx/Q0xExB9BEtaI/hNorzfKam9lK3vVtHOVI+JbPL9P1dfNdfTlRPvx
5vbU3+ZT3qvWvKet6ytzsBbP4zZKx/NN3t7rbULfwLe2Vvo+2naylgP+7sgbE7ASVMuB1Vf1LVha
I+R+vNsytDKIdZDVovXpv653U3Vu6sGbPqXoTf8ftwicuI+EbvpFcLofefP3bu/9+BeU0Tf1qHzd
feD2L9ukFQDd6Hku3bYBeXn7l3L8KC0Atq+/9SdqFgH9mCh1FgDTp279SVgEeGd8/nxRqn/eziIg
bu9E2iKQbFu9jffjsEUg09dm5cqcWeyR52w3fv69llYCbV14zSwCG/8O9/K9RWA38/M4vv1/pZ1e
m7ISpJ2+eFEGH4xbakpBZhl+SLm5EFI7pPgPvdcDq8nIQ4+naoff8eEdG/yztz/OH/4DyuP1mL/O
msDhyqd4SuroLvvT5iZGFu9zb9NXOd6z/COZ+amZ0JTOUuase2tz1r9DdY8c4+TEVR701bW3epBT
Vt9cOS8fRuBHD60tjxrvZ3sXfZ28+ox5/1grbHgdP9TIhWDOYqB9JaAINJO/XQ/ux54ncGxGh3Z2
DhR40CB3Axxu54uJ/QXEDvjw4e5PYJugu+DlykRM92je2Tjv0IfyYD/YXdAUB23ir7LCdC/X8xSA
3jXQ3ABIASh92A2ADvmy90Gf4waoZvy6L3HoAzeAVgSgUsFt7S5o5LdurnZgG7l6aWv72IQCwDIv
1VcOe6rPZd8mzsq2nlQ0+kM8Ue7Gcp+Wa66L1ifHfW1b/wOUhF+/fTeOL5t00m+9PG17u9EfnwKy
EHjWga5vE4cFtSXbuNSNSMdPvpy1vWonRPeH3HtlQu5FKy20mbO7Gxe1EvjrYCsBUVESkJWAqFgE
olaC0rdBK0F7m6y4NWuBthLwPGX+/ruz0bfpk1aC+r6FtaDNaTkCjJnlgMdHLQfuOmGLwHwdb6yH
uJUB4XdaBMKHefAg94dbnz5WBK7d2K8qCVvarPzA8jA69OXa8vDXB7SUtRaB1+BgT2KsuPWLg7+0
tcMf3f6R/9/0qUuYd/v/Uof97PbvcQqSeI54A+imr2/sifpbvtyr9LEbi8DRX+TnisBLKALSCmB8
/RM+AI9FfABpOSAi2rad4v/bFhYWFhYWFv5z+Hopi0CW7H5lI663f2q3/xlvoMwl5hdrsZZCNQJB
9KmNdjfpug3WMO19rJn1m/G+ma2btYPdGJ0+rEzwZUy/trQQNB3Ougtqj7IQEPXuAmkdqHs8xkvr
QGlrGqa0DpT5c2cd6OfKnXWgrG1v5Wwl2CiFuARtvOUUyDYG68/dnMBKoPcl+7Myu6e0wxu45Sfw
d218g28Wgeu3/zNc3DsWBWRN+A2I3uqjN3p/PLj9E5jzJqsf7Wtm6o/c+uF+gO/f+vd9joC8/bc2
ecPXZn3kGjgfBXDW/F/62jki3QDsGmhmdx6PLALJtCE3gLQIaCuBdANojoA08Ws3gIwa0Df9lKR1
4PDTb+LWjywC+tZPRFu9xfO4MR+ALQGID6B5A68NcQT4Q6TGDajmZz4EUwrzBnic9gsnal9Gnkty
BnhfbXfC188cgXpgi8Ob91/Xk/vivmY+RxwByZOg43WVU/yBTci3L3iGc/Br/TltQlnZ+T+E0DT4
c0E8AvMTKD5rj0NQ+hSP4Bjby1KIS8DYQN/IG47kEeTfCPILiLDPn+zf1x2v50igTffN1j9zPt8Z
H+QSvBteGJ6RC5jxx+Pnhz5axzv8zx3emHDI84wVB38u5PtHoX/a5y/nRmTBEfmvygk3AFIAWl9T
ALgNKQBFBisAREUJQDwApAC0ufo+1CZN+JojIOWTOsSlkiDDArUC0PaczR4lR0DPL8+36tev47KY
V7TptSd8ANMmOQiII/Da+ltHOr4EWdxcGe2m37Y55Q3wuIl1QG6a9s32Oc/LOEus6iIMRHRBW9fe
vHlXST/byEQXNOuCtFC0cW2O/g+dxWAUZdCRCoktAnivRQnhtrGVoPYBKwEDWQsiXAIG4hQgi4C0
FjDS4AYesRzsBztCA1kOyvix9SBqOWhtY87BDPcsAr/Twxc9zKMHuT8+pkhEb/pnD3uvbwOKADrY
R31ji4D1+cvxm/oN92L/y+vUyXHbWfIf8v/za3nwl3FUxyMeAIrl59c2t0B/8OtxmCPAN3Q7/0sd
9t3NXikJhZ/Q90krAJPgeX4YGSCJhHUfzQqg/fozPgBbAhAfoHIPqkXgG5EFj2MSKAJ7vYK3T2jq
LqB25JYPox1jez2EjsmEAsEJi/gNS2xiSR6tf0abRtqO2Ua2o3rStgO0jWy3+HZ91NomJyTaEpF5
G7n90b/VbX7P0hTV3rZHKtxyrxR076P7NHnP58mFjEgoYpGzykGZ07oSyo+PdSGUPqlcWOWA59A/
cbKPkZINH9zzbrRG/pHTCkKZQyoCOGlS6bvuLihrW1l0cEUP+LsJhUYKBzqko4grAj/vBkDreGZ9
bz8zxSF66COGvyfjJfrhPkT2YxmsHPQHv77xy+dXyH9nb/11LnDoe6b+V7K/x9L8PyIGShKgkRO3
f83039RYua9CFsSuARkF0BP8rALAj9KFUNbJNnxw4gaoBELgBmiKwPG4yIILCwsLCwufDZcjQNS0
iJT6W3NOOcwb4Dn1zTWLmzqbz6uenFN1KyDLQPOZ82uRw6Cu03gH7WZ8jBO3bG2KL+Z28uc/+tic
tIvbv+QPaA1Lhht+q89OchAax4HN71lo+4BHUOcQloebuQgYMCeBmMPKE+QUjLgEWmbr5Pj2P7MS
YI7BK1kaqZuHgAj62jXHoMwBxgbnIyLoO4e38qjv3/l7RHHmRv4T80Zv+efG27aoyf8uwa/Kkg0f
RKQ8NB75/nFSn/5mL8cbi8CE/NfGClP/Q0mANjlWWAL4Nbr9v8S8/Tq9JYCo5J3RVgIkDzkFwhJQ
9wpcA3aPzbpq8w40d0CUEMjj0VxtHzE+wAbaWt9u+

In [182]:
contour(x, y, bat, fill=true, c=:gray)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
<image width="514" height="381" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAAgIAAAF9CAYAAAB22QBFAAAgAElEQVR4nOxdUbvjLKvVzPzg8/3/
Z+K5aDWoCwQ12d1vWRczrUEg3W1AQIz/+9//pUCQUir/n+cZQgjl/3ztPM+QztSNnammozTttfM8
Ozoqp5OZzkq3Fz15n3oenOwX/5pXQHoV2amnIzyvSxdNEvRJIfVjDY/6Wj/WytHQi7yU9Nzc6956
GkSn4cnJgWNIDjNXw5Obx8FK/1M8PxExxh/nSem5uRxNBGPvARX//B7RSGMxxus10BXJQTwkORK9
ZiyYeQFdQ01/HAeU0/I44nHRlLkXT8qv5XWNXfpU/Bh9OjkRyAmxk1neH8elP6HpZBP++VpFX/j1
uiLZrxGHw+FwOBxfib/ZO8jQrsLO8FrpxkS8zvNN914XnkcZCMd5VNfCQVbc74nZL4ErszOEFFvd
8mo7hPTW42jmpZQ6vV588txY0R/oMzjPkG+zyCE8L70IDeHX6lNeE32u67Wc0Qo/T4ifEhEo9/Ye
i/GRiAD9LDIiiVB088GqbzoaEWwrUO1K/46V8m/HymfCrcSl1xU9xwusqi38pyMCDF1+/xMRgfaz
0PFC98bTH8cB5NRzQ3itri/Zr3ujK+trdd2v9I+j16ddSdP5XTTi6OVQ2R2vI6/q5QhCaPmTa5XM
A0c7uIjA39gGlarv9/hLlh+18ItXMWvFgB9GtprndQM5tH4cR3mdp9byslGNlATqHxIdyw/lWOa3
j4EYIyHLjsxb2ZSKEc4OzYs4VnTUUJf7CD15ez/gAoSN+kGkdP06jCjfsdmQfYydc0A8LUw/CYte
WmPmqYG9PNWGWpqn5JHfa2Vy1+AY4P8JjkAwOw5AL5IG4AxvLec1dMQ+PF85CUGjj+BUDO+t/+zK
fcTe8PZOiPxZtDZP0isgx0q67xCFiEBIoU0cSKujM5z9ip6smml0IIRXhIBGB1pegVnhV6/JvD5K
EPNFOUrQRRmOKgefxXSr5eJ4GKIEgj4oSnBdq3kMV/ggSiDSo8+HoefmSvxR7v51j7Gai3jOyObm
Vu/Rqp7KATpyPC1jHFajDP81WO5dY/TRGLtYWDTe9P2yIwCui8Z4IHunI9Ab3Eljyaz+r1WwwlCD
VTkylpTnNTY23pI+dBVfxoTVP41otLKP4yh60ygAjQDQaxX/o9dVjAgQXl4j4HA4HA7HF0OuEcgR
7GbFjuhDYOoGGl55pXuG86JrrlG+Z6hD65VMsALv76PnAVeYV6iiW4GfYG614i01EX26oF/hY33Y
vH4VXeijDKpVPIkQfEREAPHM/w9W4LsiAkPaJqpS0XUj+sgBh5WIwqemELSreu2K3jRfQ8eszldX
8fS9iR7QcSv1lv9TEYEgXMNjQLYyTI/C5nl+q89xRMi344/qBpoVMlrFS/pUoX5pxV504Hcs0BQH
2hmA5qF6ADEiAHj9lX5w7c3RcelLRusGWl75KRpj7OlSAPOyQZR/VGjuRVeRVEU2HW11r5d+dC4H
StXRkwGkjwiWMGlmT1L/EJBRMxiF3UAmFmrzYXp/Ah5zBLSylUb5MUdA0PnTHIGgkF2PAV4aQ03k
IQegvG95CMWFkD4yfC36GO8tCPxH9QDs3yvKMpEcdE23a6CpuqcJhVHdQAihihDQ1TyNDlR05Bqd
h6ID+VoXJahW0dfugtf/EdcNZNnNKj6Es8vPo1V2HaG4ZLX0uZigijxY8vqD3QZsdIHqCla8PxoR
UK7UucjB7oiAOnJwDXZDKJrAQRtlgHN/e0RgYe6bWDVfa8S3OgKCDhpeP+kIhAF9P4YNj0o24NWu
XGtDGir+XG+BVna1vx+s3su1bgzThdCs4mPPE+3lp3MrnjRaIO4yiN01MSJA6wHQroGp7YNnUKcL
8ntxa+CbF9ohQHcPkMj7e9rFk33gk6JHem9nqJlJBpFudSwfAal9zD+hrCvV59pJEAt90bsy6Fl2
7ziIhn1HceF149Vn8dOOAPpu5S9vxzNg50A7X6OPxNcS2pf0qsaUBn7VDZDmG8xxP1drzA1GX2Pg
tWNaR0BLrzX6nB4/6QgERo7sCAB646qf5QXC/5eBlKMRmZ42BULGFRntPAEWEIIUQp7f6YNkKxoE
Uadi5Ey0esExkAbwhkIOh8PhcDgq6GoEkGeprBvIyCvW1psKIZSUQL36F/oIFJ7v+YzMMgbWNbGE
/a+VOjs/xc7dv6ITpGFO2x8goNX/RVZYpvZNrZdqvVRPkwbnWP0A0OpdDIM312KMqijB00DfMRhR
0PJb1WdxPs9Yx1m7ol+dPxsREK8N+Jt4/UBEoF1tj/hf/4OxQZ6ek1nxoqmEtjhPSjOgVTmJMtgj
FIDeEO2gsrUFgRZdh/QmXWP4mxXJiG0unGC2bgA9yA+6Xz+zHKYG2vQCybWbOwu2dJnjodpdIDUP
Cok0GQLNg6gT0dKjXQawziAIoXiQLmh5acLz6TWhksnNFfV5IjXAyQHOQQh9GkGjj6TXHakBrdOy
6txI8y0GeXbuE0YfjWkdgTI+mLvqaDzhCPRGWOsIgGuGJj1B4sWkAZADEALu7Y90paF8OrejR+cK
tDn5wDc4qjsdNrKJnCot0Yb6yXkByElgzyaIuB5A1UeAyGFrBF6pdeYaGhPqBtAKPxyhGGioQ8OL
Og6oEdHFtxQcFH7dDzvxP/bj6A0vaihEixJbZ4JGCXTNgwRjP2hOtLO4sEWMfeEh1HFgsFcdAU1E
gOpKaTXGuLwGD8OnHIEV50BrSKXPzoKfdA52OgJojDP27XuNYeeu7XIE0Fj1v1F2zwPwHRT/IQPd
8WqjwshJkKILzOq/M9BCPYDomNBrwv1SXqgxUHcfxu2AyPHR1gNoHIFr/eo1Ag6Hw+FwfDXEGoF2
P2MZZjxLVDcQAh/qp2cLtHJiUwCQYur5k/d9xIFvRFSlC5rw+Wt+nlN7t+je+HMC3ivK4lkKSCEE
rmahe1MPdJeGcvrBa/Vbr4JHIeciO98jiEbsBrdSX5GHeKIowZ1YWf1r7537rX9taoC5polGjFbq
Gnppvnb1z8mmK146X4wgXFN7em0aAKzUCz2IBFy8QidH0hXyV+iKZKKQv9RiuOWFWgxrIyd9tAOn
MdgDj8DnOvw7gwjI33zDGdQwSqcCFno6xtQNDIv/jvyfvMWQpi1CCNWJhkXXRg5qREQ/hNaSHsfR
GbPzJfxFJuXFQQg+tPc0CueTdMHrWoTpgksOoRP463StP4wYcWoA1hKE2s+gxvXXpAYaftw1xNHS
WdBTA/N0aqM/OVdjsGfp8vtdjkD1WjA2OtnAaEwU/1HDnHmU95yTwMjh7o0zvO1YZTzJ3Ja/9r6R
A5CvcWcB0IY/1r4A9D7aexrVA3CpgXjg4sU+IkBsQXkYgop/9IXqjP1l4fV1AyFUpw/SnHxXqEfp
329ah+Dl0NTRAcnYXEWAF47LDwjouOM6mhAqi9j2Pqhy8sTAwxMJXxcLMxgYiN0EMUrQGriU+OLC
Vu/2GuLZXSeOyTW07ghoIgKccyDp32JprBt5jxuchp10KwZ8hFUDr6WbNfArY7uN/qojEAZ0rZza
mIWOrlxjKs3RGGfYoQPwvogcgEyDVtu9THBvxPB29FXBHrhfYKA5fWLsc/eVoQYOAHet0l9ZD9A5
N9J9S04Oc01uKNRUEORrtLSAPnBg+J8o3d4wR08LC

In [183]:
surface(x, y, bat)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
<polyline clip-path="url(#clip00)" style="stroke:#000000; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,279.187 21.7148,279.187 15.3788,283.243 21.7148,279.187 21.7148,263.558 18.5468,265.586 21.7148,263.558 21.7148,247.928 15.3788,251.984 21.7148,247.928 
 21.7148,232.299 18.5468,234.327 21.7148,232.299 21.7148,216.67 15.3788,220.725 21.7148,216.67 21.7148,201.04 18.5468,203.068 21.7148,201.04 21.7148,185.411 
 15.3788,189.467 21.7148,185.411 21.7148,169.782 18.5468,171.809 21.7148,169.782 21.7148,154.152 15.3788,158.208 21.7148,154.152 
 "/>
 
 
 
 
 
<polyline clip-path="url(#clip00)" style="stroke:#000000; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,279.187 21.7148,279.187 15.3788,283.243 21.7148,279.187 56.674,292.408 53.5061,294.436 56.674,292.408 91.6333,305.628 85.2973,309.684 91.6333,305.628 
 126.593,318.849 123.425,320.877 126.593,318.849 161.552,332.069 155.216,336.125 161.552,332.069 196.511,345.29 193.343,347.318 196.511,345.29 231.47,358.511 
 225.134,362.566 231.47,358.511 266.429,371.731 263.261,373.759 266.429,371.731 301.389,384.952 295.053,389.008 301.389,384.952 
 "/>
 
 
 
 
 
<polyline clip-path="url(#clip00)" style="stroke:#000000; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 301.389,384.952 301.389,384.952 306.982,387.067 301.389,384.952 330.723,366.175 333.52,367.233 330.723,366.175 360.057,347.398 365.651,349.513 360.057,347.398 
 389.392,328.621 392.188,329.679 389.392,328.621 418.726,309.844 424.319,311.96 418.726,309.844 448.06,291.067 450.857,292.125 448.06,291.067 477.394,272.29 
 482.988,274.406 477.394,272.29 506.729,253.514 509.525,254.571 506.729,253.514 536.063,234.737 541.656,236.852 536.063,234.737 
 "/>
 
<image width="514" height="381" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAAgIAAAF9CAYAAAB22QBFAAAgAElEQVR4nOy9a7Rty1YW9tWYa+1z
zj3nXO69XN4gQb2AiBeNMSpETTTEmJYETdQYohECSIAIJmlqMJKntgRbjPKIqKhAsKnNRsR3w0eM
qBBtvhAFQaKACPfBfZxz9mPtteYc1fOjqld9vVeNuebeZ5+z99mrf63NNcaoUa8x5lzj+6r3XjWS
iCAQCAQCgcDNxPK4OxAIBAKBQODxIYRAIBAIBAI3GCEEAoFAIBC4wQghEAgEAoHADUYIgUAgEAgE
bjBCCAQCgUAgcIMRQiAQCAQCgRuMEAKBQCAQCNxghBAIBAKBQOAGI4RAIBAIBAI3GCEEAoFAIBC4
wQghEAgEAoHADUYIgUAgEAgEbjBCCAQCgUAgcIMRQiAQCAQCgRuMEAKBQCAQCNxghBAIBAKBQOAG
I4RAIBAIBAI3GCEEAoFAIBC4wQghEAgEAoHADUYIgUAgEAgEbjBCCAQCgUAgcIMRQiAQCAQCgRuM
EAKBQCAQCNxghBAIBAKBQOAGI4RAIBAIBAI3GCEEAoFAIBC4wQghEAgEAoHADUYIgUAgEAgEbjBC
CAQCgUAgcIMRQiAQCAQCgRuMEAKBQCAQCNxghBAIBAKBQOAGI4RAIBAIBAI3GCEEAoFAIBC4wQgh
EAgEAoHADUYIgUAgEAgEbjBCCAQCgUAgcIMRQiAQCAQCgRuMEAKBQCAQCNxghBAIBAKBQOAGI4RA
IBAIBAI3GCEEAoFAIBC4wQghEAgEAoHADUYIgUAgEAgEbjBCCAQCgUAgcIMRQiAQCAQCgRuMEAKB
QCAQCNxghBAIBAKBQOAGI4RAIBAIBAI3GCEEAoFAIBC4wQghEAgEAoHADcbZ4+5AIPAocPUdP01S
PgDrirSuQF6BdQWAepzL8Zrrfq55MpAByQKsgKwADsD5l1ykx3tFgUAg8Pogicjj7kMgcDLuf/fP
F+QVaT0g5Ur4uRB9WldA01cSAkYEODEwEwIrgDWV9DVB8gKsC2Rd8Ox/+8EQCIFA4KlCCIHAE4W7
P/QrJEkh90L0+zbCH4hfLQAtTZDWQ7cGHBMCawayQOoWGcYigJwgOVVBsEDyUkTB2kWBrDtIXpDX
HWRdkNcFb/3qfxpCIRAIvKEQroHAY8edH/010ohexH0wSfPnct8CPV2h+aFlKL3lL7tJ+umyk1pR
k4zEBw0f+JJ3iFSh8Pav/8chCgKBwBOPEAKBx4I77/l1grwCcgAkI1WyTiDS5n3JjfATkz+6IEgs
EoDJFlSG0gAjBkw6gE76aX6au4wEIEGQ8N7P+1RRS8FHffN3hSgIBAJPJMI1EHjNcfuDv1GQ98Us
L3sgVz++VPN+dQWU4+oGMO6Bg/X/k3uguAjKuZK/+v/zirRWC8FmsKAUV4DGB1T3gMYISF6KeyAv
5XjdQarLQKo7QNYdUMk+1+Ocq+sg27R1LW4EAMjrgnXd4R1/6q+HQAgEAo8VYREIvGa4/fJvKUwr
lWVlNSP6VEf5Ketov37gjo1p336SWgkA40ZIxj1AroSWD/aYtwxJzejQy1ruFneUWlpCsyZMkJLg
+/+9XyA5L/gpf+7/CUEQCAQeC0IIBB45br/y34kl/7JN4gl+tceZTf9ua0RAtu6B6SejUbR3CZh9
9Dy89fvFaQEgjW4EytPOD+X1/Bzf80t+kax5wTv/wl8KQRAIBF5XhBAIvCrcvfhKkXyA5ENJEHUB
6OdQXQGHuk/n1MQvh+4GYFHgXQBsSWjp/Xwj+awzATR4cBZkmJrloPn3s6YDIhQMKET+FAfQLQPl
uFsCKOiQtskog1I2JTEp3/WZv1jWXNwGa17wc//anw5hEAgEXlOEEAg8FO7d/50ibPaHkq6O9Nkl
kIfjZLYc6Kekz6N9dhv04MDjFoFZ0CAaKwtcWhvFC0TmC242ot+wCJwUbdO0g0AX9mQxoFlSEqQE
/I2f90tlzQt+wXf8iRAE

## Exercícios

- Faça um gráfico de $f(x) = x^2 - 5x + 6$.
- Faça um gráfico de $f(x) = 2*sin(x)*cos(x)$.
- Faça um gráfico da função $f(x) = 1/x^2$, limitando a visão ao conjunto $[-2,2]\times[-2,2]$.
- Faça uma animação de pontos aparecendo na tela, um de cada vez.
- Faça uma função que recebe $n$ e desenho um circunferência de raio 1, e dois polígonos regulares de $n$ lados.
Um que circunscreve e outro que inscreve a circunferência. 