# NLPModels.jl, Optimize.jl e CUTEst.jl

- [NLPModels.jl](https://github.com/JuliaSmoothOptimizers/NLPModels.jl)
- [Optimize.jl](https://github.com/JuliaSmoothOptimizers/Optimize.jl)
- [CUTEst.jl](https://github.com/JuliaSmoothOptimizers/CUTEst.jl)

In [1]:
Pkg.clone("https://github.com/JuliaSmoothOptimizers/Optimize.jl")
Pkg.build("Optimize")

INFO: Cloning Optimize from https://github.com/JuliaSmoothOptimizers/Optimize.jl


LoadError: LoadError: Optimize already exists
while loading In[1], in expression starting on line 1

[Resumo das relações](http://abelsiqueira.github.io/assets/jopt-2016.pdf) (pág. 20)

In [2]:
using NLPModels

In [3]:
nlp = SimpleNLPModel(x->dot(x,x), zeros(2))

NLPModels.SimpleNLPModel(Minimization problem Generic
nvar = 2, ncon = 0 (0 linear)
,NLPModels.Counters(0,0,0,0,0,0,0,0,0,0,0),(anonymous function),(anonymous function))

In [4]:
obj(nlp, ones(2))

2.0

In [5]:
# SimpleNLPModel

f(x) = (x[1] - 1)^2 + 100*(x[2] - x[1]^2)^2
x0 = [-1.2;1.0]
c(x) = [ (x[1] + 1)*(x[2] + 1) - 1 ]
nlp = SimpleNLPModel(f, x0, c=c, lcon=[0.0], ucon=[0.0])

NLPModels.SimpleNLPModel(Minimization problem Generic
nvar = 2, ncon = 1 (0 linear)
,NLPModels.Counters(0,0,0,0,0,0,0,0,0,0,0),f,c)

In [6]:
println(nlp.meta)

1x2 Array{Float64,2}:
 -Inf  -Inf

Minimization problem Generic
nvar = 2, ncon = 1 (0 linear)
lvar = 

1x2 Array{Float64,2}:
 Inf  Inf

1x1 Array{Float64,2}:
 0.0

1x1 Array{Float64,2}:
 0.0

1x2 Array{Float64,2}:
 -1.2  1.0

1x1 Array{Float64,2}:
 0.0

1x1 Array{Int64,2}:
 1


uvar = 
lcon = 
ucon = 
x0 = 
y0 = 
nnzh = 4
nnzj = 2
nonlinear constraints: 



In [7]:
obj(nlp, nlp.meta.x0)

24.199999999999996

In [8]:
grad(nlp, nlp.meta.x0)

2-element Array{Float64,1}:
 -215.6
  -88.0

In [9]:
hess(nlp, nlp.meta.x0) # Note que é triangular inferior

2x2 Array{Float64,2}:
 1330.0    0.0
  480.0  200.0

In [10]:
hprod(nlp, nlp.meta.x0, ones(2))

2-element Array{Float64,1}:
 1810.0
  680.0

In [11]:
cons(nlp, nlp.meta.x0)

1-element Array{Float64,1}:
 -1.4

In [12]:
jac(nlp, nlp.meta.x0)

1x2 Array{Float64,2}:
 2.0  -0.2

In [13]:
# JuMPNLPModel
using JuMP
jlp = begin
    m = Model()
    @variable(m, x[1:2])
    setvalue(x[1], -1.2)
    setvalue(x[2], 1.0)
    @NLobjective(m, Min, (x[1]-1)^2 + 100*(x[2]-x[1]^2)^2)
    @NLconstraint(m, (x[1]+1)*(x[2]+1) == 1)
    JuMPNLPModel(m)
end
println(jlp.meta)

1x2 Array{Float64,2}:
 -Inf  -Inf

1x2 Array{Float64,2}:
 Inf  Inf

1x1 Array{Float64,2}:
 0.0

1x1 Array{Float64,2}:
 0.0

1x2 Array{Float64,2}:
 -1.2  1.0

1x1 Array{Float64,2}:
 0.0

1x1 Array{Int64,2}:
 1

Minimization problem Generic
nvar = 2, ncon = 1 (0 linear)
lvar = 
uvar = 
lcon = 
ucon = 
x0 = 
y0 = 
nnzh = 4
nnzj = 2
nonlinear constraints: 



In [14]:
obj(jlp, jlp.meta.x0)

24.199999999999996

In [15]:
hess(jlp, jlp.meta.x0)

2x2 sparse matrix with 3 Float64 entries:
	[1, 1]  =  1330.0
	[2, 1]  =  480.0
	[2, 2]  =  200.0

In [16]:
jac(jlp, jlp.meta.x0)

1x2 sparse matrix with 2 Float64 entries:
	[1, 1]  =  2.0
	[1, 2]  =  -0.2

In [17]:
using OptimizationProblems

In [18]:
hs6()

Minimization problem with:
 * 0 linear constraints
 * 1 nonlinear constraint
 * 2 variables
Solver is default solver

In [19]:
nlp = JuMPNLPModel(hs6())

NLPModels.JuMPNLPModel(Minimization problem Generic
nvar = 2, ncon = 1 (0 linear)
,Minimization problem with:
 * 0 linear constraints
 * 1 nonlinear constraint
 * 2 variables
Solver is ModelReader(),NLPModels.MathProgModel(JuMP.NLPEvaluator(Minimization problem with:
 * 0 linear constraints
 * 1 nonlinear constraint
 * 2 variables
Solver is ModelReader(),0x2 sparse matrix with 0 Float64 entries:,Float64[],true,[0.0,0.0],JuMP.FunctionStorage([ReverseDiffSparse.NodeData(CALL::ReverseDiffSparse.NodeType,4,-1),ReverseDiffSparse.NodeData(CALL::ReverseDiffSparse.NodeType,2,1),ReverseDiffSparse.NodeData(VALUE::ReverseDiffSparse.NodeType,1,2),ReverseDiffSparse.NodeData(VARIABLE::ReverseDiffSparse.NodeType,1,2),ReverseDiffSparse.NodeData(VALUE::ReverseDiffSparse.NodeType,2,1)],5x5 sparse matrix with 4 Bool entries:
	[2, 1]  =  true
	[5, 1]  =  true
	[3, 2]  =  true
	[4, 2]  =  true,[1.0,2.0],[4.840000000000001,2.2,1.0,-1.2,2.0],[0.0,4.4,1.0,-1.0,3.8161336241630686],[1.0,4.4,0.0,-4.4,0.0],[1],[1

In [20]:
x = nlp.meta.x0

2-element Array{Float64,1}:
 -1.2
  1.0

In [21]:
obj(nlp, x)

4.840000000000001

In [22]:
using CUTEst

In [23]:
nlp = CUTEstModel("ROSENBR")

Minimization problem ROSENBR
nvar = 2, ncon = 0 (0 linear)


In [24]:
x = nlp.meta.x0

2-element Array{Float64,1}:
 -1.2
  1.0

In [25]:
g(x) = grad(nlp, x)

g (generic function with 1 method)

In [26]:
H(x) = hess_op(nlp, x)

H (generic function with 1 method)

In [27]:
g(x)

2-element Array{Float64,1}:
 -215.6
  -88.0

In [28]:
H(x)

Linear operator
  nrow: 2
  ncol: 2
  dtype: Float64
  symmetric: true
  hermitian: true
  prod:   (anonymous function)
  tprod:  Nullable((anonymous function))
  ctprod: Nullable((anonymous function))


In [29]:
using Krylov

In [30]:
x = x - Krylov.cg(H(x), g(x))[1]

2-element Array{Float64,1}:
 -1.17528
  1.38067

In [31]:
full(H(x))

2x2 Array{Float64,2}:
 1107.27   470.112
  470.112  200.0  

In [32]:
x = nlp.meta.x0

2-element Array{Float64,1}:
 -1.2
  1.0

In [33]:
x = x - full(H(x)) \ g(x)

2-element Array{Float64,1}:
 -1.17528
  1.38067

In [34]:
cutest_finalize(nlp)

In [35]:
function newton_kkt_method(nlp::AbstractNLPModel; tol = 1e-5, max_iter = 1000, max_time = 60)
    exit_flag = 0
    x0 = nlp.meta.x0
    f(x) = obj(nlp, x)
    c(x) = cons(nlp, x)
    ∇f(x) = grad(nlp, x)
    H(x) = full(hess_op(nlp, x))
    J(x) = jac(nlp, x)
    μ = 1e-2
    
    x = copy(x0) # Cópia de x0
    iter = 0
    start_time = time()
    elapsed_time = 0.0
    fx = f(x)
    ∇fx = ∇f(x)
    B = H(x)
    cx = c(x)
    Jx = J(x)
    
    n = length(x0)
    m = length(cx)
    λ = zeros(m)

    ∇Lx = ∇fx + Jx'*λ
    
    Φ(x,μ) = f(x) + μ*norm(c(x), 1)
    while norm(∇Lx) > tol || norm(c(x), 1) > tol
        dtil = -[B Jx'; Jx zeros(m,m)]\[∇Lx; cx]
        d = dtil[1:n]
        dλ = dtil[n+1:n+m]
        Jxd = Jx*d
        
        DPx = 0.0
        for i = 1:m
            DPx += Jxd[i]*(cx[i] != 0 ? sign(cx[i]) : sign(Jxd[i]))
        end
        DΦx = dot(∇fx,d)
        #μ = DPx != 0.0 ? max(-DΦx/DPx, norm(λ,Inf)) : norm(λ,Inf)
        while DΦx + μ*DPx >= 0
            μ *= 2
        end
        DΦx += μ*DPx
        Φx = Φ(x,μ)
        
        if DΦx >= 0
            exit_flag = -1
            break
        end

        t = 1.0
        while Φ(x + t*d,μ) > Φx + 0.5*t*DΦx
            t = t*0.9
        end
        x = x + t*d
        
        fx = f(x)
        ∇fx = ∇f(x)
        B = H(x)
        cx = c(x)
        Jx = J(x)
        λ += t*dλ
        ∇Lx = ∇fx + Jx'*λ
        iter = iter + 1
        if iter >= max_iter
            exit_flag = 1
            break
        end
        elapsed_time = time() - start_time
        if elapsed_time >= max_time
            exit_flag = 2
            break
        end
    end
    return x, fx, ∇Lx, cx, exit_flag, iter, elapsed_time # Precisamos retornar o ponto encontrado
end

newton_kkt_method (generic function with 1 method)

In [36]:
nlp = CUTEstModel("HS7")

Minimization problem HS7
nvar = 2, ncon = 1 (0 linear)


In [37]:
nlp.meta.jfix

1-element Array{Int64,1}:
 1

In [38]:
newton_kkt_method(nlp)

([2.0461132184565227,1.4424439126460733],0.20363047334995565,[0.7996167071543737,-0.9992786818223892],[24.981249304766695],1,1000,0.6200850009918213)

In [39]:
cutest_finalize(nlp)