In [2]:
# Quero imprimir arquivo1.out, arquivo2.out, ..., arquivo100.out

In [3]:
# Como imprime?
println("Oi mundo")

Oi mundo


In [4]:
x = 5

5

In [7]:
println(x)
println("x = $x")
println("eˣ = $(exp(x))") #\^x

5
x = 5
eˣ = 148.4131591025766


In [10]:
println("arquivo1.out")
println("arquivo2.out")
println("arquivo3.out")

arquivo1.out
arquivo2.out
arquivo3.out


In [13]:
for i = 1:5
    println("arquivo$i.out")
end

arquivo1.out
arquivo2.out
arquivo3.out
arquivo4.out
arquivo5.out


In [14]:
for cor in ["azul", "vermelho", "verde"]
    println("A cor é $cor")
end

A cor é azul
A cor é vermelho
A cor é verde


In [17]:
A = rand(3,3)
B = rand(3,3)
C = rand(3,3)
for matriz in Any[A, B, C]
    println("Det(M) = $(det(matriz))")
end

Det(M) = 0.021671457589848984
Det(M) = 0.21475252853603713
Det(M) = 0.07628502565991428


In [19]:
arquivos = readdir()

23-element Array{ByteString,1}:
 "Aula1.ipynb"       
 "Aula2.ipynb"       
 "Aula3.ipynb"       
 "AUTOMAT.d"         
 ".git"              
 ".gitignore"        
 "intro"             
 ".ipynb_checkpoints"
 "libALLINITU.so"    
 "libBARD.so"        
 "libBEALE.so"       
 "libBT3.so"         
 "libCUBE.so"        
 "libHS35.so"        
 "libOSCIPATH.so"    
 "libROSENBR.so"     
 "MetodoGradiente.jl"
 "OUTSDIF.d"         
 "src"               
 "teste.pdf"         
 "teste.png"         
 "Untitled.ipynb"    
 "update_bfgs.o"     

In [21]:
for arq in arquivos
    println("Arquivo $arq")
end

Arquivo Aula1.ipynb
Arquivo Aula2.ipynb
Arquivo Aula3.ipynb
Arquivo AUTOMAT.d
Arquivo .git
Arquivo .gitignore
Arquivo intro
Arquivo .ipynb_checkpoints
Arquivo libALLINITU.so
Arquivo libBARD.so
Arquivo libBEALE.so
Arquivo libBT3.so
Arquivo libCUBE.so
Arquivo libHS35.so
Arquivo libOSCIPATH.so
Arquivo libROSENBR.so
Arquivo MetodoGradiente.jl
Arquivo OUTSDIF.d
Arquivo src
Arquivo teste.pdf
Arquivo teste.png
Arquivo Untitled.ipynb
Arquivo update_bfgs.o


In [22]:
# Dado um numero
n = 6
# O fatorial sera n*(n-1)*(n-2)*...*1
# Vou fazer assim:
# Comeco com i = n e com P = 1
i = n
P = 1

1

In [23]:
# Calculo P <- P*i e diminuo i
P = P*i

6

In [24]:
i = i - 1

5

In [25]:
# Calculo P <- P*i e diminuo i novamente
P = P*i
i = i - 1
println("P = $P")

P = 30


In [27]:
# Calculo P <- P*i e diminuo i novamente
P = P*i
i = i - 1
println("P = $P")

P = 120


In [28]:
# Calculo P <- P*i e diminuo i novamente
P = P*i
i = i - 1
println("P = $P")

P = 360


In [29]:
# Calculo P <- P*i e diminuo i novamente
P = P*i
i = i - 1
println("P = $P")

P = 720


In [30]:
# Calculo P <- P*i e diminuo i novamente
P = P*i
i = i - 1
println("P = $P")

P = 720


In [31]:
# Calculo P <- P*i e diminuo i novamente
P = P*i
i = i - 1
println("P = $P")

P = 0


In [33]:
# Comeco com i = n e P = 1 e facco
# P = P*i e i = i - 1
# repetidamente, ateh que i seja 1
# Ateh que i seja 1 ⇔ Enquanto nao for 1
i = n
P = 1
while i != 1 # != quer dizer diferente
    P = P*i
    i = i - 1
end
println("P = $P")

P = 720


In [43]:
# if CONDICAO
#    FACA COISAS
# end
n = 11
if mod(n,2) == 0 # N par
    println("n eh par")
else # Caso contrario
    # N impar
    println("n eh impar")
end

n eh impar


In [57]:
n = 10
if mod(n,6) == 0 # div. por 3
    println("n = 6k")
elseif mod(n,6) == 1
    # Caso nao seja, mas seja...
    # resto 1
    println("n = 6k+1")
else
    println("n eh louco mano")
end

n eh louco mano


In [61]:
# Calcular se um numero eh primo
# Ele soh eh divisivel por 1 e ele mesmo
# Assuma que o numero serah natural nao nulo
n = 32901750257
n_eh_primo = true

if n == 1
    n_eh_primo = false
else
    # Verificamos agora se n eh divisivel por
    # 2, 3, 4, ..., n - 1
    for i = 2:n-1
        if mod(n,i) == 0 # n eh div. por i
            n_eh_primo = false
            break
        end
    end
    # Se passou pelo for e nao entrou no if,
    # entao n_eh_primo nao foi modificado
    # e continua valendo true
end

if n_eh_primo
    println("$n eh primo")
else
    println("$n nao eh primo")
end

32901750257 nao eh primo


In [62]:
n = 100

100

In [63]:
n = n/2

50.0

In [64]:
n = n/2

25.0

In [65]:
n = 3n+1

76.0

In [66]:
n = n/2

38.0

In [67]:
n = n/2

19.0

In [68]:
n = 3n+1

58.0

In [69]:
n = n/2

29.0

In [70]:
n = 3n+1

88.0

In [71]:
n = n/2

44.0

In [72]:
n = n/2

22.0

In [73]:
n = n/2

11.0

In [74]:
n = 3n+1

34.0

In [75]:
n = n/2

17.0

In [76]:
n = 3n+1

52.0

In [77]:
n = n/2

26.0

In [78]:
n = n/2

13.0

In [79]:
n = 3n+1

40.0

In [80]:
n = n/2

20.0

In [81]:
n = n/2

10.0

In [83]:
mod(10.0, 3)

1.0

In [84]:
x = [2,3]

2-element Array{Int64,1}:
 2
 3

In [85]:
push!(x, 5)

3-element Array{Int64,1}:
 2
 3
 5

In [86]:
pop!(x)

5

In [87]:
x

2-element Array{Int64,1}:
 2
 3