# Introdução à Linguagem Julia

Julia é uma linguagem dinâmica de alto nível e alto desempenho.
Ela se assemelha ao MatLab e ao Python na facilidade de escrita
de código, mas sua velocidade pode ser comparável ao C e Fortran.

# Jupyter

O Jupyter é uma interface web para Julia, Python, e muitas outras.
Ela **não** é o Julia, isto é, o Julia não depende do Jupyter para
funcionar. No entanto, usando o Jupyter, aulas e apresentações
ficam mais práticas.

Cada *célula* do Jupyter pode ser executada com um `ctrl+enter`, ou
um `ctrl+shift`, sendo que o último move a seleção para a célula de
baixo.
Você pode adicionar novas células usando o `+` no topo da página.

# O REPL - Terminal Interativo

Ao abrir o Julia no Windows, ou digitar `julia` no terminal do Mac
ou Linux, se abrirá um prompt tipo

````julia
julia>
````

O Jupyter também serve como esse prompt e todo comando digitado aqui
pode ser digitado lá.

# Básico

In [1]:
2 + 3

5

In [2]:
3 * 5

15

In [3]:
7 ^ 3

343

In [4]:
exp(0)

1.0

In [5]:
sin(3.14159/4)

0.7071063120935576

In [6]:
pi

π = 3.1415926535897...

In [7]:
( sin(pi/4)*2 )^2

1.9999999999999996

In [8]:
round(pi, 2)

3.14

In [9]:
sqrt(2)

1.4142135623730951

In [10]:
abs(-3)

3

In [11]:
x = 2

2

In [12]:
x ^ 2

4

In [13]:
y = 2x

4

In [14]:
y - x

2

In [15]:
1e-2 # 10⁻²

0.01

In [16]:
1e3 # 10³

1000.0

In [17]:
0.1 + 0.2 - 0.3

5.551115123125783e-17

In [18]:
5/2

2.5

## Exercício

- Calcule $\varphi = \dfrac{\sqrt{5} + 1}{2}$.

# Álgebra Linear Numérica

In [19]:
rand(3)

3-element Array{Float64,1}:
 0.358609 
 0.0889741
 0.986542 

In [20]:
ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [21]:
zeros(3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [22]:
rand(2,4)

2×4 Array{Float64,2}:
 0.535757  0.8689    0.733794   0.923784
 0.705314  0.562009  0.0447553  0.862029

In [23]:
v = rand(3)

3-element Array{Float64,1}:
 0.770796
 0.434653
 0.276392

In [24]:
w = rand(3)

3-element Array{Float64,1}:
 0.129826
 0.116833
 0.608228

In [25]:
v + w

3-element Array{Float64,1}:
 0.900622
 0.551486
 0.884621

In [26]:
3*v

3-element Array{Float64,1}:
 2.31239 
 1.30396 
 0.829177

In [27]:
2*v + 3*w

3-element Array{Float64,1}:
 1.93107
 1.2198 
 2.37747

In [28]:
A = rand(2, 3)

2×3 Array{Float64,2}:
 0.991518  0.749083  0.08027 
 0.697381  0.726413  0.737395

In [29]:
A * v

2-element Array{Float64,1}:
 1.11203
 1.05709

In [30]:
w = rand(2)

2-element Array{Float64,1}:
 0.083807
 0.286626

In [31]:
A'

3×2 Array{Float64,2}:
 0.991518  0.697381
 0.749083  0.726413
 0.08027   0.737395

In [32]:
A' * w

3-element Array{Float64,1}:
 0.282984
 0.270987
 0.218084

In [33]:
B = rand(2, 3)

2×3 Array{Float64,2}:
 0.705477  0.766995  0.883107
 0.126214  0.65003   0.794654

In [34]:
A + B

2×3 Array{Float64,2}:
 1.69699   1.51608  0.963377
 0.823595  1.37644  1.53205 

In [35]:
A * B'

2×2 Array{Float64,2}:
 1.34492  0.675856
 1.70034  1.14618 

In [36]:
A' * B

3×3 Array{Float64,2}:
 0.787512  1.21381   1.42979 
 0.620144  1.04673   1.23877 
 0.149698  0.540895  0.656861

$$ Ax = b $$

In [37]:
A = rand(3, 3)
b = rand(3)
x = A\b # Resolve o SL

3-element Array{Float64,1}:
  0.592412
 -0.109662
  0.182173

In [38]:
A * x - b # É pra ser zero (ou quase)

3-element Array{Float64,1}:
 0.0        
 0.0        
 1.38778e-17

In [39]:
norm(A*x-b) # norm = ‖ ⋅ ‖

1.3877787807814457e-17

In [40]:
v = [1.0; 2.0; 3.0]
w = [2.0; -2.0; 2.0]
dot(v, w) # v,w

4.0

In [41]:
det(A)

0.2129035956882457

In [42]:
A^2 # A * A

3×3 Array{Float64,2}:
 0.639533  0.9852   0.483485
 0.897887  1.27201  0.848692
 0.91051   1.09145  0.526389

In [43]:
A .^ 2 # Cada elemento de A ao quadrado

3×3 Array{Float64,2}:
 0.0328714  0.280336  0.333622 
 0.829031   0.54355   0.0813747
 0.0465169  0.745909  0.155444 

In [44]:
B = rand(3, 3)

3×3 Array{Float64,2}:
 0.365618  0.909824  0.686322
 0.127251  0.606888  0.399386
 0.848016  0.468129  0.880445

In [45]:
A .* B

3×3 Array{Float64,2}:
 0.0662882  0.481722  0.39642 
 0.115863   0.447434  0.11393 
 0.182898   0.404305  0.347127

In [46]:
A = [2  3  4; 4.1  5.2  6.0]

2×3 Array{Float64,2}:
 2.0  3.0  4.0
 4.1  5.2  6.0

In [47]:
A = [2 3 4;1 0 1]

2×3 Array{Int64,2}:
 2  3  4
 1  0  1

## Funções que "distribuem"

In [48]:
exp([0.0; 1.0])

2-element Array{Float64,1}:
 1.0    
 2.71828

In [49]:
sqrt(shuffle(linspace(0, 1, 10)))

10-element Array{Float64,1}:
 0.471405
 1.0     
 0.816497
 0.333333
 0.942809
 0.745356
 0.57735 
 0.881917
 0.666667
 0.0     

## Exercício

- Crie um vetor com os ângulos importantes: 0, pi/6, pi/4, pi/3 e pi/2.
- Crie um vetor com o seno de cada ângulo e outro com o cosseno, usando o vetor acima.
- Calcule a tangente de cada angulo usando os dois vetores acima (tan = sen/cos), mas **sem usar a função tan**.

## Acesso aos elementos

In [50]:
v = rand(5)

5-element Array{Float64,1}:
 0.864847
 0.737608
 0.46581 
 0.643569
 0.335641

In [51]:
v[1]

0.8648465250325679

In [52]:
v[2]

0.737608273311448

In [53]:
v[end]

0.335641336401999

In [54]:
A

2×3 Array{Int64,2}:
 2  3  4
 1  0  1

In [55]:
A[1,1]

2

In [56]:
A[2,3]

1

In [57]:
v[2:4]

3-element Array{Float64,1}:
 0.737608
 0.46581 
 0.643569

In [58]:
2.0 : 0.01: 3.0

2.0:0.01:3.0

In [59]:
A

2×3 Array{Int64,2}:
 2  3  4
 1  0  1

In [60]:
A[:,2]

2-element Array{Int64,1}:
 3
 0

In [61]:
A[1,:]

3-element Array{Int64,1}:
 2
 3
 4

In [62]:
A[2,3] = 0.0

0.0

In [63]:
A

2×3 Array{Int64,2}:
 2  3  4
 1  0  0

In [64]:
eye(5, 7)

5×7 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0

In [65]:
m, n = size(A)

(2,3)

In [66]:
(m, n) = size(A)

(2,3)

In [67]:
length(v)

5

## Exercício

- Crie um vetor aleatório e mude o primeiro elemento para o seu oposto (i.e. mude o sinal)

In [68]:
v = rand(3)

3-element Array{Float64,1}:
 0.394025
 0.254748
 0.733368

In [69]:
v[1] = -v[1]

-0.3940245990168938

In [70]:
v

3-element Array{Float64,1}:
 -0.394025
  0.254748
  0.733368

## Matriz por blocos - concatenação

In [71]:
[rand(3,3) zeros(3,2); ones(2,3) eye(2,2)]

5×5 Array{Float64,2}:
 0.265018  0.403995  0.110655   0.0  0.0
 0.859351  0.826331  0.0707129  0.0  0.0
 0.321345  0.245345  0.231513   0.0  0.0
 1.0       1.0       1.0        1.0  0.0
 1.0       1.0       1.0        0.0  1.0

# Funções

3 tipos
- curta
- anônima
- longa

In [72]:
exp(1) - sin(1) + abs(5)

6.876810843651149

In [73]:
f(x) = x^2
f(2)

4

In [74]:
f(-3)

9

In [75]:
f(sqrt(2))

2.0000000000000004

In [76]:
g(a,b) = exp(a + b)

g (generic function with 1 method)

In [77]:
g(2,3)

148.4131591025766

In [78]:
g(3,-3)

1.0

In [79]:
h = x -> sin(x)

(::#1) (generic function with 1 method)

In [80]:
bar(f, a) = f(a) * 2 + 1

bar (generic function with 1 method)

In [81]:
bar(f, 1)

3

In [82]:
bar(x->sin(x), 5)

-0.9178485493262769

In [83]:
h(2)

0.9092974268256817

In [84]:
function soma_dois_numeros(a, b)
    return a + b
end

soma_dois_numeros (generic function with 1 method)

In [85]:
soma_dois_numeros(3, 5)

8

# Exercícios

- Crie uma função que recebe $a$ e calcula $2\bigg(a + \dfrac{1}{a}\bigg)$.
- Crie uma função que recebe dois catetos e calcula a hipotenusa.
- Crie uma função que recebe uma matriz A e um vetor v e retorna
$\dfrac{\langle v, Av\rangle}{\langle v, v\rangle}$

# Loops e condicionais

In [86]:
for i = linspace(0, 1, 11)
    println(i)
end

0.0
0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9
1.0


In [87]:
for i = 1:10
    print(i)
end

12345678910

In [88]:
for i = 1:0.5:5
    println("i = $i")
end

i = 1.0
i = 1.5
i = 2.0
i = 2.5
i = 3.0
i = 3.5
i = 4.0
i = 4.5
i = 5.0


In [89]:
x = rand(10)
y = zeros(10)
for i = 1:10
    y[i] = x[i] * i
end

In [90]:
x

10-element Array{Float64,1}:
 0.149332 
 0.241676 
 0.766446 
 0.011101 
 0.434603 
 0.672267 
 0.404629 
 0.867106 
 0.0984871
 0.485326 

In [91]:
y

10-element Array{Float64,1}:
 0.149332 
 0.483352 
 2.29934  
 0.0444039
 2.17302  
 4.0336   
 2.8324   
 6.93684  
 0.886384 
 4.85326  

In [92]:
for x in [0; pi/6; pi/4; pi/3; pi/2]
    println("cos($x) = $(cos(x))")
end

cos(0.0) = 1.0
cos(0.5235987755982988) = 0.8660254037844387
cos(0.7853981633974483) = 0.7071067811865476
cos(1.0471975511965976) = 0.5000000000000001
cos(1.5707963267948966) = 6.123233995736766e-17


In [93]:
for i = 3:3:20
    print("$i ")
end

3 6 9 12 15 18 

In [94]:
n = 6
v = ones(n)
v[n/2] = 2
v

LoadError: LoadError: ArgumentError: invalid index: 3.0
while loading In[94], in expression starting on line 3

In [95]:
n/2

3.0

In [96]:
div(7,2)

3

In [97]:
round(Int, n/2)

3

In [98]:
10 % 4

2

# Fatorial
$$ n! = n(n-1)\dots2. 1 $$

In [99]:
function fatorial(n)
    resultado = 1
    for i = 1:n
        resultado = resultado * i
    end
    return resultado
end

fatorial (generic function with 1 method)

In [100]:
fatorial(4)

24

In [101]:
fatorial(5)

120

In [102]:
fatorial(0)

1

## Exercícios

- Faça uma função `soma1(n)` que calcula a soma $1 + 2 + 3 + \dots + n$, usando `for`. (O valor exato é `n(n+1)/2`).
- Faça uma função `soma2(n)` que calcula a soma $1^2 + 2^2 + \dots + n^2$, usando `for`. (O valor exato é `n(n+1)(2n+1)/6`).

In [103]:
function sinal(x)
    if x > 0
        return 1
    elseif x < 0
        return -1
    else
        return 0
    end
end

sinal (generic function with 1 method)

In [104]:
sinal(3.2)

1

In [105]:
sinal(-1.2)

-1

In [106]:
sinal(0.0)

0

In [107]:
π

π = 3.1415926535897...

In [108]:
function bhaskara(a, b, c)
    Δ = b^2 - 4a*c
    if Δ < 0
        error("Nos reais não tem solução")
    end
    return (-b + sqrt(Δ))/2a, (-b - sqrt(Δ))/2a
end

bhaskara (generic function with 1 method)

In [109]:
bhaskara(1, 5, 6) #x^2 + 5x + 6 = 0

(-2.0,-3.0)

In [110]:
bhaskara(1, 0, 1)

LoadError: LoadError: Nos reais não tem solução
while loading In[110], in expression starting on line 1

In [111]:
bhaskara(1, 0, -1)

(1.0,-1.0)

## Exercícios

- Faça uma função `primo(n)` que retorna se o número `n` é primo ou não. Lembrando que `n % p` é o resto da divisão de `n` por `p`. Teste com a função abaixo.

In [112]:
for i = 2:15
    if primo(i)
        println("$i é primo")
    else
        println("$i não é primo")
    end
end

LoadError: LoadError: UndefVarError: primo not defined
while loading In[112], in expression starting on line 1

In [113]:
i = 1
while i <= n
    println("i = $i")
    i += 1
end

i = 1
i = 2
i = 3
i = 4
i = 5
i = 6


In [114]:
function zero_de_funcao(f, a, b)
    if f(a) * f(b) > 0
        error("f pode não ter raíz em [$a,$b]")
    end
    x = (a+b)/2
    while abs(f(x)) > 1e-8
        if f(x) * f(a) < 0
            b = x
        else
            a = x
        end
        x = (a+b)/2
    end
    return x, f(x)
end

zero_de_funcao (generic function with 1 method)

In [115]:
x, fx = zero_de_funcao(x->6x^2 - x - 1/3, 0, 1)

(0.3333333358168602,7.45058065243498e-9)

In [116]:
x, fx = zero_de_funcao(x->6x^2 - x - 1/3, -1, 0)

(-0.1666666641831398,-7.450580541412677e-9)

In [117]:
x, fx = zero_de_funcao(x->6x^2 - x - 1/3, -1, 1)

LoadError: LoadError: f pode não ter raíz em [-1,1]
while loading In[117], in expression starting on line 1

## Exercícios

- Faça uma função `collatz(n)` que calcula uma sequência
$$ a_{n+1} = \left\{\begin{array}{ll}
a_n/2, & \mbox{se $a_n$ é par} \\
3a_n + 1, & \mbox{se $a_n$ é ímpar}.
\end{array}\right.$$
começando de $a_0 = n$, e parando quando $a_n = 1$.
Imprima cada elemento da sequência.

## Operadores lógicos

In [118]:
true

true

In [119]:
true || false

true

In [120]:
true && false

false

In [121]:
if 1 > 0 && "a" in ["a", "b"]
    println("Ok")
end

Ok


In [122]:
!true

false

In [123]:
!false

true

In [124]:
function fib(n)
    if (n == 1 || n == 2)
        return 1
    else
        return fib(n-1) + fib(n-2)
    end
end

fib (generic function with 1 method)

In [125]:
fib(1)

1

In [126]:
fib(2)

1

In [127]:
fib(3)

2

In [128]:
fib(5)

5

In [129]:
fib(10)

55

In [130]:
!true

false

## !(a && b) = !a || !b

In [131]:
x = 0
n = 0

while !(x > 5 || n == 10)
    x = x + rand()
    n = n + 1
end
println("Fim, x = $x, n = $n")

Fim, x = 5.388199205182593, n = 10


In [132]:
n = 0
x = 0

while x <= 5 && n < 10
    x = x + rand()
    n = n + 1
end
println("Fim, x = $x, n = $n")

Fim, x = 4.03892937827931, n = 10


## Plots

In [133]:
using Plots
gr()

Plots.GRBackend()

In [134]:
plot([1; 2; 3], [3; 1; 2])

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 1.0 
 
 
 1.5 
 
 
 2.0 
 
 
 2.5 
 
 
 3.0 
 
 
 1.0 
 
 
 1.5 
 
 
 2.0 
 
 
 2.5 
 
 
 3.0 
 
 
 
 
 
 
 y1

In [135]:
x = linspace(-1, 2, 100)
y = x.^3 - x.^2
plot(x, y)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -1.0 
 
 
 -0.5 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 1.5 
 
 
 2.0 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 3 
 
 
 4 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,384.952 27.5163,375.562 33.3178,366.628 39.1193,358.139 44.9208,350.084 50.7223,342.454 56.5238,335.238 62.3253,328.424 68.1268,322.002 73.9283,315.963 
 79.7298,310.294 85.5313,304.986 91.3328,300.027 97.1342,295.408 102.936,291.118 108.737,287.146 114.539,283.481 120.34,280.113 126.142,277.031 131.943,274.225 
 137.745,271.684 143.546,269.397 149.348,267.355 155.149,265.545 160.951,263.958 166.752,262.584 172.554,261.41 178.355,260.428 184.157,259.626 189.958,258.993 
 195.76,258.519 201.561,258.194 207.363,258.007 213.164,257.947 218.966,258.003 224.767,258.166 230.569,258.424 236.37,258.767 242.172,259.184 247.973,259.664 
 253.775,260.198 259.576,260.774 265.378,261.382 271.179,262.011 276.981,262.651 282.782,263.29 288.584,263.92 294.385,264.527 300.187,265.103 305.988,265.637 
 311.79,266.118 317.591,266.535 323.393,266.878 329.194,267.136 334.996,267.298 340.797,267.355 346.599,267.295 352.4,267.107 358.202,266.782 364.003,266.309 
 369.805,265.676 375.606,264.874 381.408,263.891 387.209,262.718 393.011,261.343 398.812,259.756 404.614,257.947 410.415,255.904 416.217,253.618 422.018,251.077 
 427.82,248.271 433.621,245.189 439.423,241.821 445.224,238.156 451.026,234.184 456.827,229.893 462.629,225.274 468.43,220.316 474.232,215.008 480.033,209.339 
 485.835,203.299 491.636,196.878 497.438,190.064 503.239,182.847 509.041,175.217 514.842,167.163 520.644,158.674 526.445,149.74 532.247,140.35 538.048,130.493 
 543.85,120.159 549.651,109.338 555.453,98.0183 561.254,86.1897 567.056,73.8415 572.857,60.9632 578.659,47.5443 584.46,33.574 590.261,19.0418 596.063,3.93701 
 
 "/>
 
 
 
 
 y1

In [136]:
scatter(x, y)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 0.0 
 
 
 2.5 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1

In [137]:
scatter(x, rand(100))

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1

In [138]:
#f(x) = sin(x) + cos(x)
plot(x->sin(x) + cos(x)*x, 0, 4pi) # plot(fun, a, b)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 5 
 
 
 10 
 
 
 -5 
 
 
 0 
 
 
 5 
 
 
 10 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,219.645 27.5163,215.311 33.3178,211.116 39.1193,207.197 44.9208,203.683 50.7223,200.694 56.5238,198.338 62.3253,196.705 68.1268,195.869 73.9283,195.884 
 79.7298,196.784 85.5313,198.578 91.3328,201.255 97.1342,204.778 102.936,209.091 108.737,214.113 114.539,219.746 120.34,225.871 126.142,232.355 131.943,239.052 
 137.745,245.805 143.546,252.449 149.348,258.818 155.149,264.746 160.951,270.069 166.752,274.634 172.554,278.296 178.355,280.927 184.157,282.417 189.958,282.676 
 195.76,281.637 201.561,279.26 207.363,275.53 213.164,270.462 218.966,264.099 224.767,256.511 230.569,247.799 236.37,238.087 242.172,227.528 247.973,216.293 
 253.775,204.576 259.576,192.586 265.378,180.545 271.179,168.684 276.981,157.238 282.782,146.441 288.584,136.524 294.385,127.707 300.187,120.198 305.988,114.184 
 311.79,109.832 317.591,107.282 323.393,106.645 329.194,107.997 334.996,111.384 340.797,116.81 346.599,124.246 352.4,133.622 358.202,144.831 364.003,157.731 
 369.805,172.142 375.606,187.854 381.408,204.625 387.209,222.189 393.011,240.259 398.812,258.529 404.614,276.682 410.415,294.395 416.217,311.344 422.018,327.211 
 427.82,341.688 433.621,354.484 439.423,365.333 445.224,373.992 451.026,380.255 456.827,383.952 462.629,384.952 468.43,383.171 474.232,378.57 480.033,371.159 
 485.835,360.997 491.636,348.193 497.438,332.904 503.239,315.333 509.041,295.728 514.842,274.377 520.644,251.606 526.445,227.771 532.247,203.254 538.048,178.458 
 543.85,153.797 549.651,129.694 555.453,106.57 561.254,84.8368 567.056,64.8922 572.857,47.1105 578.659,31.8367 584.46,19.3799 590.261,10.0068 596.063,3.93701 
 
 "/>
 
 
 
 
 y1

In [139]:
plot(x->exp(x), -1, 1)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -1.0 
 
 
 -0.5 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 1 
 
 
 2 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 12.8259,384.952 18.7172,383.735 24.6085,382.493 30.4997,381.226 36.391,379.933 42.2823,378.613 48.1736,377.267 54.0649,375.893 59.9562,374.491 65.8475,373.061 
 71.7387,371.601 77.63,370.112 83.5213,368.592 89.4126,367.041 95.3039,365.458 101.195,363.844 107.086,362.196 112.978,360.514 118.869,358.799 124.76,357.048 
 130.652,355.261 136.543,353.439 142.434,351.578 148.325,349.68 154.217,347.744 160.108,345.767 165.999,343.751 171.891,341.693 177.782,339.593 183.673,337.45 
 189.564,335.264 195.456,333.033 201.347,330.756 207.238,328.433 213.13,326.063 219.021,323.644 224.912,321.176 230.803,318.657 236.695,316.087 242.586,313.465 
 248.477,310.789 254.369,308.059 260.26,305.273 266.151,302.429 272.042,299.528 277.934,296.568 283.825,293.547 289.716,290.465 295.608,287.32 301.499,284.11 
 307.39,280.835 313.281,277.494 319.173,274.084 325.064,270.604 330.955,267.054 336.847,263.431 342.738,259.734 348.629,255.961 354.52,252.112 360.412,248.184 
 366.303,244.176 372.194,240.086 378.085,235.913 383.977,231.654 389.868,227.309 395.759,222.875 401.651,218.35 407.542,213.733 413.433,209.022 419.324,204.215 
 425.216,199.309 431.107,194.304 436.998,189.196 442.89,183.984 448.781,178.666 454.672,173.239 460.563,167.702 466.455,162.051 472.346,156.285 478.237,150.402 
 484.129,144.398 490.02,138.272 495.911,132.021 501.802,125.642 507.694,119.133 513.585,112.492 519.476,105.714 525.368,98.7988 531.259,91.7422 537.15,84.5415 
 543.041,77.1939 548.933,69.6963 554.824,62.0457 560.715,54.239 566.607,46.273 572.498,38.1444 578.389,29.8499 584.28,21.3862 590.172,12.7497 596.063,3.93701 
 
 "/>
 
 
 
 
 y1

In [140]:
plot!(x->exp(-x)*3, -1, 1)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -1.0 
 
 
 -0.5 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 2.5 
 
 
 5.0 
 
 
 7.5 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 30.6037,384.952 36.3154,384.585 42.0271,384.21 47.7388,383.827 53.4505,383.437 59.1622,383.039 64.8739,382.632 70.5856,382.218 76.2974,381.794 82.0091,381.363 
 87.7208,380.922 93.4325,380.473 99.1442,380.014 104.856,379.546 110.568,379.068 116.279,378.581 121.991,378.083 127.703,377.576 133.414,377.058 139.126,376.529 
 144.838,375.99 150.55,375.44 156.261,374.879 161.973,374.306 167.685,373.721 173.396,373.124 179.108,372.516 184.82,371.895 190.532,371.261 196.243,370.614 
 201.955,369.954 207.667,369.281 213.378,368.594 219.09,367.892 224.802,367.177 230.514,366.447 236.225,365.702 241.937,364.942 247.649,364.166 253.36,363.374 
 259.072,362.567 264.784,361.743 270.496,360.902 276.207,360.043 281.919,359.168 287.631,358.274 293.342,357.363 299.054,356.432 304.766,355.483 310.477,354.514 
 316.189,353.526 321.901,352.517 327.613,351.488 333.324,350.437 339.036,349.366 344.748,348.272 350.459,347.156 356.171,346.018 361.883,344.856 367.595,343.67 
 373.306,342.46 379.018,341.226 384.73,339.966 390.441,338.681 396.153,337.369 401.865,336.031 407.577,334.665 413.288,333.272 419,331.85 424.712,330.398 
 430.423,328.918 436.135,327.407 441.847,325.865 447.559,324.292 453.27,322.687 458.982,321.049 464.694,319.377 470.405,317.672 476.117,315.932 481.829,314.156 
 487.54,312.344 493.252,310.495 498.964,308.608 504.676,306.682 510.387,304.718 516.099,302.713 521.811,300.667 527.522,298.58 533.234,296.45 538.946,294.277 
 544.658,292.059 550.369,289.796 556.081,287.487 561.793,285.13 567.504,282.726 573.216,280.272 578.928,277.769 584.64,275.214 590.351,272.607 596.063,269.947 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#e9746a; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 30.6037,3.93701 36.3154,11.917 42.0271,19.7375 47.7388,27.4015 53.4505,34.9123 59.1622,42.2728 64.8739,49.4862 70.5856,56.5553 76.2974,63.483 82.0091,70.2721 
 87.7208,76.9255 93.4325,83.4458 99.1442,89.8357 104.856,96.0978 110.568,102.235 116.279,108.249 121.991,114.143 127.703,119.919 133.414,125.579 139.126,131.126 
 144.838,136.563 150.55,141.89 156.261,147.111 161.973,152.228 167.685,157.242 173.396,162.156 179.108,166.972 184.82,171.692 190.532,176.317 196.243,180.849 
 201.955,185.291 207.667,189.644 213.378,193.91 219.09,198.091 224.802,202.188 230.514,206.203 236.225,210.138 241.937,213.994 247.649,217.773 253.36,221.477 
 259.072,225.106 264.784,228.663 270.496,232.149 276.207,235.564 281.919,238.912 287.631,242.193 293.342,245.408 299.054,248.559 304.766,251.646 310.477,254.672 
 316.189,257.638 321.901,260.544 327.613,263.392 333.324,266.183 339.036,268.919 344.748,271.599 350.459,274.226 356.171,276.801 361.883,279.324 367.595,281.796 
 373.306,284.219 379.018,286.594 384.73,288.921 390.441,291.201 396.153,293.436 401.865,295.626 407.577,297.773 413.288,299.876 419,301.938 424.712,303.958 
 430.423,305.938 436.135,307.878 441.847,309.78 447.559,311.643 453.27,313.469 458.982,315.259 464.694,317.012 470.405,318.731 476.117,320.416 481.829,322.066 
 487.54,323.684 493.252,325.269 498.964,326.823 504.676,328.345 510.387,329.837 516.099,331.3 521.811,332.733 527.522,334.137 533.234,335.513 538.946,336.862 
 544.658,338.184 550.369,339.479 556.081,340.749 561.793,341.993 567.504,343.212 573.216,344.406 578.928,345.577 584.64,346.725 590.351,347.849 596.063,348.951 
 
 "/>
 
 
 
 
 y1 
 
 
 
 y2

In [141]:
xlims!(-0.5, 0.5)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -0.50 
 
 
 -0.25 
 
 
 0.00 
 
 
 0.25 
 
 
 0.50 
 
 
 2.5 
 
 
 5.0 
 
 
 7.5 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 -252.126,384.952 -240.703,384.585 -229.279,384.21 -217.856,383.827 -206.432,383.437 -195.009,383.039 -183.585,382.632 -172.162,382.218 -160.739,381.794 -149.315,381.363 
 -137.892,380.922 -126.468,380.473 -115.045,380.014 -103.622,379.546 -92.1981,379.068 -80.7747,378.581 -69.3513,378.083 -57.9278,377.576 -46.5044,377.058 -35.081,376.529 
 -23.6576,375.99 -12.2342,375.44 -0.810732,374.879 10.6127,374.306 22.0361,373.721 33.4595,373.124 44.883,372.516 56.3064,371.895 67.7298,371.261 79.1532,370.614 
 90.5766,369.954 102,369.281 113.423,368.594 124.847,367.892 136.27,367.177 147.694,366.447 159.117,365.702 170.541,364.942 181.964,364.166 193.387,363.374 
 204.811,362.567 216.234,361.743 227.658,360.902 239.081,360.043 250.505,359.168 261.928,358.274 273.351,357.363 284.775,356.432 296.198,355.483 307.622,354.514 
 319.045,353.526 330.468,352.517 341.892,351.488 353.315,350.437 364.739,349.366 376.162,348.272 387.586,347.156 399.009,346.018 410.432,344.856 421.856,343.67 
 433.279,342.46 444.703,341.226 456.126,339.966 467.55,338.681 478.973,337.369 490.396,336.031 501.82,334.665 513.243,333.272 524.667,331.85 536.09,330.398 
 547.513,328.918 558.937,327.407 570.36,325.865 581.784,324.292 593.207,322.687 604.631,321.049 616.054,319.377 627.477,317.672 638.901,315.932 650.324,314.156 
 661.748,312.344 673.171,310.495 684.595,308.608 696.018,306.682 707.441,304.718 718.865,302.713 730.288,300.667 741.712,298.58 753.135,296.45 764.558,294.277 
 775.982,292.059 787.405,289.796 798.829,287.487 810.252,285.13 821.676,282.726 833.099,280.272 844.522,277.769 855.946,275.214 867.369,272.607 878.793,269.947 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#e9746a; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 -252.126,3.93701 -240.703,11.917 -229.279,19.7375 -217.856,27.4015 -206.432,34.9123 -195.009,42.2728 -183.585,49.4862 -172.162,56.5553 -160.739,63.483 -149.315,70.2721 
 -137.892,76.9255 -126.468,83.4458 -115.045,89.8357 -103.622,96.0978 -92.1981,102.235 -80.7747,108.249 -69.3513,114.143 -57.9278,119.919 -46.5044,125.579 -35.081,131.126 
 -23.6576,136.563 -12.2342,141.89 -0.810732,147.111 10.6127,152.228 22.0361,157.242 33.4595,162.156 44.883,166.972 56.3064,171.692 67.7298,176.317 79.1532,180.849 
 90.5766,185.291 102,189.644 113.423,193.91 124.847,198.091 136.27,202.188 147.694,206.203 159.117,210.138 170.541,213.994 181.964,217.773 193.387,221.477 
 204.811,225.106 216.234,228.663 227.658,232.149 239.081,235.564 250.505,238.912 261.928,242.193 273.351,245.408 284.775,248.559 296.198,251.646 307.622,254.672 
 319.045,257.638 330.468,260.544 341.892,263.392 353.315,266.183 364.739,268.919 376.162,271.599 387.586,274.226 399.009,276.801 410.432,279.324 421.856,281.796 
 433.279,284.219 444.703,286.594 456.126,288.921 467.55,291.201 478.973,293.436 490.396,295.626 501.82,297.773 513.243,299.876 524.667,301.938 536.09,303.958 
 547.513,305.938 558.937,307.878 570.36,309.78 581.784,311.643 593.207,313.469 604.631,315.259 616.054,317.012 627.477,318.731 638.901,320.416 650.324,322.066 
 661.748,323.684 673.171,325.269 684.595,326.823 696.018,328.345 707.441,329.837 718.865,331.3 730.288,332.733 741.712,334.137 753.135,335.513 764.558,336.862 
 775.982,338.184 787.405,339.479 798.829,340.749 810.252,341.993 821.676,343.212 833.099,344.406 844.522,345.577 855.946,346.725 867.369,347.849 878.793,348.951 
 
 "/>
 
 
 
 
 y1 
 
 
 
 y2

In [142]:
ylims!(0.5, 1.5)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -0.50 
 
 
 -0.25 
 
 
 0.00 
 
 
 0.25 
 
 
 0.50 
 
 
 0.50 
 
 
 0.75 
 
 
 1.00 
 
 
 1.25 
 
 
 1.50 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 -238.793,435.292 -227.549,432.431 -216.305,429.512 -205.061,426.534 -193.817,423.495 -182.573,420.394 -171.33,417.229 -160.086,414 -148.842,410.705 -137.598,407.343 
 -126.354,403.912 -115.11,400.411 -103.866,396.839 -92.6226,393.194 -81.3788,389.474 -70.1349,385.679 -58.8911,381.806 -47.6473,377.854 -36.4034,373.821 -25.1596,369.706 
 -13.9157,365.507 -2.67186,361.223 8.57198,356.851 19.8158,352.389 31.0597,347.837 42.3035,343.192 53.5474,338.452 64.7912,333.615 76.0351,328.68 87.2789,323.644 
 98.5228,318.505 109.767,313.261 121.01,307.91 132.254,302.45 143.498,296.879 154.742,291.194 165.986,285.393 177.23,279.473 188.474,273.433 199.717,267.269 
 210.961,260.98 222.205,254.562 233.449,248.013 244.693,241.331 255.937,234.512 267.18,227.554 278.424,220.455 289.668,213.21 300.912,205.817 312.156,198.274 
 323.4,190.576 334.644,182.722 345.887,174.707 357.131,166.529 368.375,158.183 379.619,149.668 390.863,140.979 402.107,132.112 413.35,123.064 424.594,113.832 
 435.838,104.411 447.082,94.7986 458.326,84.9895 469.57,74.9803 480.814,64.7668 492.057,54.3449 503.301,43.7102 514.545,32.8586 525.789,21.7855 537.033,10.4864 
 548.277,-1.04327 559.52,-12.8082 570.764,-24.8133 582.008,-37.0633 593.252,-49.5633 604.496,-62.3185 615.74,-75.3339 626.984,-88.6149 638.227,-102.167 649.471,-115.996 
 660.715,-130.106 671.959,-144.505 683.203,-159.198 694.447,-174.19 705.691,-189.489 716.934,-205.1 728.178,-221.029 739.422,-237.283 750.666,-253.869 761.91,-270.794 
 773.154,-288.063 784.397,-305.686 795.641,-323.668 806.885,-342.017 818.129,-360.74 829.373,-379.845 840.617,-399.341 851.861,-419.234 863.104,-439.533 874.348,-460.246 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#e9746a; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 -238.793,-2531.66 -227.549,-2469.52 -216.305,-2408.62 -205.061,-2348.94 -193.817,-2290.45 -182.573,-2233.14 -171.33,-2176.97 -160.086,-2121.92 -148.842,-2067.98 -137.598,-2015.11 
 -126.354,-1963.3 -115.11,-1912.53 -103.866,-1862.77 -92.6226,-1814 -81.3788,-1766.22 -70.1349,-1719.39 -58.8911,-1673.49 -47.6473,-1628.51 -36.4034,-1584.43 -25.1596,-1541.24 
 -13.9157,-1498.91 -2.67186,-1457.42 8.57198,-1416.76 19.8158,-1376.92 31.0597,-1337.87 42.3035,-1299.61 53.5474,-1262.11 64.7912,-1225.36 76.0351,-1189.34 87.2789,-1154.05 
 98.5228,-1119.46 109.767,-1085.56 121.01,-1052.34 132.254,-1019.79 143.498,-987.884 154.742,-956.618 165.986,-925.978 177.23,-895.95 188.474,-866.523 199.717,-837.684 
 210.961,-809.422 222.205,-781.726 233.449,-754.583 244.693,-727.983 255.937,-701.915 267.18,-676.368 278.424,-651.333 289.668,-626.797 300.912,-602.753 312.156,-579.19 
 323.4,-556.098 334.644,-533.467 345.887,-511.289 357.131,-489.555 368.375,-468.256 379.619,-447.382 390.863,-426.926 402.107,-406.879 413.35,-387.233 424.594,-367.979 
 435.838,-349.111 447.082,-330.621 458.326,-312.5 469.57,-294.741 480.814,-277.338 492.057,-260.282 503.301,-243.568 514.545,-227.188 525.789,-211.136 537.033,-195.404 
 548.277,-179.987 559.52,-164.879 570.764,-150.073 582.008,-135.563 593.252,-121.343 604.496,-107.407 615.74,-93.7502 626.984,-80.3664 638.227,-67.2504 649.471,-54.3966 
 660.715,-41.7999 671.959,-29.4551 683.203,-17.3573 694.447,-5.50133 705.691,6.11749 716.934,17.5039 728.178,28.6627 739.422,39.5982 750.666,50.3151 761.91,60.8176 
 773.154,71.1101 784.397,81.1968 795.641,91.0817 806.885,100.769 818.129,110.262 829.373,119.566 840.617,128.684 851.861,137.619 863.104,146.375 874.348,154.957 
 
 "/>
 
 
 
 
 y1 
 
 
 
 y2

In [143]:
t = linspace(-2, 3, 200)
x = cos(t*pi*2) .* exp(t) # x(t) = cos(2πt)×e^t
y = sin(t*pi*2) .* exp(t)
plot(x, y)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -10 
 
 
 0 
 
 
 10 
 
 
 20 
 
 
 -10 
 
 
 0 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 248.11,147.763 248.14,147.436 248.109,147.101 248.014,146.766 247.856,146.44 247.634,146.132 247.352,145.85 247.013,145.604 246.624,145.402 246.191,145.251 
 245.725,145.158 245.236,145.128 244.734,145.166 244.234,145.273 243.747,145.451 243.288,145.699 242.869,146.013 242.504,146.39 242.205,146.822 241.983,147.3 
 241.848,147.816 241.809,148.356 241.87,148.909 242.036,149.461 242.308,149.996 242.684,150.501 243.159,150.96 243.726,151.359 244.376,151.685 245.095,151.924 
 245.868,152.068 246.678,152.106 247.505,152.033 248.329,151.844 249.128,151.538 249.88,151.119 250.563,150.59 251.155,149.959 251.636,149.239 251.988,148.443 
 252.195,147.588 252.244,146.694 252.125,145.781 251.834,144.874 251.369,143.995 250.733,143.169 249.933,142.421 248.983,141.774 247.9,141.251 246.704,140.871 
 245.422,140.651 244.082,140.606 242.717,140.746 241.361,141.076 240.05,141.599 238.82,142.309 237.708,143.199 236.749,144.254 235.976,145.455 235.418,146.779 
 235.103,148.196 235.049,149.675 235.272,151.18 235.781,152.674 236.576,154.116 237.653,155.466 238.997,156.684 240.586,157.732 242.393,158.573 244.38,159.175 
 246.506,159.509 248.721,159.554 250.973,159.292 253.204,158.715 255.356,157.822 257.367,156.62 259.177,155.125 260.73,153.36 261.971,151.357 262.852,149.158 
 263.331,146.808 263.375,144.363 262.961,141.88 262.074,139.423 260.715,137.058 258.895,134.851 256.637,132.867 253.979,131.171 250.967,129.822 247.665,128.872 
 244.141,128.367 240.479,128.343 236.765,128.826 233.095,129.829 229.567,131.353 226.28,133.385 223.333,135.897 220.82,138.848 218.83,142.186 217.441,145.841 
 216.721,149.734 216.723,153.777 217.483,157.871 219.023,161.911 221.34,165.79 224.416,169.397 228.207,172.624 232.653,175.367 237.671,177.53 243.158,179.026 
 248.996,179.782 255.049,179.739 261.172,178.857 267.207,177.117 272.991,174.52 278.362,171.089 283.156,166.872 287.219,161.937 290.407,156.377 292.591,150.306 
 293.663,143.855 293.538,137.174 292.156,130.425 289.489,123.782 285.541,117.424 280.349,111.532 273.984,106.283 266.554,101.849 258.196,98.3865 249.082,96.0371 
 239.411,94.9194 229.407,95.1259 219.315,96.7197 209.395,99.7304 199.914,104.152 191.143,109.943 183.348,117.02 176.783,125.267 171.683,134.527 168.258,144.61 
 166.682,155.295 167.093,166.334 169.582,177.456 174.191,188.375 180.909,198.794 189.669,208.416 200.347,216.948 212.762,224.11 226.68,229.644 241.814,233.323 
 257.831,234.953 274.357,234.388 290.987,231.528 307.29,226.33 322.825,218.81 337.145,209.044 349.812,197.172 360.411,183.396 368.558,167.979 373.913,151.238 
 376.192,133.544 375.177,115.309 370.726,96.9841 362.777,79.0423 351.357,61.9729 336.588,46.2674 318.682,32.4067 297.946,20.8484 274.776,12.0134 249.653,6.27306 
 223.133,3.93701 195.838,5.24177 168.441,10.3409 141.655,19.2965 116.21,32.0731 92.8409,48.5337 72.2666,68.4375 55.1688,91.4414 42.1738,117.104 33.8327,144.89 
 30.6037,174.184 32.8345,204.297 40.7483,234.483 54.4309,263.956 73.8218,291.91 98.7081,317.535 128.722,340.041 163.344,358.679 201.904,372.761 243.598,381.685 
 287.498,384.952 332.568,382.184 377.69,373.143 421.687,357.743 463.351,336.057 501.471,308.33 534.868,274.975 562.426,236.574 583.123,193.872 596.063,147.763 
 
 "/>
 
 
 
 
 y1

In [144]:
plot(sin, 0, 2pi, label="sin")
plot!(cos, 0, 2pi, label="cos", c=:green)
plot!(x->1, 0, 2pi, c=:red, l=:dash, label="")
plot!(x->-1, 0, 2pi, c=:red, l=:dash, label="")
ylims!(-1.2, 1.2)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 2 
 
 
 4 
 
 
 6 
 
 
 -1 
 
 
 0 
 
 
 1 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,194.444 27.5163,184.376 33.3178,174.347 39.1193,164.4 44.9208,154.573 50.7223,144.907 56.5238,135.441 62.3253,126.212 68.1268,117.258 73.9283,108.614 
 79.7298,100.317 85.5313,92.3979 91.3328,84.8901 97.1342,77.8235 102.936,71.2264 108.737,65.1255 114.539,59.5453 120.34,54.5083 126.142,50.0347 131.943,46.1427 
 137.745,42.8478 143.546,40.1633 149.348,38.1001 155.149,36.6664 160.951,35.8681 166.752,35.7082 172.554,36.1876 178.355,37.3042 184.157,39.0535 189.958,41.4285 
 195.76,44.4197 201.561,48.015 207.363,52.1999 213.164,56.9575 218.966,62.2688 224.767,68.1123 230.569,74.4645 236.37,81.2998 242.172,88.5907 247.973,96.3079 
 253.775,104.42 259.576,112.895 265.378,121.698 271.179,130.794 276.981,140.147 282.782,149.718 288.584,159.469 294.385,169.361 300.187,179.354 305.988,189.407 
 311.79,199.481 317.591,209.535 323.393,219.528 329.194,229.42 334.996,239.171 340.797,248.742 346.599,258.095 352.4,267.191 358.202,275.994 364.003,284.469 
 369.805,292.581 375.606,300.298 381.408,307.589 387.209,314.424 393.011,320.777 398.812,326.62 404.614,331.931 410.415,336.689 416.217,340.874 422.018,344.469 
 427.82,347.46 433.621,349.835 439.423,351.585 445.224,352.701 451.026,353.181 456.827,353.021 462.629,352.222 468.43,350.789 474.232,348.726 480.033,346.041 
 485.835,342.746 491.636,338.854 497.438,334.381 503.239,329.344 509.041,323.763 514.842,317.663 520.644,311.065 526.445,303.999 532.247,296.491 538.048,288.572 
 543.85,280.275 549.651,271.631 555.453,262.677 561.254,253.448 567.056,243.982 572.857,234.316 578.659,224.489 584.46,214.542 590.261,204.513 596.063,194.444 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#008100; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,35.6882 27.5163,36.0079 33.3178,36.9655 39.1193,38.5572 44.9208,40.7766 50.7223,43.6148 56.5238,47.0603 62.3253,51.0993 68.1268,55.7154 73.9283,60.8902 
 79.7298,66.6028 85.5313,72.8301 91.3328,79.5472 97.1342,86.7269 102.936,94.3403 108.737,102.357 114.539,110.744 120.34,119.468 126.142,128.495 131.943,137.787 
 137.745,147.306 143.546,157.016 149.348,166.877 155.149,176.848 160.951,186.891 166.752,196.963 172.554,207.026 178.355,217.038 184.157,226.959 189.958,236.749 
 195.76,246.369 201.561,255.779 207.363,264.943 213.164,273.823 218.966,282.383 224.767,290.589 230.569,298.408 236.37,305.808 242.172,312.76 247.973,319.235 
 253.775,325.208 259.576,330.655 265.378,335.553 271.179,339.882 276.981,343.626 282.782,346.77 288.584,349.3 294.385,351.206 300.187,352.482 305.988,353.121 
 311.79,353.121 317.591,352.482 323.393,351.206 329.194,349.3 334.996,346.77 340.797,343.626 346.599,339.882 352.4,335.553 358.202,330.655 364.003,325.208 
 369.805,319.235 375.606,312.76 381.408,305.808 387.209,298.408 393.011,290.589 398.812,282.383 404.614,273.823 410.415,264.943 416.217,255.779 422.018,246.369 
 427.82,236.749 433.621,226.959 439.423,217.038 445.224,207.026 451.026,196.963 456.827,186.891 462.629,176.848 468.43,166.877 474.232,157.016 480.033,147.306 
 485.835,137.787 491.636,128.495 497.438,119.468 503.239,110.744 509.041,102.357 514.842,94.3403 520.644,86.7269 526.445,79.5472 532.247,72.8301 538.048,66.6028 
 543.85,60.8902 549.651,55.7154 555.453,51.0993 561.254,47.0603 567.056,43.6148 572.857,40.7766 578.659,38.5572 584.46,36.9655 590.261,36.0079 596.063,35.6882 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:0.8; stroke-opacity:1; fill:none" stroke-dasharray="8, 5" points="
 21.7148,35.6882 27.5163,35.6882 33.3178,35.6882 39.1193,35.6882 44.9208,35.6882 50.7223,35.6882 56.5238,35.6882 62.3253,35.6882 68.1268,35.6882 73.9283,35.6882 
 79.7298,35.6882 85.5313,35.6882 91.3328,35.6882 97.1342,35.6882 102.936,35.6882 108.737,

In [145]:
xticks!(0:pi/2:2pi)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0.0000000 
 
 
 1.5707963 
 
 
 3.1415927 
 
 
 4.7123890 
 
 
 6.2831853 
 
 
 -1 
 
 
 0 
 
 
 1 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,194.444 27.5163,184.376 33.3178,174.347 39.1193,164.4 44.9208,154.573 50.7223,144.907 56.5238,135.441 62.3253,126.212 68.1268,117.258 73.9283,108.614 
 79.7298,100.317 85.5313,92.3979 91.3328,84.8901 97.1342,77.8235 102.936,71.2264 108.737,65.1255 114.539,59.5453 120.34,54.5083 126.142,50.0347 131.943,46.1427 
 137.745,42.8478 143.546,40.1633 149.348,38.1001 155.149,36.6664 160.951,35.8681 166.752,35.7082 172.554,36.1876 178.355,37.3042 184.157,39.0535 189.958,41.4285 
 195.76,44.4197 201.561,48.015 207.363,52.1999 213.164,56.9575 218.966,62.2688 224.767,68.1123 230.569,74.4645 236.37,81.2998 242.172,88.5907 247.973,96.3079 
 253.775,104.42 259.576,112.895 265.378,121.698 271.179,130.794 276.981,140.147 282.782,149.718 288.584,159.469 294.385,169.361 300.187,179.354 305.988,189.407 
 311.79,199.481 317.591,209.535 323.393,219.528 329.194,229.42 334.996,239.171 340.797,248.742 346.599,258.095 352.4,267.191 358.202,275.994 364.003,284.469 
 369.805,292.581 375.606,300.298 381.408,307.589 387.209,314.424 393.011,320.777 398.812,326.62 404.614,331.931 410.415,336.689 416.217,340.874 422.018,344.469 
 427.82,347.46 433.621,349.835 439.423,351.585 445.224,352.701 451.026,353.181 456.827,353.021 462.629,352.222 468.43,350.789 474.232,348.726 480.033,346.041 
 485.835,342.746 491.636,338.854 497.438,334.381 503.239,329.344 509.041,323.763 514.842,317.663 520.644,311.065 526.445,303.999 532.247,296.491 538.048,288.572 
 543.85,280.275 549.651,271.631 555.453,262.677 561.254,253.448 567.056,243.982 572.857,234.316 578.659,224.489 584.46,214.542 590.261,204.513 596.063,194.444 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#008100; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,35.6882 27.5163,36.0079 33.3178,36.9655 39.1193,38.5572 44.9208,40.7766 50.7223,43.6148 56.5238,47.0603 62.3253,51.0993 68.1268,55.7154 73.9283,60.8902 
 79.7298,66.6028 85.5313,72.8301 91.3328,79.5472 97.1342,86.7269 102.936,94.3403 108.737,102.357 114.539,110.744 120.34,119.468 126.142,128.495 131.943,137.787 
 137.745,147.306 143.546,157.016 149.348,166.877 155.149,176.848 160.951,186.891 166.752,196.963 172.554,207.026 178.355,217.038 184.157,226.959 189.958,236.749 
 195.76,246.369 201.561,255.779 207.363,264.943 213.164,273.823 218.966,282.383 224.767,290.589 230.569,298.408 236.37,305.808 242.172,312.76 247.973,319.235 
 253.775,325.208 259.576,330.655 265.378,335.553 271.179,339.882 276.981,343.626 282.782,346.77 288.584,349.3 294.385,351.206 300.187,352.482 305.988,353.121 
 311.79,353.121 317.591,352.482 323.393,351.206 329.194,349.3 334.996,346.77 340.797,343.626 346.599,339.882 352.4,335.553 358.202,330.655 364.003,325.208 
 369.805,319.235 375.606,312.76 381.408,305.808 387.209,298.408 393.011,290.589 398.812,282.383 404.614,273.823 410.415,264.943 416.217,255.779 422.018,246.369 
 427.82,236.749 433.621,226.959 439.423,217.038 445.224,207.026 451.026,196.963 456.827,186.891 462.629,176.848 468.43,166.877 474.232,157.016 480.033,147.306 
 485.835,137.787 491.636,128.495 497.438,119.468 503.239,110.744 509.041,102.357 514.842,94.3403 520.644,86.7269 526.445,79.5472 532.247,72.8301 538.048,66.6028 
 543.85,60.8902 549.651,55.7154 555.453,51.0993 561.254,47.0603 567.056,43.6148 572.857,40.7766 578.659,38.5572 584.46,36.9655 590.261,36.0079 596.063,35.6882 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:0.8; stroke-opacity:1; fill:none" stroke-dasharray="8, 5" points="
 21.7148,35.6882 27.5163,35.6882 33.3178,35.6882 39.1193,35.6882 44.9208,35.6882 50.7223,35.6882 56.5238,35.6882 62.3253,35.6882 68.1268,35.6882 73.9283,35.6882 
 79.7298,35.6882 85.5313,35.6882 91.3

In [146]:
xticks!(0:pi/2:2pi, ["0", "\\pi /2", "\\pi", "3\\pi/2", "2\\pi"])

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 π 
 
 
 /2 
 
 
 π 
 
 
 3 
 
 
 π 
 
 
 2 
 
 
 
 2 
 
 
 π 
 
 
 -1 
 
 
 0 
 
 
 1 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,194.444 27.5163,184.376 33.3178,174.347 39.1193,164.4 44.9208,154.573 50.7223,144.907 56.5238,135.441 62.3253,126.212 68.1268,117.258 73.9283,108.614 
 79.7298,100.317 85.5313,92.3979 91.3328,84.8901 97.1342,77.8235 102.936,71.2264 108.737,65.1255 114.539,59.5453 120.34,54.5083 126.142,50.0347 131.943,46.1427 
 137.745,42.8478 143.546,40.1633 149.348,38.1001 155.149,36.6664 160.951,35.8681 166.752,35.7082 172.554,36.1876 178.355,37.3042 184.157,39.0535 189.958,41.4285 
 195.76,44.4197 201.561,48.015 207.363,52.1999 213.164,56.9575 218.966,62.2688 224.767,68.1123 230.569,74.4645 236.37,81.2998 242.172,88.5907 247.973,96.3079 
 253.775,104.42 259.576,112.895 265.378,121.698 271.179,130.794 276.981,140.147 282.782,149.718 288.584,159.469 294.385,169.361 300.187,179.354 305.988,189.407 
 311.79,199.481 317.591,209.535 323.393,219.528 329.194,229.42 334.996,239.171 340.797,248.742 346.599,258.095 352.4,267.191 358.202,275.994 364.003,284.469 
 369.805,292.581 375.606,300.298 381.408,307.589 387.209,314.424 393.011,320.777 398.812,326.62 404.614,331.931 410.415,336.689 416.217,340.874 422.018,344.469 
 427.82,347.46 433.621,349.835 439.423,351.585 445.224,352.701 451.026,353.181 456.827,353.021 462.629,352.222 468.43,350.789 474.232,348.726 480.033,346.041 
 485.835,342.746 491.636,338.854 497.438,334.381 503.239,329.344 509.041,323.763 514.842,317.663 520.644,311.065 526.445,303.999 532.247,296.491 538.048,288.572 
 543.85,280.275 549.651,271.631 555.453,262.677 561.254,253.448 567.056,243.982 572.857,234.316 578.659,224.489 584.46,214.542 590.261,204.513 596.063,194.444 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#008100; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,35.6882 27.5163,36.0079 33.3178,36.9655 39.1193,38.5572 44.9208,40.7766 50.7223,43.6148 56.5238,47.0603 62.3253,51.0993 68.1268,55.7154 73.9283,60.8902 
 79.7298,66.6028 85.5313,72.8301 91.3328,79.5472 97.1342,86.7269 102.936,94.3403 108.737,102.357 114.539,110.744 120.34,119.468 126.142,128.495 131.943,137.787 
 137.745,147.306 143.546,157.016 149.348,166.877 155.149,176.848 160.951,186.891 166.752,196.963 172.554,207.026 178.355,217.038 184.157,226.959 189.958,236.749 
 195.76,246.369 201.561,255.779 207.363,264.943 213.164,273.823 218.966,282.383 224.767,290.589 230.569,298.408 236.37,305.808 242.172,312.76 247.973,319.235 
 253.775,325.208 259.576,330.655 265.378,335.553 271.179,339.882 276.981,343.626 282.782,346.77 288.584,349.3 294.385,351.206 300.187,352.482 305.988,353.121 
 311.79,353.121 317.591,352.482 323.393,351.206 329.194,349.3 334.996,346.77 340.797,343.626 346.599,339.882 352.4,335.553 358.202,330.655 364.003,325.208 
 369.805,319.235 375.606,312.76 381.408,305.808 387.209,298.408 393.011,290.589 398.812,282.383 404.614,273.823 410.415,264.943 416.217,255.779 422.018,246.369 
 427.82,236.749 433.621,226.959 439.423,217.038 445.224,207.026 451.026,196.963 456.827,186.891 462.629,176.848 468.43,166.877 474.232,157.016 480.033,147.306 
 485.835,137.787 491.636,128.495 497.438,119.468 503.239,110.744 509.041,102.357 514.842,94.3403 520.644,86.7269 526.445,79.5472 532.247,72.8301 538.048,66.6028 
 543.85,60.8902 549.651,55.7154 555.453,51.0993 561.254,47.0603 567.056,43.6148 572.857,40.7766 578.659,38.5572 584.46,36.9655 590.261,36.0079 596.063,35.6882 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:0.8; stroke-opacity:1; fill:none" stroke-dasharray="8, 5" points="
 21.7148,35.6882 27.5163,35.6882 33.3178,35.6882 39.1193,35.6882 44.9208,35.6882 50.7223,35.6882 56.5238,35.6882 62.3253,35.6882 68.1268,35.6882 73.9283,35.6882 
 79.7298,35.6882 85.5313,35.6882 91.3328,3

In [147]:
x = linspace(0, 2*pi, 100)
anim = @animate for i = 1:5:100
    plot(x[1:i], sin(x[1:i]))
end
gif(anim, "exemplo1.gif", fps=10)

INFO: Saved animation to /home/abel/projetos/abel/abelsiqueira.github.io/disciplinas/cm141/exemplo1.gif


Plots.AnimatedGif("/home/abel/projetos/abel/abelsiqueira.github.io/disciplinas/cm141/exemplo1.gif")

In [148]:
x = linspace(0, 2*pi, 100)
anim = @animate for i = 1:3:100
    plot(x[1:i], sin(x[1:i]))
    xlims!(x[1], x[end])
    ylims!(-1, 1)
end
gif(anim, "exemplo2.gif", fps=12)

INFO: Saved animation to /home/abel/projetos/abel/abelsiqueira.github.io/disciplinas/cm141/exemplo2.gif


Plots.AnimatedGif("/home/abel/projetos/abel/abelsiqueira.github.io/disciplinas/cm141/exemplo2.gif")

In [149]:
x = linspace(0, 2*pi, 100)
anim = @animate for i = 1:3:100
    plot(x, sin(x), leg=false)
    a = x[i]
    scatter!([a], [sin(a)], c=:red)
    plot!(x, sin(a) + cos(a)*(x-a), c=:red, l=:dash)
    xlims!(x[1], x[end])
    ylims!(-2, 2)
end
gif(anim, "exemplo3.gif", fps=12)

INFO: Saved animation to /home/abel/projetos/abel/abelsiqueira.github.io/disciplinas/cm141/exemplo3.gif


Plots.AnimatedGif("/home/abel/projetos/abel/abelsiqueira.github.io/disciplinas/cm141/exemplo3.gif")

In [150]:
t = linspace(0, 10, 100)
x = cos(pi*t) .* t
y = sin(pi*t) .* t
z = sqrt(t)
plot(x, y, z, m=(3,:red), c=:blue)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
<polyline clip-path="url(#clip00)" style="stroke:#000000; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 30.6037,279.187 61.9993,289.987 58.1704,292.216 61.9993,289.987 100.195,303.126 92.537,307.584 100.195,303.126 138.39,316.264 134.561,318.494 138.39,316.264 
 176.586,329.403 168.928,333.862 176.586,329.403 214.781,342.542 210.952,344.771 214.781,342.542 252.976,355.681 245.319,360.14 252.976,355.681 291.172,368.82 
 287.343,371.049 291.172,368.82 329.367,381.959 321.709,386.417 329.367,381.959 338.069,384.952 
 "/>
 
 
 
 
 
 
 
<polyline clip-path="url(#clip00)" style="stroke:#000000; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 338.069,384.952 338.514,384.693 344.663,386.808 338.514,384.693 372.376,364.977 375.451,366.034 372.376,364.977 406.239,345.261 412.388,347.376 406.239,345.261 
 440.101,325.544 443.176,326.602 440.101,325.544 473.964,305.828 480.113,307.943 473.964,305.828 507.826,286.112 510.901,287.169 507.826,286.112 541.689,266.395 
 547.838,268.511 541.689,266.395 575.552,246.679 578.626,247.737 575.552,246.679 596.063,234.737 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#0000ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 312.48,225.272 314.374,217.58 316.588,213.943 318.509,210.484 319.539,206.965 319.198,203.476 317.21,200.246 313.559,197.557 308.518,195.681 302.623,194.825 
 296.622,195.086 291.381,196.423 287.774,198.642 286.559,201.416 288.261,204.304 293.082,206.806 300.843,208.419 310.971,208.705 322.535,207.344 334.334,204.193 
 345.019,199.314 353.246,192.983 357.837,185.676 357.934,178.025 353.123,170.76 343.52,164.629 329.789,160.31 313.112,158.333 295.085,159.006 277.567,162.366 
 262.491,168.159 251.648,175.846 246.484,184.65 247.916,193.623 256.202,201.744 270.876,208.022 290.756,211.612 314.036,211.907 338.448,208.625 361.481,201.848 
 380.642,192.036 393.721,179.997 399.045,166.813 395.678,153.742 383.557,142.091 363.539,133.075 337.347,127.691 307.43,126.599 276.732,130.039 248.404,137.785 
 225.478,149.157 210.55,163.067 205.483,178.119 211.187,192.747 227.491,205.369 253.113,214.549 285.759,219.159 322.327,218.502 359.194,212.403 392.581,201.243 
 418.938,185.94 435.321,167.87 439.715,148.742 431.275,130.431 410.452,114.787 378.983,103.446 339.756,97.6536 296.543,98.1224 253.644,104.945 215.452,117.565 
 186.007,134.815 168.571,155.019 165.268,176.151 176.833,196.033 202.503,212.554 240.047,223.892 285.961,228.702 335.792,226.273 384.568,216.615 427.296,200.476 
 459.473,179.288 477.555,155.031 479.351,130.051 464.275,106.825 433.446,87.712 389.616,74.7097 336.928,69.2409 280.524,71.9952 226.044,82.8412 179.064,100.821 
 144.523,124.23 126.205,150.773 126.332,177.783 145.296,202.491 181.586,222.297 231.896,235.047 291.426,239.257 354.338,234.278 414.33,220.381 465.262,198.749 
 
 "/>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1

In [151]:
x = linspace(-2, 2, 100)
y = copy(x)
f(x,y) = exp(-(x^2 + y^2))
contour(x, y, f)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
<polyline clip-path="url(#clip02)" style="stroke:#f3e258; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 305.074,211.763 302.268,213.842 299.276,215.612 297.073,216.704 291.877,218.627 288.478,219.461 286.682,219.844 281.487,220.398 276.291,220.398 271.096,219.844 
 269.3,219.461 265.9,218.627 260.705,216.704 258.502,215.612 255.509,213.842 252.704,211.763 250.314,209.547 248.84,207.915 246.244,204.066 245.119,201.548 
 244.601,200.217 243.853,196.369 243.853,192.52 244.601,188.671 245.119,187.341 246.244,184.823 248.84,180.974 250.314,179.342 252.704,177.126 255.509,175.047 
 258.502,173.277 260.705,172.185 265.9,170.262 269.3,169.428 271.096,169.045 276.291,168.491 281.487,168.491 286.682,169.045 288.478,169.428 291.877,170.262 
 297.073,172.185 299.276,173.277 302.268,175.047 305.074,177.126 307.464,179.342 308.937,180.974 311.534,184.823 312.659,187.341 313.177,188.671 313.924,192.52 
 313.924,196.369 313.177,200.217 312.659,201.548 311.534,204.066 308.937,207.915 307.464,209.547 305.074,211.763 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#fabf26; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 316.527,219.461 312.659,222.326 311.108,223.309 307.464,225.341 303.519,227.158 302.268,227.676 297.073,229.394 291.877,230.667 289.794,231.006 286.682,231.474 
 281.487,231.863 276.291,231.863 271.096,231.474 267.984,231.006 265.9,230.667 260.705,229.394 255.509,227.676 254.259,227.158 250.314,225.341 246.67,223.309 
 245.119,222.326 241.25,219.461 239.923,218.312 237.181,215.612 234.728,212.69 234.028,211.763 231.709,207.915 229.99,204.066 229.532,202.523 228.902,200.217 
 228.377,196.369 228.377,192.52 228.902,188.671 229.532,186.366 229.99,184.823 231.709,180.974 234.028,177.126 234.728,176.199 237.181,173.277 239.923,170.577 
 241.25,169.428 245.119,166.563 246.67,165.58 250.314,163.548 254.259,161.731 255.509,161.213 260.705,159.495 265.9,158.222 267.984,157.882 271.096,157.415 
 276.291,157.026 281.487,157.026 286.682,157.415 289.794,157.882 291.877,158.222 297.073,159.495 302.268,161.213 303.519,161.731 307.464,163.548 311.108,165.58 
 312.659,166.563 316.527,169.428 317.855,170.577 320.597,173.277 323.05,176.199 323.75,177.126 326.068,180.974 327.788,184.823 328.246,186.366 328.876,188.671 
 329.401,192.52 329.401,196.369 328.876,200.217 328.246,202.523 327.788,204.066 326.068,207.915 323.75,211.763 323.05,212.69 320.597,215.612 317.855,218.312 
 316.527,219.461 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#fb9c07; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 324.122,227.158 323.05,227.952 318.404,231.006 317.855,231.333 312.659,234.033 310.797,234.855 307.464,236.213 302.268,237.957 299.465,238.704 297.073,239.302 
 291.877,240.273 286.682,240.914 281.487,241.234 276.291,241.234 271.096,240.914 265.9,240.273 260.705,239.302 258.313,238.704 255.509,237.957 250.314,236.213 
 246.981,234.855 245.119,234.033 239.923,231.333 239.374,231.006 234.728,227.952 233.656,227.158 229.532,223.716 229.092,223.309 225.447,219.461 224.337,218.081 
 222.504,215.612 220.149,211.763 219.141,209.687 218.333,207.915 217.023,204.066 216.157,200.217 215.726,196.369 215.726,192.52 216.157,188.671 217.023,184.823 
 218.333,180.974 219.141,179.202 220.149,177.126 222.504,173.277 224.337,170.808 225.447,169.428 229.092,165.58 229.532,165.173 233.656,161.731 234.728,160.937 
 239.374,157.882 239.923,157.556 245.119,154.856 246.981,154.034 250.314,152.676 255.509,150.932 258.313,150.185 260.705,149.587 265.9,148.616 271.096,147.974 
 276.291,147.655 281.487,147.655 286.682,147.974 291.877,148.616 297.073,149.587 299.465,150.185 302.268,150.932 307.464,152.676 310.797,154.034 312.659,154.856 
 317.855,157.556 318.404,157.882 323.05,160.937 324.122,161.731 328.246,165.173 328.686,165.58 332.331,169.428 3

In [152]:
contour(x, y, f, fill=true)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
<image width="514" height="381" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAAgIAAAF9CAYAAAB22QBFAAAgAElEQVR4nOy97ZbroK4sKkivPc55
/4e9Z+zVgfvDFhSiwDhOutMzqjnGdIwxdtKJ9VWSgsgti+OHEX/7BpYQfuI+w+99Fj/y/ob4G9+B
90H6tSvnX7y25J+59q++x2X8hXv8m/CnkcPhcDgcHwxXBBwOh8Ph+GC4IuBwOBwOxwcjOEfg1Xgv
XevH4uIviP3/zL3/ImfhF/kS74T8Q3Fxjtdf+yXx+I/lErzb/fxN+JPH4XA4HI4PhisCDofD4XB8
MFwRcDgcDofjg+EcgafiA3LinxzHfs19v4Cf8CPxe9fLN/xQvPvpcfXn3/fTY/IfwSVw3sBZ+JPH
4XA4HI4PhisCDofD4XB8MFwRcDgcDofjg+EcgSX847H/i/Hvd4vzvyae/xN/h/D6a/wF5J96JD03
lnydc/Dk+7m63j/PJ3AugeLrt2/A4fhIuNAfg302P6YcOByfBw8NOBwOh8PxwXBFwOFwOByOD4Zz
BDr8jm70kjj728X+19e7Fud/xWf5XFf+j9V9+Efwmvr8z370XbvHdY7Bm9UreAGXwOsQ/CycI+Bw
IF4Qu3ehfx3sM7wsLJyL4HCIiIcGHA6Hw+H4aLgi4HA4HA7HB+ODOQJ/uDbAr9b7/838/sXzL7j3
X+HGD+H29DUdIjnfn7/mpVj56qP0p7gE1679bn0OnDfwOjhHwOF4Il4h9P9ljsGVhzv7rF+hHDgc
/zr+3SeMw+FwOByOQ3xIaOBn9J13SwG8fj9r56+7/K+GRNZc/lfe91WL/jWhhX9XX392K+Cr7uMr
HoXla1/OTFi7zrnP9vHP7d1KGf9cCOHfCRf8u08Yh8PhcDgch3COgOM98QO1+M9Y/9e8DC/wEsjf
IiBm4Zb2lc+GWbxn/k7McvwR3sHou+01DBy/BPcIOBwOh8PxwfgHPQJ/lA/wY+WAX1Hm9/lpfT8R
5z9zjSuW6yus9z/HG3iFsXvVabR6T6vXufgec1jlGKxyd05ce/ne17wwp+L07Lt8gTfwkiqUFOzv
8Dd5A3/saeJwOBwOh+OZ+Ac9Ao5PwrOt/zOW9hVL/zW8gffQ63ns/dq9cT7A2ud/hp+wyjv4NX6B
w/ECvMeTw+FwOBwOx6/gj3sE/gAf4A1j/901hvf43Nj/uZj871j6Z6z8a7yBf7jewLvxAc7cz7P5
AGfue3HNZ3MJREaNGNl1Vn9H66Dx+9Xv8iKXwHkDc/xxRcDxSfgJoX8uNOAphRSvyPy8olxcFMYs
tPDssILD8Zt4ExPC4XA4HA7Hb8A9Ag7HH8TbWP8E7N5GhD2Hw/H7+EOKwL/NB3hFK+DLdQCeHPu/
Wsnv2XF+tt5fqS3wNnyAVVzlDfwmR+Cn6g08mZ+wzCUQoXyC1ToE61wCfj+XwicXahCMfuvPD928
P2/gDykCjn8Rox/jT8T5rygbo2svn/tjJNI3wU8V/7l6bXadCwJ6lV8wPv+9BIbj34QrAg7Hi/Fx
Qp/gqvW1Ss5zOBzn8fefMA6Hw+FwOB7Gm3oEXq+fXLay/gQf4FodgGfH/s+44n8izs/PfX4dgavf
tfjX+AAnkH7C5f+bHIFXXPsF75vyCS70NDhXg+DJaZcXexf8TMrn+mfxE3hTRcDx13E1/k7XXBT6
71ZH4Kogf+cMgauIF7gDy0rEL3IE2LlnQhr0++hcAseT4YqAw/FErAr9y1kDfyyqNxJUV/oFsM86
OW/A4TiNv/U0cTgcDofD8VT8skfgD9QGEFnmA7yiL8ClWgAX6wA8O/Z/Nf7+7OtcrSPALNLla1/8
Tn5cHYFFsFDDKR7CT3AERj/Ln7rO4rWv9DRYrUEgIpIX3/d6hGaxd8Hb8QZEfqvmgIcGHKfw7Nj/
mCz4uNC/QuI7E8+n135Bu2N+7T+mCPxiHYEzPASqNDyZI3CmoNAqn8C5BI4rcEXA8RG4bIH/gNC/
6o14Z5yxypmwutLkZ3ydtbLH3jjI8a/jBxUBDwNM1zv1YF8LA1xN//tNV/wV6/+KpT96L9eyE56f
XfDXPAKXrXKGF6TRrd7nsufgamjgp9IZL1xnPfVwQBhdLha1tuay4jas8Ph5rY3/1tPE4XA4HA7H
U+GhAcdLcDXn/9nW/1US3xVi4bo34mf6HLw7LlnlDFfJeQTLpMRXWOUXaxM4HBauCDg+FucUk8eF
/nKI5oRwj3/MmfcShykVxid4A4uC1/kAjn8dL1IE/gAf4CXx2B8oB7wt0A9RofYKK/hxS/0Mv+DZ
1v/6/fDP4opVvyrgzwj3v+YROPNLvSJ2X5IhsOg5uOQlGF3nCu/gFddePPdKyWIRnn74I7wBkUup
hn+VN+AegQ/DT7nnr6b6/ZbQHwn8K1b9qoB3j8CG1Xd29fH6Evf+o9c4c51nzzsx170j/yb+1tPE
4XA4HA7HU+EeAcc/A2u1oxdg3cOw7h25Yumfsehf4VF4JWhfgMF7SNTC7OeyeYMgzuI1OB7xEjhR
z/HX8WcUAecDwNAiH+Cn4vTP5hKIPBYGsOvjsVWhP/osmCC7Evt/BR/gXcIFrwgDXLnO6BrL5x8p
B3r8QrigW9OujXi3GgarYYVRyWJaY5g9Z9ipz+UNiDy/RPFfKEj1ZxQBx/uhF7y34bHt+JmY/HnF
xh6PBx6BM5b6Fav+ihJx7jrv4RE4g6vC/Mo1rtCtUJgXAX6l+I885o0YXWe1aqLDIeIcAYfD4XA4
PhruEXC8FRqvwiTmP5ojMvcE4PpnLPVV9/6q5+CM9b5cw+BN9PpTPRMWbfBEP+v+3DOW8CNOZcp/
2L9vj1vv7+UmdnwenqAIPP/h8xN8gHPXeDIf4ESPzp/gAzzaAdCu9Rg5z6yxGPOfrzm+xzg5Zo8f
jV8R+ueE5d9SBM7g2aGBVeH+6Pmz+33YtT8JH1xa84eqGl5NXXx2u+MrvAGREzH9J/MGhtdZxuPB
LvcIfBBGMfxHCwqdJ+cdC8TVmP9ojr2OFY5HHoGrHIFVof+KrIGYr/b6fRJe0BnxioA/wxE4Oj+S
sRmWBPkTyIZ0zSeSBT0z4t+GKwKOX8MjjP+Zq7/MX/QIrFj57fyx92K2Jh07IbT/XGjghNCIi+Xr
ElEuWFog/5u089Lu3n9EudBzHrW9aItlXc0Fr+OX8B5PDofD4XA4HL+Ckx6BN9MbXuCC/C0+wNg9
/zw+wMjt/miJ4Xm63vPCAKsxfzbHHj/LEYgT8uIV6985AhuWXezMQl78/dszZ2ddiS4vz1upI3Ax
XJCezRGY3c8LahjwmDwjBDybNyByqXj1Bd7Aa7D2rfTQwB/CXJBeK+DTznmMBzBj/J9fi7+3Wcyf
zTnPERi7/2dKRRlbFPpXiwzFxQYuq673R5HIU5y9jzQghNG55EFFH+MPKgcz9/5s/tE5K6JmlWx4
tTZBDGukwtUQBAtfTO/nwes4fgeuCDhejqsKwKMx/7lngCstK1kDVtgfnc8VhjMegWtepVeCJUEy
ay5mni55RZGgHAEjcLKkTjnQ9Y84BpzBHfd5CeaNUxaZN8KOraYkepqh41WYKAKvf6j81IOLX2f9
2j8RBhi1DJ4T6s5X8rsSQhCZu/9H93qm4h8T3o+6+leJfkcEQpFW+M9CBKtCnwn3c+GCte/ab3gE
mHrA560rErSF7cJbSzLwHIgceg9WPQdnPAyJzHuVl

In [153]:
contour(x, y, f, fill=true, c=:gray)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
<image width="514" height="381" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAAgIAAAF9CAYAAAB22QBFAAAgAElEQVR4nO1d24KzrA4Fv//9n3iP
7IsWCGElBA+t1qyLmRZDQKvmSIghhBQcji8hxvjtKTgcl0VK/np2nI/l2xNwOBwOh8PxPbgi4HA4
HA7Hg+GKgMPhcDgcD0YMniPgOAEe+5+HX7MXPC4+D79mjj1wj4DD4XA4HA+GKwIOh8PhcDwYrgg4
HA6Hw/FgeI6AYwpPjWM/9bx/GU+Mqz/xnB1juEfA4XA4HI4HwxUBh8PhcDgeDFcEHA6Hw+F4MDxH
wPFz8e9fOx/HPfBr8fdfOx+HDPcIOBwOh8PxYLgi4HA4HA7Hg+GKgMPhcDgcD4bnCPww7hwrv/Pc
Lfj18zsaT4hX3/Uc7zpvR8V/356Aw/HrcKG/H+gaugByOI6BhwYcDofD4XgwXBFwOBwOh+PB8ByB
G+KuruY7zPuMOd7hvO+IM0IDdwg33GGOCHed9xPgOQIOx4FwRWIOe4SD5w04HMfAQwMOh8PhcDwY
7hG4OO5gDV5tjnvms/dc3CPwXHzKG2G9H67mHZHmfbV5PhHuEXA4HA6H48Fwj4DjsZixtL/pZYA8
D+d4LiSbb8+1QZbkDD9rf7dYHb8O9wg4HA6Hw/FguEfgIrhiHPibc/qEBf4xj8DmngrPC94vKs6w
qu92DQY42vOw1zvyKbgX5vtwj4DD4XA4HA+GewQct8bR1v+Ul8BMuW+cCabH89yCnbF7zBLwtPYV
2q2W6NF0DsfV4B4Bh8PhcDgeDPcInIw7xHI/NcczYvKH05mo5ngKnbf3FVle4147wwbedWYzVvlF
rqGGM7wMV/Nm3LVWwl3hioDjNviE0J8SpldbUngDIbYVe173U1cFCBY0tocLHL8EDw04HA6Hw/Fg
uEfA4bghrmz9uxXscNwLrggciKu9nK8W+9+bI3B0nB/yu0m1wavda1fGjAoCr6pVibnYb7JX+bpD
nN6VzmPgioDjq5BeNh+J8+9QNmZpj+x7RH8HBswHMHfenl8gs3Sh5jgfrgg4HCfDhf7+nefc8nM4
zoMnCzocDofD8WC4R2AjrmalfXM52h46MTRg4rgvzr8nD2GG1j0C94bV77ArvyCEr+YY7PGuXM1b
c7X53AGuCDhOwV4ha+W5J87vioDjSFjzC2aE0h0S9hz3hysCDseBcOUAQxJUewSdW34OxzHwHAGH
w+FwOB4M9wgY8E3r6xNj717CZ3Sx767jbx3ni6EB9wg4KKaWI16sXsHReQNnjGOFe490uCLgmMLR
sX+x7w6h74qA48oQt0VGtDuWV8KxXfg5AFwRcDwCZwjeb+2QOEt7N+zJBzjDEnVr0vHrcEWA4Vsv
2Csu/zva5T+z1G+P9X+G0L6cImCmvAh+WHE5CuYwwg+FEEL4nqK1t8jVL8GTBR0Oh8PheDDcI+A4
BXvX/D/SI2CimuN5GdyksM7VcEZtAoeDwxUBx2MxVelwTwLijvkcQXs77HB9780bwNNxIev4bTxW
Efi1JYEfs4Kt/Xda6p/wCJyiCOzp64rAHJCAfsB12ZVL4HkDlx77W3isIvBU7K33f7TQv40iAFsB
3YeWFLoiIOChIYjdiYa+/PDR8GRBh8PhcDgeDPcIOH4G3Eqm3/cuhbxa4aI9dGdjJk5/9B4CU30P
cp27ley4Ox6hCDw1H+AM4Xd0GODI0MC0ImAcd2Y+R/fdO45jEj+Ud7C7vPHB5+15A9fFIxQBxzk4
xAL/lCKwY4xZ2iP77h3HcQBuqBz8kpBynA/PEXA4HA6H48Fwj4DjUrBa+NY2fnSL12Lr2FvGsY69
h+5szFijVlpEZ207El6nwPGL+DlFwPMBBm3GMd4HVNozQgOHKAIb+UttU2O7IvAM3DBcEMLczoef
Osejtzv2vIF5/Jwi4JAhCsiNwu8SikDXcvwcZ2hdEXgwbqochDBOLLyrgHPY4IqA42vYIrA1V/8e
vlvoXRHAuFpogLd9VKjxsQHJL1mWjnvCkwUdDofD4Xgwbu0R+KV8gFNc0hrNwDK2jPMpa9sa8//m
HI9ok3A3j4BDQUq3DBeUGXvewGXH3oNbKwJPg1VYSvTvxqlxNgvvvUJ2w5gfn6PnDeyuDHjXF+cu
7Kz3fyTM1/o9t61JhT//m94crgg4TsdeBeAMxUTMQTB4R85IktRwFaFvHfNTJYa35gNk/qP+1r57
hdzRZZYdjlm4ImDAJ8IAmwTQqP9GoXS2cLUm/z1NEZi6zy6iHJiFvnsExrjBqoPNuxwecB53DRfc
AZ4s6HA4HA7Hg+EegYvC6gk4gufHPQJCH6nfV+d6Un6C1Vsj4Srhgj3L/xTiriludMXHGL+7fHAv
6Fy/6B3YvWFQCJ43cGG4IuAwYY+wtLj/tWOjNo2nRPfJ0MDWEI2GqygCn0KTwZ5/ww/lCGzJG5Bo
dyHzI7+pJ2E6jsBtFIFPvdC+lQ+wNY5OGud4HiCMTbxm6S+mCMx6BMJGXiI/AVdRBM7wCJgFNOiL
npVbewQQLuIlyPilvIG9PK3jXO0e9BwBh8PhcDgejNt4BH4Zu/IBPhQXN9N304u/5xHYaenPhiUQ
rKTnewSsdPZ5bHXFo7aU0uacmlsAhAu+ian8jfJhHOpwnAtXBByb8Y0wgKYIWNu0eXWCczI0sCeX
QHqXXyUMYB0TC2/cH7/4++u0dd0+Cg1k4TnKMdByBI6sI4Awvd2xYU8Dh0PCJRWBT7zQzhjjG/kA
ewWvlQ62gbneXRGwWPt7Y//tcGOPQJ9uifENRQAhTYihFK1FfXTlAPWVaOo8e1zjCh6AL5cynrq2
B+c87F7h8IGY/qfyE6y4pCLwyxCFsa2zjdcJ7nA01xnBu2mcDykC4YCxGSvxeEcPBNyov4TLKAJ7
EwOJGMmKAhb6iF9k35OoHIwSEK9xNXfghOS8lv2+CpIIpTfh4+GC8+HJgg6Hw+FwPBjuEXg4rBb7
EWNI//e25e+WNs36l/iOx9bpy/eB9T/jEbiKl+DsOvn5mjVeAjX0wI/NXScYliBtUfMmAM+DtW3E
E/U7Ap9wgzuuj68qAldxZW7B0fkA4rWYFFIanVXIWuc6K4y/oQhI4ZRtY4euraNRhP1sLoHafhFF
wLpsACXmvbqP4/y8rbrxAV1EgpfzUoT+AH3Gwo1wwbyBEIRrebG8gU/hW4qZewROglWoKgxsvDbG
xU2KwGDMyyoChGb7tVDOO2Ce2ufRsWbQrhkpDZDU1PdI7F4+OCgnXMnGFjhqSyFB5YAPrSkHI0v9
VkqB9IMddJ+cUemw9CQ87iLY7wLPEXA4HA6H48Fwj4CjwygMYLHK406rHPHSxg4Db4Rt7AFdmAxL
gM98IOSF4IAeAWCHfiXUBoaEljpYJviiRW295YfuSbNr35Q2sM3pHyOpU8DmEAc5AlvrIWzpL8Et
a0cID1EE9r4grfHcLW520mjndVZoQOF/NUUAXa+5sQfzAUJ/JiQiCXtpbDomhzWM8BVFAMHo7g9h
HOevMhZqHB3/qeS8wTJFNPaMME5hVq34Ig6OyU8NDdqwrva9vIE9oY074BGKwOVxsNCfErxWuoso
AgHQaeNwwb9H6M95I/rz5eNJ58aBlU5AdxGxg2W2MLeB0pCFNS48BPgbrXL6v2lTlIPX//4e05SD
bWsYvow8/wMVgrNXlzj2wRUBh4hZ9/wWRQDRc7qg0

In [154]:
surface(x, y, f)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
<polyline clip-path="url(#clip00)" style="stroke:#00002d; stroke-width:1; stroke-opacity:1; fill:none" points="
 6.68429,178.161 5.60444,178.164 5.24449,178.851 5.24449,179.674 5.60444,180.633 6.32434,181.317 7.76414,182.273 8.84399,183.092 9.56389,184.188 9.92384,185.146 
 9.92384,186.381 9.56389,187.068 9.20394,187.343 8.12409,187.346 6.68429,186.801 5.60444,185.982 5.24449,185.434 4.88453,184.475 4.88453,183.241 5.24449,182.554 
 5.96439,182.003 7.04424,182 8.48404,182.133 9.20394,181.994 9.56389,181.308 9.56389,180.485 9.20394,179.526 8.12409,178.706 6.68429,178.161 
 "/>
 
 
 
<polyline clip-path="url(#clip00)" style="stroke:#000000; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,279.187 21.7148,279.187 15.3788,283.243 21.7148,279.187 21.7148,266.684 18.5468,268.711 21.7148,266.684 21.7148,254.18 15.3788,258.236 21.7148,254.18 
 21.7148,241.677 18.5468,243.704 21.7148,241.677 21.7148,229.173 15.3788,233.229 21.7148,229.173 21.7148,216.67 18.5468,218.697 21.7148,216.67 21.7148,204.166 
 15.3788,208.222 21.7148,204.166 21.7148,191.663 18.5468,193.691 21.7148,191.663 21.7148,179.159 15.3788,183.215 21.7148,179.159 21.7148,166.656 18.5468,168.684 
 21.7148,166.656 21.7148,154.152 15.3788,158.208 21.7148,154.152 
 "/>
 
 
 
 
 
<polyline clip-path="url(#clip00)" style="stroke:#000000; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,279.187 21.7148,279.187 15.3788,283.243 21.7148,279.187 56.674,292.408 53.5061,294.436 56.674,292.408 91.6333,305.628 85.2973,309.684 91.6333,305.628 
 126.593,318.849 123.425,320.877 126.593,318.849 161.552,332.069 155.216,336.125 161.552,332.069 196.511,345.29 193.343,347.318 196.511,345.29 231.47,358.511 
 225.134,362.566 231.47,358.511 266.429,371.731 263.261,373.759 266.429,371.731 301.389,384.952 295.053,389.008 301.389,384.952 
 "/>
 
 
 
 
 
<polyline clip-path="url(#clip00)" style="stroke:#000000; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 301.389,384.952 301.389,384.952 306.982,387.067 301.389,384.952 330.723,366.175 333.52,367.233 330.723,366.175 360.057,347.398 365.651,349.513 360.057,347.398 
 389.392,328.621 392.188,329.679 389.392,328.621 418.726,309.844 424.319,311.96 418.726,309.844 448.06,291.067 450.857,292.125 448.06,291.067 477.394,272.29 
 482.988,274.406 477.394,272.29 506.729,253.514 509.525,254.571 506.729,253.514 536.063,234.737 541.656,236.852 536.063,234.737 
 "/>
 
<image width="514" height="381" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAAgIAAAF9CAYAAAB22QBFAAAgAElEQVR4nOy9fcguW3sf9LvWzH0/
z977nDfJmw+TkKTUNkRq+pFgTCRE/xDUgLSgbUIpWFRaQaXoP7EgYk0VIVSFoFT8QEStNBahIFRB
KtTQVImJxIjYikmNtkls+5r3fc/ZH899r8s/1vW5Zu5nP3vvc87e+9zXb/Pse2bNmjUza2bW77eu
61priJlRKBQKhULhOtHe9gkUCoVCoVB4eyghUCgUCoXCFaOEQKFQKBQKV4wSAoVCoVAoXDFKCBQK
hUKhcMUoIVAoFAqFwhWjhEChUCgUCleMEgKFQqFQKFwxSggUCoVCoXDFKCFQKBQKhcIVo4RAoVAo
FApXjBIChUKhUChcMUoIFAqFQqFwxSghUCgUCoXCFaOEQKFQKBQKV4wSAoVCoVAoXDFKCBQKhUKh
cMUoIVAoFAqFwhWjhEChUCgUCleMEgKFQqFQKFwxSggUCoVCoXDFKCFQKBQKhcIVo4RAoVAoFApX
jBIChUKhUChcMUoIFAqFQqFwxSghUCgUCoXCFaOEQKFQKBQKV4wSAoVCoVAoXDFKCBQKhUKhcMUo
IVAoFAqFwhWjhEChUCgUCleMEgKFQqFQKFwxSggUCoVCoXDFKCFQKBQKhcIVo4RAoVAoFApXjBIC
hUKhUChcMUoIFAqFQqFwxSghUCgUCoXCFaOEQKFQKBQKV4wSAoVCoVAoXDFKCBQKhUKhcMUoIVAo
FAqFwhWjhEChUCgUCleMEgKFQqFQKFwxSggUCoVCoXDFKCFQKBQKhcIVo4RAoVAoFApXjBIChUKh
UChcMUoIFAqFQqFwxSghUCgUCoXCFaOEQKFQKBQKV4wSAoVCoVAoXDFKCBQKhUKhcMUoIVAoFAqF
whWjhEChUCgUCleMEgKFQqFQKFwxSggUCoVCoXDFKCFQKBQKhcIVo4RAoVAoFApXjBIChUKhUChc
MUoIFAqFQqFwxSghUCgUCoXCFaOEQKFQKBQKV4wSAoVCoVAoXDFKCBQKhUKhcMUoIVAoFAqFwhWj
hEChUCgUCleMEgKFQqFQKFwxSggUCoVCoXDFKCFQKBQKhcIVo4RAoVAoFApXjBIChUKhUChcMUoI
FAqFQqFwxSghUCgUCoXCFaOEQKFQKBQKV4wSAoVCoVAoXDFKCBQKhUKhcMUoIVAoFAqFwhWjhECh
UCgUCleMEgKFQqFQKFwxSggUCoVCoXDFKCFQKBQKhcIVo4RAoVAoFApXjBIChUKhUChcMUoIFAqF
QqFwxSghUC

## Exercícios

- Faça um gráfico de $f(x) = x^2 - 5x + 6$.
- Faça um gráfico de $f(x) = 2*sin(x)*cos(x)$.
- Faça um gráfico da função $f(x) = 1/x^2$, limitando a visão ao conjunto $[-2,2]\times[-2,2]$.
- Faça uma animação de pontos aparecendo na tela, um de cada vez.
- Faça uma função que recebe $n$ e desenho um circunferência de raio 1, e dois polígonos regulares de $n$ lados.
Um que circunscreve e outro que inscreve a circunferência. 