# Método do Gradiente

O método do Gradiente é definido pela direção de máximo decréscimo
$d^k = -\nabla f(x^k)$. É importante notar que o método é ineficiente sem a busca linear.
Aqui, vamos implementar a busca linear de Armijo, que pede que o tamanho de passo $\lambda_k$ seja tal que
$$ f(x^k + \lambda_kd^k) < f(x^k) + \alpha\lambda_k\nabla f(x^k)^Td^k, $$
onde $\alpha\in(0,1)$ (usaremos $\alpha = 0.5$.

Vamos considerar como teste inicial a função
$$ f(x) = 4x_1^2 + 9x_1^2, $$
cujo gradiente é
$$ \nabla f(x) = \left(\begin{array}{c} 8x_1 \\ 18x_2 \end{array}\right), $$
a partir do ponto $x^0 = (1,1)$.

In [1]:
f(x) = x[1]^2 + 4*x[2]^2;
∇f(x) = [2*x[1]; 8*x[2]];
x0 = [1.0; 1.5];

In [3]:
using Plots
gr()
contour(linspace(-3,3,100), linspace(-3,3,100),
    (x,y)->f([x;y]))

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -3 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 3 
 
 
 -3 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 3 
 
 
<polyline clip-path="url(#clip02)" style="stroke:#f57d15; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 35.4331,340.094 40.4899,341.248 45.5468,342.379 49.0974,343.156 50.6037,343.478 55.6605,344.535 60.7174,345.569 65.7743,346.58 67.5383,346.925 70.8311,347.553 
 75.888,348.496 80.9449,349.415 86.0017,350.313 88.206,350.694 91.0586,351.176 96.1155,352.009 101.172,352.82 106.229,353.609 111.286,354.376 111.881,354.463 
 116.343,355.106 121.4,355.812 126.457,356.498 131.514,357.162 136.57,357.804 140.058,358.232 141.627,358.421 146.684,359.007 151.741,359.572 156.798,360.117 
 161.855,360.64 166.912,361.143 171.969,361.625 176.106,362.001 177.025,362.083 182.082,362.514 187.139,362.923 192.196,363.312 197.253,363.681 202.31,364.029 
 207.367,364.357 212.423,364.664 217.48,364.951 222.537,365.217 227.594,365.463 232.651,365.689 234.674,365.771 237.708,365.891 242.765,366.071 247.822,366.232 
 252.878,366.372 257.935,366.492 262.992,366.593 268.049,366.673 273.106,366.733 278.163,366.773 283.22,366.793 288.276,366.793 293.333,366.773 298.39,366.733 
 303.447,366.673 308.504,366.593 313.561,366.492 318.618,366.372 323.675,366.232 328.731,366.071 333.788,365.891 336.822,365.771 338.845,365.689 343.902,365.463 
 348.959,365.217 354.016,364.951 359.073,364.664 364.129,364.357 369.186,364.029 374.243,363.681 379.3,363.312 384.357,362.923 389.414,362.514 394.471,362.083 
 395.39,362.001 399.528,361.625 404.584,361.143 409.641,360.64 414.698,360.117 419.755,359.572 424.812,359.007 429.869,358.421 431.438,358.232 434.926,357.804 
 439.983,357.162 445.039,356.498 450.096,355.812 455.153,355.106 459.615,354.463 460.21,354.376 465.267,353.609 470.324,352.82 475.381,352.009 480.437,351.176 
 483.29,350.694 485.494,350.313 490.551,349.415 495.608,348.496 500.665,347.553 503.958,346.925 505.722,346.58 510.779,345.569 515.836,344.535 520.892,343.478 
 522.399,343.156 525.949,342.379 531.006,341.248 536.063,340.094 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#fb9c07; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 536.063,350.145 533.535,350.694 531.006,351.231 525.949,352.283 520.892,353.313 515.836,354.321 515.105,354.463 510.779,355.288 505.722,356.23 500.665,357.151 
 495.608,358.05 494.56,358.232 490.551,358.913 485.494,359.75 480.437,360.567 475.381,361.363 471.212,362.001 470.324,362.135 465.267,362.872 460.21,363.589 
 455.153,364.285 450.096,364.961 445.039,365.617 443.816,365.771 439.983,366.242 434.926,366.843 429.869,367.425 424.812,367.986 419.755,368.527 414.698,369.048 
 409.742,369.54 409.641,369.549 404.584,370.021 399.528,370.472 394.471,370.904 389.414,371.316 384.357,371.709 379.3,372.082 374.243,372.435 369.186,372.769 
 364.129,373.083 360.253,373.309 359.073,373.376 354.016,373.645 348.959,373.895 343.902,374.126 338.845,374.338 333.788,374.53 328.731,374.703 323.675,374.857 
 318.618,374.991 313.561,375.107 308.504,375.203 303.447,375.28 298.39,375.338 293.333,375.376 288.276,375.395 283.22,375.395 278.163,375.376 273.106,375.338 
 268.049,375.28 262.992,375.203 257.935,375.107 252.878,374.991 247.822,374.857 242.765,374.703 237.708,374.53 232.651,374.338 227.594,374.126 222.537,373.895 
 217.48,373.645 212.423,373.376 211.244,373.309 207.367,373.083 202.31,372.769 197.253,372.435 192.196,372.082 187.139,371.709 182.082,371.316 177.025,370.904 
 171.969,370.472 166.912,370.021 161.855,369.549 161.754,369.54 156.798,369.048 151.741,368.527 146.684,367.986 141.627,367.425 136.57,366.843 131.514,366.242 
 127.68,365.771 126.457,365.617 121.4,364.961 116.343,364.285 111.286,363.589 106.229,362.872 101.172,362.135 100.284,362.001 96.1155,361.363 91.0586,360.567 
 86.0017,359.75 80.9449,358.913 76.9364,358.232 75.88

In [4]:
d = -∇f(x0)

2-element Array{Float64,1}:
  -2.0
 -12.0

In [5]:
t = 1.0
f(x0+t*d), f(x0)+0.5*t*dot(∇f(x0),d)

(442.0,-64.0)

Como $f(x^0+d) > f(x^0)$, então a condição de Armijo não é satisfeito. Vamos atualizar o tamanho do passo sempre multiplicando o passo por 0.9.
Então

In [6]:
t = t*0.9
f(x0+t*d), f(x0)+0.5*t*dot(∇f(x0),d)

(346.6,-56.60000000000001)

O valor já melhorou. Vamos tentar de novo.

In [7]:
t = t*0.9
f(x0+t*d), f(x0)+0.5*t*dot(∇f(x0),d)

(270.6580000000001,-49.940000000000005)

In [8]:
t = t*0.9
f(x0+t*d), f(x0)+0.5*t*dot(∇f(x0),d)

(210.34378000000007,-43.946000000000005)

Como vemos, a ideia é repetir esse diminuição de $t$ até que a condição seja satisfeita. Vamos fazer isso com o while

In [9]:
while f(x0 + t*d) > f(x0) + 0.5*t*dot(∇f(x0),d)
    t = t*0.9;
end
t

0.12157665459056936

In [10]:
x1 = x0 + t*d

2-element Array{Float64,1}:
 0.756847 
 0.0410801

O método se repete agora a partir de x1

In [11]:
d = -∇f(x1);
t = 1.0;
while f(x1 + t*d) > f(x1) + 0.5*t*dot(∇f(x1),d)
    t = t*0.9;
end
x2 = x1 + t*d

2-element Array{Float64,1}:
  0.105251
 -0.100389

In [12]:
d = -∇f(x2);
t = 1.0;
while f(x2 + t*d) > f(x2) + 0.5*t*dot(∇f(x2),d)
    t = t*0.9;
end
x3 = x2 + t*d

2-element Array{Float64,1}:
  0.0796591 
 -0.00274933

Nós precisamos repetir esses passos até que $\Vert\nabla f(x^k)\Vert$ seja suficientemente pequeno. Pra fazer isso, vamos usar apenas uma variável para $x^k$ e atualizá-la.

In [13]:
x = copy(x0); # Cópia de x0
while norm(∇f(x)) > 1e-5
    d = -∇f(x);
    t = 1.0;
    while f(x + t*d) > f(x) + 0.5*t*dot(∇f(x),d)
        t = t*0.9;
    end
    x = x + t*d
end
x

2-element Array{Float64,1}:
 1.32742e-6
 9.36671e-7

Agora sim, temos a solução esperada (suficientemente próximo).

O método então, será esse código. Vamos criar uma função para ele (sempre crie funções)

In [14]:
function gradient_method(f, ∇f, x0) # Precisamos dar um nome e colocar os argumentos de entrada
    x = copy(x0) # Cópia de x0
    while norm(∇f(x)) > 1e-5
        d = -∇f(x)
        t = 1.0
        while f(x + t*d) > f(x) + 0.5*t*dot(∇f(x),d)
            t = t*0.9
        end
        x = x + t*d
    end
    return x # Precisamos retornar o ponto encontrado
end

gradient_method (generic function with 1 method)

Agora podemos brincar com essa função, mudando $f$ e $\nabla f$.

In [15]:
f(x) = (x[1]-1)^2 + 4*(x[2]-2)^2; ∇f(x) = [2*(x[1]-1); 8*(x[2]-2)];
x = gradient_method(f, ∇f, [0.0; 0.0])

2-element Array{Float64,1}:
 0.999997
 2.0     

Inclusive, podemos usar a notação `x->` para definir uma função na hora de chamar a função do método (para testar).

In [16]:
x = gradient_method(x->x[1]^2 + (1-x[2])^2 , x->[2*x[1]; -2*(1-x[2])], [2.0;3.0])

2-element Array{Float64,1}:
 3.08169e-7
 1.0       

Vamos testar também com a famosa função de Rosenbrock

In [20]:
f(x) = (1-x[1])^2 + 100*(x[2]-x[1]^2)^2;
∇f(x) = [-2*(1-x[1]) - 400*x[1]*(x[2]-x[1]^2);
         200*(x[2] - x[1]^2)]; # Posso escrever separado para ficar mais fácil de visualizar
x0 = [1.2; -0.8];
contour(linspace(-2,3,100), linspace(-2,3,100),
    (x,y)->f([x;y]), levels=200)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 3 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 3 
 
 
 
 
 
 
 
 
 
 
<polyline clip-path="url(#clip02)" style="stroke:#450a69; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 35.4331,305.838 36.6023,309.234 37.888,313.003 39.1608,316.772 40.4213,320.541 40.4899,320.747 41.7483,324.31 43.0665,328.08 44.3715,331.849 45.5468,335.273 
 45.6717,335.618 47.0365,339.387 48.3874,343.156 49.7251,346.925 50.6037,349.417 51.0793,350.694 52.4776,354.463 53.8619,358.232 55.2326,362.001 55.6605,363.182 
 56.6513,365.771 58.0836,369.54 59.5017,373.309 60.7174,376.568 60.9184,377.078 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#420a67; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 64.4726,377.078 63.0119,373.309 61.5361,369.54 60.7174,367.461 60.087,365.771 58.6751,362.001 57.2487,358.232 55.8075,354.463 55.6605,354.079 54.4336,350.694 
 53.0553,346.925 51.6627,343.156 50.6037,340.312 50.2775,339.387 48.9457,335.618 47.6004,331.849 46.2412,328.08 45.5468,326.164 44.9108,324.31 43.6114,320.541 
 42.2988,316.772 40.9726,313.003 40.4899,311.637 39.6871,309.234 38.4197,305.465 37.1394,301.696 35.8458,297.927 35.4331,296.728 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#3e0a65; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 35.4331,292.089 36.1457,294.158 37.4364,297.927 38.7136,301.696 39.9778,305.465 40.4899,306.998 41.28,309.234 42.6032,313.003 43.9126,316.772 45.2088,320.541 
 45.5468,321.527 46.5562,324.31 47.9122,328.08 49.2543,331.849 50.5827,335.618 50.6037,335.677 51.9853,339.387 53.3746,343.156 54.7496,346.925 55.6605,349.439 
 56.1412,350.694 57.5791,354.463 59.002,358.232 60.4105,362.001 60.7174,362.825 61.8777,365.771 63.35,369.54 64.8072,373.309 65.7743,375.827 66.2815,377.078 
 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#3b0963; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 70.0737,377.078 68.5746,373.309 67.0595,369.54 65.7743,366.371 65.5436,365.771 64.0945,362.001 62.63,358.232 61.1498,354.463 60.7174,353.366 59.7216,350.694 
 58.3064,346.925 56.876,343.156 55.6605,339.982 55.4449,339.387 54.0775,335.618 52.6957,331.849 51.299,328.08 50.6037,326.213 49.9333,324.31 48.5986,320.541 
 47.2498,316.772 45.8864,313.003 45.5468,312.067 44.5755,309.234 43.2732,305.465 41.957,301.696 40.6265,297.927 40.4899,297.54 39.3604,294.158 38.0902,290.389 
 36.8063,286.619 35.5085,282.85 35.4331,282.631 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#390962; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 35.4331,277.801 35.8742,279.081 37.1683,282.85 38.4482,286.619 39.7146,290.389 40.4899,292.711 41.0013,294.158 42.3279,297.927 43.6401,301.696 44.9384,305.465 
 45.5468,307.24 46.2704,309.234 47.6298,313.003 48.9746,316.772 50.3051,320.541 50.6037,321.389 51.6923,324.31 53.0848,328.08 54.4625,331.849 55.6605,335.157 
 55.837,335.618 57.2787,339.387 58.7048,343.156 60.1156,346.925 60.7174,348.54 61.5663,350.694 63.0422,354.463 64.5022,358.232 65.7743,361.547 65.9586,362.001 
 67.4858,365.771 68.9963,369.54 70.4908,373.309 70.8311,374.169 72.0474,377.078 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#350960; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 74.0727,377.078 72.5151,373.309 70.9402,369.54 70.8311,369.279 69.4436,365.771 67.938,362.001 66.4157,358.232 65.7743,356.652 64.9346,354.463 63.4794,350.694 
 62.0083,346.925 60.7174,343.65 60.5335,343.156 59.1273,339.387 57.7059,335.618 56.2688,331.849 55.6605,330.261 54.8707,328.08 53.4977,324.31 52.1096,320.541 
 50.706,316.772 50.6037,316.498 49.3733,313.003 48.0329,309.234 46.6778,305.465 45.5468,302.348 45.3233,301.696 44.0294,297.927 42.7214,294.158 41.399,290.389 
 40.4899,287.817 40.0902,286.619 38.828,282.85 37.5522,279.081 36.2623,275.312 35.4331,272.907 
 "/>
<polyline clip-path

In [24]:
contour(linspace(-2,3,400), linspace(-2,3,400),
(x,y)->f([x;y]), levels=[0.05;0.5;1;5])

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 3 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 3 
 
<polyline clip-path="url(#clip02)" style="stroke:#000003; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 415.017,3.93701 414.678,4.8722 414.357,5.80739 414.356,5.80961 413.98,6.74258 413.626,7.67777 413.292,8.61296 413.101,9.16353 412.945,9.54815 412.576,10.4833 
 412.228,11.4185 411.899,12.3537 411.847,12.5031 411.526,13.2889 411.164,14.2241 410.822,15.1593 410.592,15.8135 410.476,16.0945 410.099,17.0297 409.745,17.9649 
 409.409,18.9 409.337,19.103 409.034,19.8352 408.666,20.7704 408.319,21.7056 408.082,22.3663 407.968,22.6408 407.586,23.576 407.227,24.5112 406.886,25.4464 
 406.828,25.6084 406.504,26.3816 406.132,27.3168 405.781,28.252 405.573,28.8221 405.419,29.1871 405.034,30.1223 404.672,31.0575 404.328,31.9927 404.318,32.02 
 403.933,32.9279 403.559,33.8631 403.206,34.7983 403.064,35.1823 402.828,35.7335 402.443,36.6687 402.079,37.6039 401.809,38.3283 401.718,38.539 401.321,39.4742 
 400.948,40.4094 400.594,41.3446 400.554,41.4504 400.195,42.2798 399.811,43.215 399.449,44.1502 399.299,44.5425 399.062,45.0854 398.669,46.0206 398.297,46.9558 
 398.045,47.6155 397.923,47.8909 397.52,48.8261 397.14,49.7613 396.79,50.6683 396.778,50.6965 396.365,51.6317 395.976,52.5669 395.608,53.5021 395.535,53.6887 
 395.202,54.4373 394.805,55.3725 394.43,56.3077 394.281,56.6865 394.031,57.2428 393.626,58.178 393.244,59.1132 393.026,59.6623 392.851,60.0484 392.439,60.9836 
 392.05,61.9188 391.771,62.6156 391.662,62.854 391.243,63.7892 390.848,64.7244 390.516,65.5458 390.464,65.6596 390.038,66.5947 389.637,67.5299 389.262,68.4521 
 389.256,68.4651 388.824,69.4003 388.417,70.3355 388.032,71.2707 388.007,71.3307 387.599,72.2059 387.188,73.1411 386.798,74.0763 386.752,74.1854 386.365,75.0115 
 385.948,75.9466 385.554,76.8818 385.498,77.0167 385.119,77.817 384.699,78.7522 384.301,79.6874 384.243,79.8245 383.862,80.6226 383.439,81.5578 383.038,82.493 
 382.988,82.6087 382.594,83.4282 382.168,84.3634 381.764,85.2985 381.733,85.3696 381.315,86.2337 380.886,87.1689 380.48,88.1041 380.479,88.1072 380.024,89.0393 
 379.594,89.9745 379.224,90.8167 379.178,90.9097 378.721,91.8449 378.289,92.7801 377.969,93.5023 377.863,93.7153 377.406,94.6504 376.974,95.5856 376.715,96.1645 
 376.536,96.5208 376.079,97.456 375.647,98.3912 375.46,98.8041 375.196,99.3264 374.74,100.262 374.308,101.197 374.205,101.422 373.844,102.132 373.389,103.067 
 372.958,104.002 372.95,104.018 372.479,104.938 372.026,105.873 371.696,106.581 371.578,106.808 371.101,107.743 370.651,108.678 370.441,109.124 370.185,109.613 
 369.712,110.549 369.264,111.484 369.186,111.646 368.779,112.419 368.31,113.354 367.932,114.143 367.853,114.289 367.361,115.225 366.896,116.16 366.677,116.611 
 366.417,117.095 365.931,118.03 365.47,118.965 365.422,119.064 364.969,119.901 364.489,120.836 364.168,121.484 364.011,121.771 363.509,122.706 363.035,123.641 
 362.913,123.885 362.531,124.577 362.038,125.512 361.658,126.262 361.555,126.447 361.041,127.382 360.555,128.317 360.403,128.613 360.044,129.252 359.539,130.188 
 359.149,130.942 359.046,131.123 358.522,132.058 358.026,132.993 357.894,133.245 357.503,133.928 356.989,134.864 356.639,135.525 356.481,135.799 355.949,136.734 
 355.446,137.669 355.385,137.784 354.905,138.604 354.386,139.54 354.13,140.013 353.857,140.475 353.321,141.41 352.875,142.224 352.803,142.345 352.25,143.28 
 351.727,144.216 351.62,144.407 351.173,145.151 350.634,146.086 350.366,146.566 350.088,147.021 349.535,147.956 349.111,148.704 348.996,148.891 348.427,149.827 
 347.889,150.762 347.856,150.819 347.311,151.697 346.759,152.632 346.602,152.904 346.184,153.567 345.62,154.503 345.347,154.967 345.048,155.438 344.47,156.373 
 344.092,157.009 343.899,157.308 343.31,158.243 342.837,159.027 342.739,159.179 342.137,160.114 341.583,1

In [25]:
x = gradient_method(f, ∇f, x0)

2-element Array{Float64,1}:
 0.999989
 0.999978

Isso conclui o básico do método.

## Mais informações na implementação

Apesar do método estar implementado, queremos mais informações dele.
Queremos saber **quantas iterações** ele leva pra convergir e **em quanto tempo**.
Rapidamente, podemos fazer a parte de iterações.

In [27]:
function gradient_method(f, ∇f, x0) # Precisamos dar um nome e colocar os argumentos de entrada
    x = copy(x0) # Cópia de x0
    iter = 0
    while norm(∇f(x)) > 1e-5
        d = -∇f(x)
        t = 1.0
        while f(x + t*d) > f(x) + 0.5*t*dot(∇f(x),d)
            t = t*0.9
        end
        x = x + t*d
        iter = iter + 1
    end
    return x, iter # Precisamos retornar o ponto encontrado
end

gradient_method (generic function with 1 method)

In [28]:
x, iter = gradient_method(f, ∇f, x0)

([0.9999891261933653,0.9999782129526038],1816)

Para calcular o tempo temos as funções `tic` e `toc`, similares às funções do MatLab, mas vamos usar a função `time`, que é melhor para fazer comparações (que faremos depois).

In [29]:
function gradient_method(f, ∇f, x0) # Precisamos dar um nome e colocar os argumentos de entrada
    x = copy(x0) # Cópia de x0
    iter = 0
    start_time = time()
    while norm(∇f(x)) > 1e-5
        d = -∇f(x)
        t = 1.0
        while f(x + t*d) > f(x) + 0.5*t*dot(∇f(x),d)
            t = t*0.9
        end
        x = x + t*d
        iter = iter + 1
    end
    elapsed_time = time() - start_time
    return x, iter, elapsed_time # Precisamos retornar o ponto encontrado
end

gradient_method (generic function with 1 method)

In [30]:
x, iter, el_time = gradient_method(f, ∇f, x0)

([0.9999891261933653,0.9999782129526038],1816,0.035060882568359375)

Além disso, também queremos o valor da função e do gradiente na solução.

In [31]:
function gradient_method(f, ∇f, x0) # Precisamos dar um nome e colocar os argumentos de entrada
    x = copy(x0) # Cópia de x0
    iter = 0
    start_time = time()
    while norm(∇f(x)) > 1e-5
        d = -∇f(x)
        t = 1.0
        while f(x + t*d) > f(x) + 0.5*t*dot(∇f(x),d)
            t = t*0.9
        end
        x = x + t*d
        iter = iter + 1
    end
    elapsed_time = time() - start_time
    return x, f(x), ∇f(x), iter, elapsed_time # Precisamos retornar o ponto encontrado
end

gradient_method (generic function with 1 method)

In [32]:
x, fx, ∇fx, iter, el_time = gradient_method(f, ∇f, x0)

([0.9999891261933653,0.9999782129526038],1.183961096977204e-10,[-5.926838706009923e-6,-7.910473298622378e-6],1816,0.03397202491760254)

Agora, vamos limitar o número de iterações e o tempo de execução do algoritmo.
Para isso, vamos criar variáveis para essas quantidades. Depois vamos querer receber esses valores na chamada de função. Também vamos criar uma variável para a tolerância.

In [33]:
function gradient_method(f, ∇f, x0) # Precisamos dar um nome e colocar os argumentos de entrada
    tol = 1e-5
    max_iter = 1000
    max_time = 60 # Em segundos
    
    x = copy(x0) # Cópia de x0
    iter = 0
    start_time = time()
    elapsed_time = 0.0
    while norm(∇f(x)) > tol
        d = -∇f(x)
        t = 1.0
        while f(x + t*d) > f(x) + 0.5*t*dot(∇f(x),d)
            t = t*0.9
        end
        x = x + t*d
        iter = iter + 1
        if iter >= max_iter
            break
        end
        elapsed_time = time() - start_time
        if elapsed_time >= max_time
            break
        end
    end
    return x, f(x), ∇f(x), iter, elapsed_time # Precisamos retornar o ponto encontrado
end

gradient_method (generic function with 1 method)

In [34]:
x, fx, ∇fx, iter, el_time = gradient_method(f, ∇f, x0)

([0.9994031107078174,0.9988039099625171],3.56988505428105e-7,[-0.00012732354220518585,-0.0005335459889677097],1000,0.03200101852416992)

Note como o método agora não convergiu para esse problema. Da maneira que retornamos o valor do algoritmo, não temos como saber disso. Vamos criar uma variável sinalizando a saída (*exit flag*).
O mais utilizando para o exit flag é que se ele é 0, então ele convergiu. Cada outro valor indica um tipo de problema que aconteceu. Vamos usar 1 para o máximo de iterações e 2 para o máximo de tempo.

In [35]:
function gradient_method(f, ∇f, x0) # Precisamos dar um nome e colocar os argumentos de entrada
    tol = 1e-5
    max_iter = 1000
    max_time = 60 # Em segundos
    exit_flag = 0
    
    x = copy(x0) # Cópia de x0
    iter = 0
    start_time = time()
    elapsed_time = 0.0
    while norm(∇f(x)) > tol
        d = -∇f(x)
        t = 1.0
        while f(x + t*d) > f(x) + 0.5*t*dot(∇f(x),d)
            t = t*0.9
        end
        x = x + t*d
        iter = iter + 1
        if iter >= max_iter
            exit_flag = 1
            break
        end
        elapsed_time = time() - start_time
        if elapsed_time >= max_time
            exit_flag = 2
            break
        end
    end
    return x, f(x), ∇f(x), exit_flag, iter, elapsed_time # Precisamos retornar o ponto encontrado
end

gradient_method (generic function with 1 method)

In [36]:
x, fx, ∇fx, exit_flag, iter, el_time = gradient_method(f, ∇f, x0)
exit_flag

1

Agora vamos colocar os parâmetros `tol`, `max_iter` e `max_time` como parâmetros de entrada da função.
No entanto, algumas coisas têm que ser observadas. Esses parâmetros devem ser **opcionais**, com um **valor padrão**, caso o usuário não queira usá-los.
Em Julia, para criar uma parâmetro opcional, basta colocar o valor padrão na chamada, mas **todos** os argumentos opcionais devem estar à direita.

In [39]:
function media(a, b, p1 = 1.0, p2 = 1.0) # Função que calcula média ponderada.
    return (a*p1 + b*p2)/(p1+p2)
end

media (generic function with 3 methods)

In [40]:
media(3,5) # Chamada assim, os pesos são 1.0 e 1.0

4.0

In [41]:
media(3,5,3.0,2.0) # Pesos 3 e 2

3.8

In [42]:
media(3,5,3.0) # Pesos 3 e 1

3.5

Para calcular a média mudando o peso do segundo parâmetro, é obrigatório passar o peso do primeiro.

No nosso caso, isso é infactível, pois o usuário pode querer mudar apenas um dos parâmetros.
Para resolver esse problema, vamos usar **argumentos de palavra chave** (*keyword argument*).
Esses argumentos devem ser colocados depois de um `;` na chamada de função, e eles devem ser chamados usando o nome do parâmetro.

In [43]:
function media(a, b; p1 = 1.0, p2 = 1.0)
    return (a*p1 + b*p2)/(p1+p2)
end

media (generic function with 3 methods)

In [44]:
media(3,5)

4.0

In [45]:
media(3,5, p1=2)

3.6666666666666665

In [46]:
media(3,5, p2=2)

4.333333333333333

In [47]:
media(3,5, p1=3,p2=2)

3.8

Agora ao nosso caso.

In [48]:
function gradient_method(f, ∇f, x0; tol = 1e-5, max_iter = 1000, max_time = 60)
    exit_flag = 0
    
    x = copy(x0) # Cópia de x0
    iter = 0
    start_time = time()
    elapsed_time = 0.0
    while norm(∇f(x)) > tol
        d = -∇f(x)
        t = 1.0
        while f(x + t*d) > f(x) + 0.5*t*dot(∇f(x),d)
            t = t*0.9
        end
        x = x + t*d
        iter = iter + 1
        if iter >= max_iter
            exit_flag = 1
            break
        end
        elapsed_time = time() - start_time
        if elapsed_time >= max_time
            exit_flag = 2
            break
        end
    end
    return x, f(x), ∇f(x), exit_flag, iter, elapsed_time # Precisamos retornar o ponto encontrado
end

gradient_method (generic function with 1 method)

In [49]:
x, fx, ∇fx, exit_flag, iter, el_time = gradient_method(f, ∇f, x0)

([0.9994031107078174,0.9988039099625171],3.56988505428105e-7,[-0.00012732354220518585,-0.0005335459889677097],1,1000,0.03355002403259277)

In [50]:
x, fx, ∇fx, exit_flag, iter, el_time = gradient_method(f, ∇f, x0, max_iter=5000)

([0.9999891261933653,0.9999782129526038],1.183961096977204e-10,[-5.926838706009923e-6,-7.910473298622378e-6],0,1816,0.03480219841003418)

In [51]:
x, fx, ∇fx, exit_flag, iter, el_time = gradient_method(f, ∇f, x0, tol=1e-3)

([0.9989210992904697,0.9978385406541873],1.1663518645739358e-6,[-0.00023110098545843223,-0.0009643906986100959],0,872,0.0186460018157959)

In [52]:
x, fx, ∇fx, exit_flag, iter, el_time = gradient_method(f, ∇f, x0, max_iter=5000, tol=1e-8)

([0.999999989127975,0.999999978216308],1.1835807667890093e-16,[-5.887178694853094e-9,-7.92843568575563e-9],0,3190,0.06446409225463867)

In [53]:
x, fx, ∇fx, exit_flag, iter, el_time = gradient_method(f, ∇f, x0, max_iter=5000, tol=1e-8, max_time=0.1)

([0.999999989127975,0.999999978216308],1.1835807667890093e-16,[-5.887178694853094e-9,-7.92843568575563e-9],0,3190,0.05345606803894043)

Pra finalizar, devemos nos preocupar com a **qualidade** da implementação. Podemos levar isso a vários níveis, mas vamos nos preocupar, por enquanto, apenas com chamadas desnecessária de função.

In [54]:
n = 1000; (Q,R) = qr(rand(n,n));
G = Q*diagm(linspace(1,100,n))*Q'; # Uma matriz nxn com número de condição 100.
g = rand(n);
f(x) = 0.5*dot(x,G*x) + dot(g,x);
∇f(x) = G*x + g;
x, fx, ∇fx, exit_flag, iter, el_time = gradient_method(f, ∇f, zeros(n));
x, fx, ∇fx, exit_flag, iter, el_time = gradient_method(f, ∇f, zeros(n)); # Rodando duas vezes
println("exit_flag = $exit_flag")
println("iter = $iter")
println("el_time = $el_time")

exit_flag = 0
iter = 219
el_time = 2.012194871902466


Em Julia, as coisas são compiladas enquanto vão sendo feitas, então para comparar tempo, temos que rodar a função a primeira vez só para compilá-la.

Nesse exemplo, criamos uma função quadrática
$$ f(x) = \frac{1}{2}x^TGx + x^Tg, $$
onde a matriz $G$ é simétrica definida positiva e com número de condição 100, i.e., bem comportada.
A dimensão de $G$ é 1000, mas o número de iterações que precisamos para convergência é bem menor que 1000.
No entanto, o tempo que o algoritmo leva para convergir é bem maior que no exemplo de Rosenbrock.
Isso acontece porque cada avaliação da função $f$ e de $\nabla f$ tem uma multiplicação por matriz, o que deixa o método mais lento.
Então, precisamos diminuir o número de avaliações. A mudança abaixo, reduz drasticamente a quantidade de avaliações de função que fazemos.

In [55]:
function gradient_method(f, ∇f, x0; tol = 1e-5, max_iter = 1000, max_time = 60)
    exit_flag = 0
    
    x = copy(x0) # Cópia de x0
    iter = 0
    start_time = time()
    elapsed_time = 0.0
    fx = f(x)
    ∇fx = ∇f(x)
    while norm(∇fx) > tol
        d = -∇fx
        ∇fx_dot_d = dot(∇fx, d)
        t = 1.0
        while f(x + t*d) > fx + 0.5*t*∇fx_dot_d
            t = t*0.9
        end
        x = x + t*d
        fx = f(x)
        ∇fx = ∇f(x)
        iter = iter + 1
        if iter >= max_iter
            exit_flag = 1
            break
        end
        elapsed_time = time() - start_time
        if elapsed_time >= max_time
            exit_flag = 2
            break
        end
    end
    return x, fx, ∇fx, exit_flag, iter, elapsed_time # Precisamos retornar o ponto encontrado
end

gradient_method (generic function with 1 method)

In [56]:
x, fx, ∇fx, exit_flag, iter, el_time = gradient_method(f, ∇f, zeros(n));
x, fx, ∇fx, exit_flag, iter, el_time = gradient_method(f, ∇f, zeros(n)); # Rodando duas vezes
println("exit_flag = $exit_flag")
println("iter = $iter")
println("el_time = $el_time")

exit_flag = 0
iter = 219
el_time = 0.7955448627471924


Comparando o tempo das duas, vemos a economia obtida.

Algumas outras melhorias podem ser feitas, mas não vamos nos preocupar com elas agora.