# Método de Newton

Já implementamos o método do gradiente em detalhes, então não vamos levar tanto tempo com o método de Newton.
Na verdade, as diferenças são poucas, por enquanto.

O método de Newton é dado pelo passo $d^k$ que satisfaz
$$ \nabla^2 f(x^k)d^k = -\nabla f(x^k). $$

Uma parte extremamente importante desse método, é que ele resolve problemas quadráticos em uma iteração,
então vamos começar com um problema um pouco diferente.

In [1]:
f(x) = (exp(x[1]) - 1)^2 + (x[2] + exp(x[1]+1))^2
∇f(x) = [2*exp(x[1])*(exp(x[1])-1) + 2*exp(x[1]+1)*(x[2] + exp(x[1]+1));
    2*(x[2] + exp(x[1]+1))]
∇²f(x) = [4*exp(2*x[1])-2*exp(x[1])+2*x[2]*exp(x[1]+1)+4*exp(2*x[1]+2) 2*exp(x[1]+1);
    2*exp(x[1]+1) 2]
x0 = [0.5; 1.2];

In [2]:
using Plots
gr()
contour(linspace(-2,0.5,100), linspace(-4,0,100), (x,y)->f([x;y]), levels=100)

[Plots.jl] Initializing backend: gr


<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -2.0 
 
 
 -1.5 
 
 
 -1.0 
 
 
 -0.5 
 
 
 0.0 
 
 
 0.5 
 
 
 -4 
 
 
 -3 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 
 
 
 
 
 
 
<polyline clip-path="url(#clip02)" style="stroke:#d94d3c; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 130.942,377.078 126.457,375.743 121.4,374.28 117.945,373.309 116.343,372.855 111.286,371.459 106.229,370.103 104.071,369.54 101.172,368.777 96.1155,367.482 
 91.0586,366.224 89.1885,365.771 86.0017,364.992 80.9449,363.79 75.888,362.621 73.133,362.001 70.8311,361.479 65.7743,360.362 60.7174,359.276 55.7176,358.232 
 55.6605,358.22 50.6037,357.182 45.5468,356.172 40.4899,355.19 36.6454,354.463 35.4331,354.232 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#d74b3e; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 35.4331,351.365 40.4899,352.323 45.5468,353.309 50.6037,354.322 51.2887,354.463 55.6605,355.354 60.7174,356.414 65.7743,357.504 69.0647,358.232 70.8311,358.62 
 75.888,359.76 80.9449,360.933 85.4254,362.001 86.0017,362.138 91.0586,363.365 96.1155,364.628 100.565,365.771 101.172,365.925 106.229,367.247 111.286,368.608 
 114.653,369.54 116.343,370.003 121.4,371.429 126.457,372.896 127.841,373.309 131.514,374.395 136.57,375.933 140.229,377.078 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#d34841; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 149.183,377.078 146.684,376.256 141.627,374.637 137.354,373.309 136.57,373.063 131.514,371.52 126.457,370.021 124.789,369.54 121.4,368.554 116.343,367.123 
 111.419,365.771 111.286,365.734 106.229,364.368 101.172,363.041 97.0951,362.001 96.1155,361.75 91.0586,360.482 86.0017,359.251 81.6999,358.232 80.9449,358.052 
 75.888,356.875 70.8311,355.731 65.7743,354.619 65.0457,354.463 60.7174,353.527 55.6605,352.464 50.6037,351.43 46.9031,350.694 45.5468,350.422 40.4899,349.433 
 35.4331,348.471 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#d14643; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 35.4331,345.552 40.4899,346.517 42.5699,346.925 45.5468,347.503 50.6037,348.512 55.6605,349.549 60.7174,350.616 61.0767,350.694 65.7743,351.702 70.8311,352.818 
 75.888,353.966 78.0228,354.463 80.9449,355.139 86.0017,356.339 91.0586,357.575 93.6764,358.232 96.1155,358.84 101.172,360.133 106.229,361.464 108.216,362.001 
 111.286,362.825 116.343,364.219 121.4,365.654 121.799,365.771 126.457,367.116 131.514,368.62 134.52,369.54 136.57,370.162 141.627,371.738 146.517,373.309 
 146.684,373.362 151.741,375.015 156.798,376.719 157.836,377.078 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#ce4346; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 166.202,377.078 161.855,375.537 156.798,373.796 155.344,373.309 151.741,372.092 146.684,370.433 143.883,369.54 141.627,368.814 136.57,367.232 131.758,365.771 
 131.514,365.696 126.457,364.186 121.4,362.721 118.849,362.001 116.343,361.289 111.286,359.89 106.229,358.531 105.087,358.232 101.172,357.199 96.1155,355.901 
 91.0586,354.64 90.3296,354.463 86.0017,353.402 80.9449,352.197 75.888,351.026 74.4149,350.694 70.8311,349.878 65.7743,348.759 60.7174,347.671 57.1574,346.925 
 55.6605,346.609 50.6037,345.568 45.5468,344.555 40.4899,343.571 38.2989,343.156 35.4331,342.608 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#cb4148; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 35.4331,339.633 40.4899,340.594 45.5468,341.581 50.6037,342.597 53.3138,343.156 55.6605,343.636 60.7174,344.697 65.7743,345.789 70.8311,346.913 70.8846,346.925 
 75.888,348.055 80.9449,349.23 86.0017,350.439 87.041,350.694 91.0586,351.671 96.1155,352.937 101.172,354.239 102.021,354.463 106.229,355.566 111.286,356.929 
 115.981,358.232 116.343,358.332 121.4,359.76 126.457,361.23 129.036,362.001 131.514,362.736 136.57,364.277 141.329,365.771 141.627,365.863 146.684,367.479 
 151.741,369.144 152.913,369.54 156.798,370.843 161.855,372.59 

Para resolver sistemas lineares facilmente no Julia, podemos usar a barra invertida (`\`).

In [50]:
x = copy(x0);
d = -∇²f(x)\ ∇f(x);
x = x + d

2-element Array{Float64,1}:
  0.463436
 -4.31782 

In [51]:
d = -∇²f(x)\ ∇f(x);
x = x + d

2-element Array{Float64,1}:
  0.193888
 -3.15613 

In [52]:
d = -∇²f(x)\ ∇f(x);
x = x + d

2-element Array{Float64,1}:
  0.0762441
 -2.91167  

In [53]:
d = -∇²f(x)\ ∇f(x);
x = x + d

2-element Array{Float64,1}:
  0.0112067
 -2.74284  

In [54]:
d = -∇²f(x)\ ∇f(x);
x = x + d

2-element Array{Float64,1}:
  0.000360465
 -2.7191     

In [55]:
d = -∇²f(x)\ ∇f(x);
x = x + d

2-element Array{Float64,1}:
  3.52396e-7
 -2.71828   

In [56]:
norm(∇f(x))

1.7002054938085291e-6

Então o método de Newton convergiu, e com poucas iterações.
Em muitos casos, o passo puro, sem busca linear, já é suficiente.

In [109]:
function newton_method(f, ∇f, ∇²f, x0; tol = 1e-5, max_iter = 1000, max_time = 60)
    exit_flag = 0
    
    x = copy(x0) # Cópia de x0
    iter = 0
    start_time = time()
    elapsed_time = 0.0
    fx = f(x)
    ∇fx = ∇f(x)
    while norm(∇fx) > tol
        ∇²fx = ∇²f(x)
        d = -∇²fx\∇fx
        x = x + d
        fx = f(x)
        ∇fx = ∇f(x)
        iter = iter + 1
        if iter >= max_iter
            exit_flag = 1
            break
        end
        elapsed_time = time() - start_time
        if elapsed_time >= max_time
            exit_flag = 2
            break
        end
    end
    return x, fx, ∇fx, exit_flag, iter, elapsed_time # Precisamos retornar o ponto encontrado
end

newton_method (generic function with 1 method)

In [93]:
x, fx, ∇fx, exit_flag, iter, elapsed_time = newton_method(f, ∇f, ∇²f, x0)

([3.52396e-7,-2.71828],1.5526378286388286e-13,[1.66324e-6,3.52594e-7],0,6,5.3882598876953125e-5)

A implementação é essencialmente a mesma que a do método do gradiente sem a busca.

No entanto, veja que o método depende do ponto inicial.

In [94]:
x, fx, ∇fx, exit_flag, iter, elapsed_time = newton_method(f, ∇f, ∇²f, [-1.2;2.0])

([-13.3149,4.58709e-10],0.9999967007228948,[-3.29925e-6,8.96934e-6],0,13,7.104873657226562e-5)

O ponto que a função convergiu **não** é um ponto crítico.

In [113]:
x, fx, ∇fx, exit_flag, iter, elapsed_time = newton_method(f, ∇f, ∇²f, [-1.0,-0.9028])

([-1.0,-0.9028],0.409024240893728,[-0.270688,0.1944],4,0,0.0)

A primeira coisa a ver é que a matriz pode ser definida negativa, mas usando `\` não será possível.
Vamos usar o nosso código de LDLt.

In [96]:
function ldlt(A)
    (m,n) = size(A)
    if m != n
        error("Matriz tem que ser quadrada")
    end
    # Suporemos a matriz simétrica
    L = eye(A)
    D = zeros(n)
    ef = 0
    for j = 1:n
        s = 0.0;
        for k = 1:j-1
            s += L[j,k]^2*D[k]
        end
        D[j] = A[j,j] - s
        if abs(D[j]) < 1e-12
            ef = 1
        end
        for i = j+1:n
            s = 0.0
            for k = 1:j-1
                s += L[i,k]*L[j,k]*D[k]
            end
            L[i,j] = (A[i,j] - s)/D[j]
        end
    end
    return L, D, ef
end

ldlt (generic function with 1 method)

Agora adicionamos esse passo extra no método. Vamos continuar usando `\` para resolver o sistema triangular, mas para melhorar o método deveríamos mudar isso também.

In [111]:
function newton_method(f, ∇f, ∇²f, x0; tol = 1e-5, max_iter = 1000, max_time = 60)
    exit_flag = 0
    
    x = copy(x0) # Cópia de x0
    iter = 0
    start_time = time()
    elapsed_time = 0.0
    fx = f(x)
    ∇fx = ∇f(x)
    while norm(∇fx) > tol
        ∇²fx = ∇²f(x)
        L, D, ef = ldlt(∇²fx)
        if ef != 0
            exit_flag = 3
            break
        end
        if any(D .< 0)
            exit_flag = 4
            break
        end
        d = -L'\((L\∇fx)./D)
        x = x + d
        fx = f(x)
        ∇fx = ∇f(x)
        iter = iter + 1
        if iter >= max_iter
            exit_flag = 1
            break
        end
        elapsed_time = time() - start_time
        if elapsed_time >= max_time
            exit_flag = 2
            break
        end
    end
    return x, fx, ∇fx, exit_flag, iter, elapsed_time # Precisamos retornar o ponto encontrado
end

newton_method (generic function with 1 method)

In [106]:
x, fx, ∇fx, exit_flag, iter, elapsed_time = newton_method(f, ∇f, ∇²f, x0)
println("exit_flag = $exit_flag")

exit_flag = 0


In [107]:
x, fx, ∇fx, exit_flag, iter, elapsed_time = newton_method(f, ∇f, ∇²f, [-1.2;2.0])
println("exit_flag = $exit_flag")

exit_flag = 4


In [114]:
x, fx, ∇fx, exit_flag, iter, elapsed_time = newton_method(f, ∇f, ∇²f, [-1.0,-0.9028])
println("exit_flag = $exit_flag")

exit_flag = 4
