In [1]:
using ForwardDiff

In [2]:
f(x) = x[1]^2 + 4*x[2]^2 + 9*x[3]^2 + 16*x[4]^2
g(x) = ForwardDiff.gradient(f, x)

g (generic function with 1 method)

In [3]:
x0 = ones(4)

4-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0

In [4]:
f(x0)

30.0

In [5]:
g(x0)

4-element Array{Float64,1}:
  2.0
  8.0
 18.0
 32.0

In [8]:
function busca_linear(f, x, d; alpha = 0.5)
    g(x) = ForwardDiff.gradient(f, x)
    t = 1.0
    while f(x + t*d) > f(x) + alpha * t * dot(g(x), d)
        t = t * 0.9
    end
    return t
end

busca_linear (generic function with 1 method)

## DFP com cálculo da matriz (i.e., jeito errado)

In [49]:
H0 = eye(4)

4x4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [50]:
d0 = -H0*g(x0)

4-element Array{Float64,1}:
  -2.0
  -8.0
 -18.0
 -32.0

In [51]:
t0 = busca_linear(f, x0, d0)

0.03433683820292516

In [52]:
s0 = t0 * d0

4-element Array{Float64,1}:
 -0.0686737
 -0.274695 
 -0.618063 
 -1.09878  

In [53]:
x1 = x0 + s0

4-element Array{Float64,1}:
  0.931326 
  0.725305 
  0.381937 
 -0.0987788

In [54]:
y0 = g(x1) - g(x0)

4-element Array{Float64,1}:
  -0.137347
  -2.19756 
 -11.1251  
 -35.1609  

In [55]:
H1 = H0 - (H0*y0)*(H0*y0)'/dot(y0, H0*y0) + s0*s0'/dot(s0,y0)

4x4 Array{Float64,2}:
  1.00009       0.000187863  -0.00019925  -0.00190217
  0.000187863   0.998098     -0.014231    -0.0500666 
 -0.00019925   -0.014231      0.917603    -0.271867  
 -0.00190217   -0.0500666    -0.271867     0.120407  

In [56]:
d1 = -H1*g(x1)
t1 = busca_linear(f, x1, d1)
s1 = t1 * d1
x2 = x1 + s1
y1 = g(x2) - g(x1)
H2 = H1 - (H1*y1)*(H1*y1)'/dot(y1, H1*y1) + s1*s1'/dot(s1,y1)

4x4 Array{Float64,2}:
  1.00197      6.17218e-5  -0.0132559   0.0023134
  6.17218e-5   0.921783    -0.269731    0.0356977
 -0.0132559   -0.269731     0.147216   -0.012144 
  0.0023134    0.0356977   -0.012144    0.0328623

In [58]:
x2

4-element Array{Float64,1}:
  0.810598 
  0.347191 
 -0.0758179
  0.0655716

In [73]:
dot(y1,s1)

5.808975870534217

In [75]:
dot(y1,H1*y1)

99.26809990944342

In [78]:
d2 = -H2*g(x2)
t2 = busca_linear(f, x2, d2)
s2 = t2 * d2
x3 = x2 + s2
y2 = g(x3) - g(x2)
H3 = H2 - (H2*y2)*(H2*y2)'/dot(y2, H2*y2) + s2*s2'/dot(s2,y2)

4x4 Array{Float64,2}:
  1.01499     -0.0640034    0.0088965   9.63008e-5
 -0.0640034    0.132961    -0.00109211  2.57154e-7
  0.0088965   -0.00109211   0.0557354   2.55409e-5
  9.63008e-5   2.57154e-7   2.55409e-5  0.0312724 

In [79]:
dot(y2,s2)

1.4281606279299561

In [80]:
dot(y2,H2*y2)

12.399796350413904

In [71]:
x3

4-element Array{Float64,1}:
  0.6103   
 -0.0179509
  0.0454021
  0.0426629

In [30]:
d3 = -H3*g(x3)
t3 = busca_linear(f, x3, d3)
s3 = t3 * d3
x4 = x3 + s3
y3 = g(x4) - g(x3)
H4 = H3 - (H3*y3)*(H3*y3)'/dot(y3, H3*y3) + s3*s3'/dot(s3,y3)

4x4 Array{Float64,2}:
  0.500066     -0.000181916  -0.000116318  -0.000137965
 -0.000181916   0.125567      0.000335699   0.000408561
 -0.000116318   0.000335699   0.0557648     0.000249824
 -0.000137965   0.000408561   0.000249824   0.031551   

In [31]:
x4

4-element Array{Float64,1}:
 0.00980062
 0.0289743 
 0.0183306 
 0.0221766 

In [32]:
d4 = -H4*g(x4)
t4 = busca_linear(f, x4, d4)
s4 = t4 * d4
x5 = x4 + s4
y4 = g(x5) - g(x4)
H5 = H4 - (H4*y4)*(H4*y4)'/dot(y4, H4*y4) + s4*s4'/dot(s4,y4)

4x4 Array{Float64,2}:
  0.500233    -9.93512e-6  -3.65948e-6  -1.25965e-6
 -9.93512e-6   0.12501     -4.06166e-6  -1.13366e-6
 -3.65948e-6  -4.06166e-6   0.0555579    3.56616e-7
 -1.25965e-6  -1.13366e-6   3.56616e-7   0.0312502 

In [33]:
x5

4-element Array{Float64,1}:
 0.00113951
 0.00242168
 0.00154339
 0.00186842

In [36]:
inv(ForwardDiff.hessian(f, x5)) - H5

4x4 Array{Float64,2}:
 -0.000232927   9.93512e-6   3.65948e-6   1.25965e-6
  9.93512e-6   -1.00561e-5   4.06166e-6   1.13366e-6
  3.65948e-6    4.06166e-6  -2.29812e-6  -3.56616e-7
  1.25965e-6    1.13366e-6  -3.56616e-7  -2.38321e-7

## DFP sem a matriz

In [136]:
S = []
HY = []
mem = 2
Sigma = [] # dot(y,Hy)
Rho = [] # dot(y,s)

d0 = -g(x0)
t0 = busca_linear(f, x0, d0)
s0 = t0 * d0
x1 = x0 + s0
y0 = g(x1) - g(x0)
push!(S, s0)
push!(HY, y0)
push!(Sigma, dot(y0, y0))
push!(Rho, dot(y0, s0))

1-element Array{Any,1}:
 46.1232

In [137]:
function DFP_prod(S, HY, Sigma, Rho, v)
    n = length(S)
    if n == 1
        return v - HY[1]*dot(HY[1], v)/Sigma[1] + S[1]*dot(S[1], v)/Rho[1]
    else
        return v - HY[1]*dot(HY[1], v)/Sigma[1] + S[1]*dot(S[1], v)/Rho[1] - HY[2]*dot(HY[2], v)/Sigma[2] + S[2]*dot(S[2], v)/Rho[2]
    end
end

DFP_prod (generic function with 1 method)

In [138]:
d1 = -DFP_prod(S, HY, Sigma, Rho, g(x1)) #comofaz
t1 = busca_linear(f, x1, d1)
s1 = t1 * d1
x2 = x1 + s1
y1 = g(x2) - g(x1)

push!(Sigma, dot(y1, DFP_prod(S, HY, Sigma, Rho, y1)))
push!(S, s1)
push!(HY, y1)
push!(Rho, dot(y1, s1))

2-element Array{Any,1}:
 46.1232 
  5.80898

In [139]:
x2

4-element Array{Float64,1}:
  0.810598 
  0.347191 
 -0.0758179
  0.0655716

In [140]:
S

2-element Array{Any,1}:
 [-0.06867367640585031,-0.27469470562340126,-0.6180630876526528,-1.098778822493605] 
 [-0.12072855908038692,-0.3781138699949254,-0.45775483376374854,0.16435038124625523]

In [141]:
S[1]

4-element Array{Float64,1}:
 -0.0686737
 -0.274695 
 -0.618063 
 -1.09878  

In [142]:
S[2]

4-element Array{Float64,1}:
 -0.120729
 -0.378114
 -0.457755
  0.16435 

In [143]:
d2 = -DFP_prod(S, HY, Sigma, Rho, g(x2)) #comofaz
t2 = busca_linear(f, x2, d2)
s2 = t2 * d2
x3 = x2 + s2
y2 = g(x3) - g(x2)

push!(Sigma, dot(y2, DFP_prod(S, HY, Sigma, Rho, y2)))
push!(S, s2)
push!(HY, y2)
push!(Rho, dot(y2, s2))
shift!(S)
shift!(Sigma)
shift!(HY)
shift!(Rho)

46.12320206811342

In [125]:
d2

4-element Array{Float64,1}:
 -1.65669 
 -3.11588 
  0.721344
  0.240826

In [126]:
x3

4-element Array{Float64,1}:
  0.609183 
 -0.0316273
  0.0118807
  0.0948503

In [127]:
Sigma

3-element Array{Any,1}:
 1364.91  
   99.2681
   11.3931

In [128]:
Rho

3-element Array{Any,1}:
 46.1232 
  5.80898
  1.39504

In [144]:
d3 = -DFP_prod(S, HY, Sigma, Rho, g(x3)) #comofaz
t3 = busca_linear(f, x3, d3)
s3 = t3 * d3
x4 = x3 + s3
y3 = g(x4) - g(x3)

push!(Sigma, dot(y3, DFP_prod(S, HY, Sigma, Rho, y3)))
push!(S, s3)
push!(HY, y3)
push!(Rho, dot(y3, s3))
shift!(S)
shift!(Sigma)
shift!(HY)
shift!(Rho)

5.808975870534217

In [145]:
S

2-element Array{Any,1}:
 [-0.20141489363388285,-0.3788187061700164,0.08769863212192351,0.029278786238407867]   
 [-0.06476827234881977,-0.051922065632153326,-0.04344910068716255,-0.09338231945652309]

In [146]:
x4

4-element Array{Float64,1}:
  0.544415  
 -0.0835493 
 -0.0315684 
  0.00146803